"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Lead = { id: string; name: string; contact: string; level: string; target: string; source: string; status: string; date: string; account: string };

const fixtureLeads: Lead[] = [
  { id: "lead-1", name: "Lead •••1", contact: "+62 812••••1234", level: "N4", target: "JLPT N4 • Desember 2026", source: "Landing • Organik", status: "New", date: "05 Agustus 2026 • 20:14 WIB", account: "Belum terdaftar" },
  { id: "lead-2", name: "Lead •••2", contact: "+62 813••••9821", level: "N5", target: "JLPT N5", source: "Referral • AFF•••02", status: "Follow-up", date: "05 Agustus 2026 • 18:42 WIB", account: "Belum terdaftar" },
  { id: "lead-3", name: "Lead •••3", contact: "+62 857••••4402", level: "N4", target: "JLPT N4", source: "Blog • CTA", status: "Registered", date: "04 Agustus 2026 • 21:05 WIB", account: "Registered" },
  { id: "lead-4", name: "Lead •••4", contact: "+62 811••••3110", level: "N3", target: "JLPT N3", source: "Landing • Organik", status: "Follow-up", date: "04 Agustus 2026 • 15:30 WIB", account: "Belum terdaftar" },
];

export default function PlacementPage() {
  const [leads, setLeads] = useState(fixtureLeads);
  const [selectedId, setSelectedId] = useState("lead-1");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Semua");
  const [level, setLevel] = useState("Semua Level");
  const [feedback, setFeedback] = useState("");
  const [closeOpen, setCloseOpen] = useState(false);
  const [builderOpen, setBuilderOpen] = useState(false);
  const assignmentRef = useRef<HTMLElement>(null);
  const selected = leads.find((lead) => lead.id === selectedId) ?? leads[0];
  const visible = useMemo(() => leads.filter((lead) => (status === "Semua" || lead.status === status) && (level === "Semua Level" || lead.level === level) && `${lead.name} ${lead.level} ${lead.source} ${lead.status}`.toLowerCase().includes(query.toLowerCase())), [leads, status, level, query]);

  function markContacted() { setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status: "Follow-up" } : lead)); setFeedback("Status follow-up diperbarui."); }
  function closeLead() { setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status: "Closed" } : lead)); setCloseOpen(false); setFeedback("Status prospek ditutup."); }

  return <AdminShell current="placement"><main className="admin-page admin-a3-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • PLACEMENT BUILDER &amp; LEADS</p><h1>Placement Test Builder &amp; Leads</h1><p>Kelola konfigurasi placement, bank soal, rekomendasi level, lead, dan alur tindak lanjut.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={() => setFeedback("Laporan lead siap diekspor.")}>Export Data</button><button className="button button-primary" type="button" onClick={() => { assignmentRef.current?.scrollIntoView({ behavior: "smooth" }); assignmentRef.current?.focus(); }}>Tugaskan Tim</button><Link className="button button-dark" href="/admin/assessment-results">Assessment Results</Link></div></header>
    <section className="admin-kpi-grid">{[["Prospek Baru","48","Siswa baru menyelesaikan placement."],["Sudah Dihubungi","24","Sedang dalam proses konsultasi."],["Terdaftar Akun","18","Berhasil membuat akun siswa."],["Tingkat Konversi","37,5%","Persentase mendaftar program."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a3-filter-bar"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari kontak, level, kanal, atau status" /></label><div className="admin-filters">{["Semua","New","Follow-up","Registered"].map((item) => <button className={status === item ? "active" : ""} type="button" onClick={() => setStatus(item)} key={item}>{item}</button>)}</div><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}><option>Semua Level</option><option>N5</option><option>N4</option><option>N3</option></select></label></section>
    <div className="a3-list-detail"><section className="a3-list-panel"><header><h2>Lead Placement</h2><p>Daftar prospek yang menyelesaikan placement test.</p></header>{visible.map((lead) => <button className={selected.id === lead.id ? "active" : ""} type="button" onClick={() => { setSelectedId(lead.id); setFeedback(""); }} key={lead.id}><div><strong>{lead.name}</strong><small>Kontak tersimpan</small></div><span>{lead.level}</span><div><strong>Rekomendasi placement</strong><small>{lead.source}</small></div><b>{lead.status}</b><em>Detail</em></button>)}</section>
      <aside className="a3-detail-panel"><header><div><p className="admin-kicker">{selected.name.toUpperCase()}</p><h2>Rekomendasi {selected.level}</h2></div><span>{selected.status}</span></header><dl>{[["Nama",selected.name],["WhatsApp",selected.contact],["Target Ujian",selected.target],["Rekomendasi",selected.level],["Tanggal Pengerjaan",selected.date],["Kanal Pendaftaran",selected.source],["Status Akun",selected.account]].map(([term,value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl><section className="lead-pipeline"><p className="admin-kicker">ALUR TINDAK LANJUT</p>{["Placement selesai","Konsultasi admin","Buat akun siswa","Invoice dibuat","Membership aktif"].map((step,index) => <div className={index === 0 || selected.status !== "New" && index === 1 ? "done" : ""} key={step}><span>{index === 0 || selected.status !== "New" && index === 1 ? "✓" : index + 1}</span><strong>{step}</strong></div>)}</section><section className="lead-actions" ref={assignmentRef} tabIndex={-1}><label className="admin-field"><span>Tugaskan Kepada</span><select><option>Admin Konsultasi / Sales</option></select></label><label className="admin-field"><span>Catatan Tindak Lanjut</span><textarea defaultValue="Telah dihubungi via WhatsApp untuk konsultasi rekomendasi level N4." rows={3}/></label><div className="lead-action-buttons"><button className="button button-primary" type="button" onClick={markContacted}>Tandai Sudah Dihubungi</button><button className="button button-secondary" type="button" onClick={() => setFeedback("Tautan pendaftaran telah disiapkan untuk dikirim ke siswa.")}>Kirim Tautan Daftar</button><button className="button button-secondary danger" type="button" onClick={() => setCloseOpen(true)}>Tutup Prospek</button></div>{feedback && <p className="admin-local-feedback" role="status">{feedback}</p>}</section><aside className="a2-announcement"><strong>PRIVASI &amp; KEBIJAKAN</strong><p>Akses data nomor kontak prospek dijaga sesuai kebijakan privasi HIRU Academy.</p></aside></aside></div>

    <section className="placement-builder-panel placement-bento-compact"><header><div><p className="admin-kicker">PLACEMENT TEST BUILDER</p><h2>20 soal • 5 menit • hasil langsung</h2></div><span className="placement-config-badge">Siap Diedit</span></header><div className="placement-builder-metrics">{[["20","Soal"],["5m","Timer"],["4","Section"],["Auto","Result"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="placement-sections">{["Bunpou","Moji Goi","Dokkai","Choukai"].map((item) => <span key={item}>{item}</span>)}</div><div className="placement-builder-action"><button className="button button-primary" type="button" onClick={() => setBuilderOpen(true)}>Kelola Builder</button></div></section>

    {builderOpen && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setBuilderOpen(false)} aria-label="Tutup Placement Builder"/><section role="dialog" aria-modal="true" aria-labelledby="placement-builder-title" className="a4-dialog" style={{ maxWidth: "780px", width: "100%", padding: "28px" }}><header><p className="admin-kicker">PLACEMENT TEST BUILDER</p><h2 id="placement-builder-title">Konfigurasi Soal &amp; Algoritma Penilaian</h2><p>Kelola 20 butir soal placement, pembagian seksi kemampuan, dan bobot rekomendasi level.</p></header><div className="admin-form-grid" style={{ marginTop: "16px" }}><label className="admin-field"><span>Durasi Timer (Menit)</span><input type="number" defaultValue={5} /></label><label className="admin-field"><span>Jumlah Soal</span><input type="number" defaultValue={20} readOnly /></label><label className="admin-field"><span>Hasil Analisis</span><select defaultValue="auto"><option value="auto">Kalkulasi Otomatis (Rekomendasi N5–N1)</option></select></label><label className="admin-field"><span>Seksi Penilaian</span><input defaultValue="Bunpou, Moji Goi, Dokkai, Choukai" readOnly /></label></div><div style={{ marginTop: "16px", background: "#f8fafc", padding: "16px", borderRadius: "12px", border: "1px solid #dee1ea" }}><strong>Bank Soal Placement (20 Soal Terstandarisasi)</strong><p style={{ margin: "4px 0 0", fontSize: "13px", color: "var(--muted)" }}>Siswa akan menjawab 5 soal Bunpou, 5 soal Moji Goi, 5 soal Dokkai, dan 5 soal Choukai.</p></div><div style={{ display: "flex", justifyContent: "flex-end", gap: "12px", marginTop: "24px" }}><button className="button button-secondary" type="button" onClick={() => setBuilderOpen(false)}>Tutup</button><button className="button button-primary" type="button" onClick={() => { setBuilderOpen(false); setFeedback("Pengaturan placement test berhasil disimpan."); }}>Simpan Konfigurasi</button></div></section></div>}

    {closeOpen && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setCloseOpen(false)} aria-label="Batal tutup lead"/><section role="dialog" aria-modal="true" aria-labelledby="close-lead-title"><p className="admin-kicker">ADMIN • CONFIRMATION</p><h2 id="close-lead-title">Tutup prospek {selected.name}?</h2><span>Konfirmasi</span><p>Tindakan ini akan menandai prospek sebagai selesai atau tidak melanjutkan proses konsultasi.</p><label className="admin-field"><span>Alasan Penutupan</span><textarea defaultValue="Siswa memutuskan untuk belajar mandiri terlebih dahulu." rows={3}/></label><div><button className="button button-primary" type="button" onClick={closeLead}>Konfirmasi Penutupan</button><button className="button button-secondary" type="button" onClick={() => setCloseOpen(false)}>Batal</button></div></section></div>}
  </main></AdminShell>;
}
