"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Lead = { id: string; name: string; contact: string; level: string; target: string; source: string; status: string; date: string; account: string };

const fixtureLeads: Lead[] = [
  { id: "lead-1", name: "Lead •••1", contact: "+62 812••••1234", level: "N4", target: "JLPT N4 • Desember 2026", source: "Landing • Organik", status: "New", date: "05 Agustus 2026 • 20:14 WIB", account: "Belum terdaftar" },
  { id: "lead-2", name: "Lead •••2", contact: "+62 813••••9821", level: "N5", target: "JLPT N5", source: "Referral • AFF•••02", status: "Follow-up", date: "05 Agustus 2026 • 18:42 WIB", account: "Belum terdaftar" },
  { id: "lead-3", name: "Lead •••3", contact: "+62 857••••4402", level: "N4", target: "JLPT N4", source: "Blog • CTA", status: "Registered", date: "04 Agustus 2026 • 21:05 WIB", account: "Registered" },
  { id: "lead-4", name: "Lead •••4", contact: "+62 811••••3110", level: "N3", target: "JLPT N3", source: "Landing • Organik", status: "Follow-up", date: "Dari backend", account: "Belum terdaftar" },
];

export default function PlacementPage() {
  const [leads, setLeads] = useState(fixtureLeads);
  const [selectedId, setSelectedId] = useState("lead-1");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Semua");
  const [level, setLevel] = useState("Semua Level");
  const [feedback, setFeedback] = useState("");
  const [closeOpen, setCloseOpen] = useState(false);
  const assignmentRef = useRef<HTMLElement>(null);
  const selected = leads.find((lead) => lead.id === selectedId) ?? leads[0];
  const visible = useMemo(() => leads.filter((lead) => (status === "Semua" || lead.status === status) && (level === "Semua Level" || lead.level === level) && `${lead.name} ${lead.level} ${lead.source} ${lead.status}`.toLowerCase().includes(query.toLowerCase())), [leads, status, level, query]);

  function markContacted() { setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status: "Follow-up" } : lead)); setFeedback("Status Follow-up diperbarui pada fixture lokal."); }
  function closeLead() { setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status: "Closed" } : lead)); setCloseOpen(false); setFeedback("Lead ditutup pada fixture lokal; audit backend belum terhubung."); }

  return <AdminShell current="placement"><main className="admin-page admin-a3-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • PLACEMENT BUILDER &amp; LEADS</p><h1>Placement Test Builder &amp; Leads</h1><p>Kelola konfigurasi placement, question pool, rekomendasi level, lead, dan follow-up pipeline.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={() => setFeedback("Export memerlukan backend, permission, masking, dan audit.")}>Export</button><button className="button button-primary" type="button" onClick={() => { assignmentRef.current?.scrollIntoView({ behavior: "smooth" }); assignmentRef.current?.focus(); }}>Assign Leads</button><Link className="button button-dark" href="/admin/assessment-results">Assessment Results</Link></div></header>
    <section className="admin-kpi-grid">{[["New leads","Dinamis","Lead placement baru."],["Follow-up","Dinamis","Sudah dihubungi."],["Registered","Dinamis","Sudah membuat akun."],["Conversion","Dinamis","Dihitung dari backend."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a3-filter-bar"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari lead termasking, level, source, atau status" /></label><div className="admin-filters">{["Semua","New","Follow-up","Registered"].map((item) => <button className={status === item ? "active" : ""} type="button" onClick={() => setStatus(item)} key={item}>{item}</button>)}</div><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}><option>Semua Level</option><option>N5</option><option>N4</option><option>N3</option></select></label></section>
    <div className="a3-list-detail"><section className="a3-list-panel"><header><h2>Lead Placement</h2><p>Identitas dan kontak fixture tetap dimasking.</p></header>{visible.map((lead) => <button className={selected.id === lead.id ? "active" : ""} type="button" onClick={() => { setSelectedId(lead.id); setFeedback(""); }} key={lead.id}><div><strong>{lead.name}</strong><small>Kontak dimasking</small></div><span>{lead.level}</span><div><strong>Rekomendasi placement</strong><small>{lead.source}</small></div><b>{lead.status}</b><em>Detail</em></button>)}</section>
      <aside className="a3-detail-panel"><header><div><p className="admin-kicker">{selected.name.toUpperCase()}</p><h2>Rekomendasi {selected.level}</h2></div><span>{selected.status}</span></header><dl>{[["Nama",selected.name],["WhatsApp",selected.contact],["Target Ujian",selected.target],["Rekomendasi",selected.level],["Tanggal Pengerjaan",selected.date],["Source",selected.source],["Account Status",selected.account]].map(([term,value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl><section className="lead-pipeline"><p className="admin-kicker">FOLLOW-UP PIPELINE</p>{["Placement selesai","Follow-up admin","Register account","Invoice dibuat","Membership aktif"].map((step,index) => <div className={index === 0 || selected.status !== "New" && index === 1 ? "done" : ""} key={step}><span>{index === 0 || selected.status !== "New" && index === 1 ? "✓" : index + 1}</span><strong>{step}</strong></div>)}</section><section className="lead-actions" ref={assignmentRef} tabIndex={-1}><label className="admin-field"><span>Assign To</span><select><option>Admin / Sales</option></select></label><label className="admin-field"><span>Ringkasan</span><textarea defaultValue="Follow-up fixture; tidak tersimpan ke backend." rows={3}/></label><div><button className="button button-primary" type="button" onClick={markContacted}>Mark Contacted</button><button className="button button-secondary" type="button" onClick={() => setFeedback("Link daftar siap untuk handoff manual; tidak ada pesan yang dikirim.")}>Kirim Link Daftar</button><button className="button button-secondary danger" type="button" onClick={() => setCloseOpen(true)}>Close Lead</button></div>{feedback && <p className="admin-local-feedback" role="status">{feedback}</p>}</section><aside className="a2-announcement"><strong>PRIVACY</strong><p>Akses data lead, export, dan follow-up mengikuti role serta audit policy.</p></aside></aside></div>
    <section className="placement-builder-panel"><header><div><p className="admin-kicker">PLACEMENT TEST BUILDER</p><h2>20 soal • 5 menit • hasil langsung</h2></div><span>Config Ready</span></header><div className="placement-builder-metrics">{[["20","Soal"],["5m","Timer"],["4","Section"],["Auto","Result"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="placement-sections">{["Bunpou","Moji Goi","Dokkai","Choukai"].map((item) => <span key={item}>{item}</span>)}</div><p>Question pool, scoring, dan rekomendasi level mengikuti backend.</p><Link className="button button-dark" href="/admin/program/n4/chapters/chapter-4/quiz">Kelola Builder</Link></section>
    {closeOpen && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setCloseOpen(false)} aria-label="Batal tutup lead"/><section role="dialog" aria-modal="true" aria-labelledby="close-lead-title"><p className="admin-kicker">ADMIN • CONFIRMATION</p><h2 id="close-lead-title">Close {selected.name}?</h2><span>Confirm</span><p>Close Lead memerlukan alasan dan audit trail. Demo hanya mengubah fixture lokal.</p><label className="admin-field"><span>Alasan</span><textarea defaultValue="Lead tidak melanjutkan proses." rows={3}/></label><div><button className="button button-primary" type="button" onClick={closeLead}>Konfirmasi Tindakan</button><button className="button button-secondary" type="button" onClick={() => setCloseOpen(false)}>Batal</button></div></section></div>}
  </main></AdminShell>;
}
