"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Feedback = { id:string; member:string; plan:string; shortPlan:string; level:string; chapter:number; total:number; rating:number; consent:boolean; status:string; completed:boolean; text:string; material:number; practice:number; experience:number; recommendation:string };
type Dialog = "complete"|"candidate"|"blocked"|null;

const fixtures:Feedback[] = [
  { id:"f1",member:"Member •••1",plan:"Belajar Mandiri",shortPlan:"Mandiri",level:"N4",chapter:12,total:12,rating:5,consent:true,status:"Menunggu",completed:false,text:"Journey dan latihan membantu saya belajar lebih terarah. Penjelasan pada Reading masih bisa dibuat lebih rinci.",material:5,practice:4,experience:5,recommendation:"Kirim catatan Reading ke tim konten. Kandidat testimoni boleh dibuat karena izin tersedia." },
  { id:"f2",member:"Member •••2",plan:"Belajar dengan Sensei",shortPlan:"Sensei",level:"N3",chapter:20,total:20,rating:4,consent:false,status:"Perlu tindak lanjut",completed:false,text:"Sesi Sensei membantu, tetapi jadwal latihan perlu lebih mudah ditemukan.",material:4,practice:4,experience:3,recommendation:"Tinjau temuan navigasi latihan. Tetap sebagai tindak lanjut internal; tanpa izin tidak boleh menjadi kandidat testimoni." },
  { id:"f3",member:"Member •••3",plan:"Belajar Mandiri",shortPlan:"Mandiri",level:"N5",chapter:15,total:15,rating:5,consent:true,status:"Siap ditinjau",completed:false,text:"Materi dasar dan latihan membantu saya menyelesaikan level dengan ritme yang konsisten.",material:5,practice:5,experience:5,recommendation:"Feedback siap ditinjau. Kandidat testimoni boleh dibuat karena izin tersedia." },
  { id:"f4",member:"Member •••4",plan:"Belajar dengan Sensei",shortPlan:"Sensei",level:"N4",chapter:12,total:12,rating:3,consent:false,status:"Menunggu",completed:false,text:"Materi cukup membantu, tetapi beberapa instruksi latihan masih perlu diperjelas.",material:4,practice:3,experience:3,recommendation:"Tinjau kejelasan instruksi sebagai feedback internal. Jangan buat kandidat testimoni tanpa izin." },
];

export default function FeedbackPage() {
  const [items,setItems] = useState(fixtures);
  const [selectedId,setSelectedId] = useState("f1");
  const [plan,setPlan] = useState("Semua Plan");
  const [level,setLevel] = useState("Semua Level");
  const [chapter,setChapter] = useState("Chapter Terakhir");
  const [rating,setRating] = useState("Semua Rating");
  const [consent,setConsent] = useState("Semua Status Izin");
  const [dialog,setDialog] = useState<Dialog>(null);
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  const visible = useMemo(() => items.filter((item) => (plan === "Semua Plan" || item.plan === plan) && (level === "Semua Level" || item.level === level) && (chapter !== "Chapter Terakhir" || item.chapter === item.total) && (rating === "Semua Rating" || item.rating === Number(rating)) && (consent === "Semua Status Izin" || consent === "Izin testimoni" && item.consent || consent === "Tanpa izin" && !item.consent)),[items,plan,level,chapter,rating,consent]);
  const average = (items.reduce((sum,item) => sum + item.rating,0) / items.length).toLocaleString("id-ID",{minimumFractionDigits:1,maximumFractionDigits:1});
  function complete() { setItems((list) => list.map((item) => item.id === selected.id ? {...item,completed:true}:item));setDialog("complete"); }
  function candidate() { setDialog(selected.consent ? "candidate":"blocked"); }
  function reset() { setPlan("Semua Plan");setLevel("Semua Level");setChapter("Chapter Terakhir");setRating("Semua Rating");setConsent("Semua Status Izin"); }

  return <AdminShell current="communication"><main className="admin-page admin-a8-page">
    <header className="admin-header"><div><p className="admin-kicker">KONTEN &amp; KOMUNIKASI • FEEDBACK</p><h1>Moderasi Feedback Akhir Level</h1><p>Kelola rating, masukan, tindak lanjut, dan kandidat testimoni dari Chapter terakhir.</p></div><div className="admin-header-actions"><Link className="button button-primary" href="/admin/testimonials">Lihat Testimoni →</Link></div></header>
    <section className="admin-kpi-grid">{[[items.filter((item) => !item.completed).length,"Menunggu ditinjau"],[average,"Rating rata-rata"],[items.filter((item) => item.consent).length,"Izin testimoni"],[items.filter((item) => item.status === "Perlu tindak lanjut").length,"Perlu tindak lanjut"]].map(([value,label]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>Dinamis dari fixture aktif.</small></article>)}</section>
    <section className="a8-filter-panel"><strong>FILTER ANTREAN</strong><div><label className="admin-field"><span>Plan</span><select value={plan} onChange={(event) => setPlan(event.target.value)}><option>Semua Plan</option><option>Free Member</option><option>Belajar Mandiri</option><option>Belajar dengan Sensei</option></select></label><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}><option>Semua Level</option>{["N1","N2","N3","N4","N5"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="admin-field"><span>Chapter</span><select value={chapter} onChange={(event) => setChapter(event.target.value)}><option>Chapter Terakhir</option></select></label><label className="admin-field"><span>Rating</span><select value={rating} onChange={(event) => setRating(event.target.value)}><option>Semua Rating</option>{[5,4,3,2,1].map((item) => <option value={item} key={item}>{item} bintang</option>)}</select></label><label className="admin-field"><span>Status izin</span><select value={consent} onChange={(event) => setConsent(event.target.value)}><option>Semua Status Izin</option><option>Izin testimoni</option><option>Tanpa izin</option></select></label></div></section>
    <div className="a8-layout"><section className="a8-queue"><header><h2>Antrean feedback</h2><p>Data pengguna ditampilkan secara terbatas.</p></header>{visible.length ? visible.map((item) => <button className={selected.id === item.id ? "active":""} type="button" onClick={() => setSelectedId(item.id)} key={item.id}><span><strong>{item.member}</strong><small>{item.shortPlan} • {item.level} • Chapter {item.chapter}/{item.total}</small></span><span><b className="a8-stars" aria-label={`Rating ${item.rating} dari 5`}>{"★".repeat(item.rating)}{"☆".repeat(5-item.rating)}</b><small>{item.consent ? "Izin testimoni":"Tanpa izin"}</small></span><em>{item.completed ? "Selesai":item.status}</em></button>) : <section className="a8-empty"><strong>Belum ada feedback untuk filter ini.</strong><button className="button button-secondary" type="button" onClick={reset}>Reset Filter</button></section>}</section>
      <section className="a8-review"><header><div><p className="admin-kicker">DETAIL FEEDBACK TERPILIH</p><h2>{selected.member}</h2></div><span>{selected.completed ? "Selesai":selected.status}</span></header><p className="a8-context">{selected.plan} • {selected.level} • Chapter {selected.chapter} dari {selected.total}</p><div className="a8-badges"><b>Rating {selected.rating}/5</b><span>{selected.consent ? "Izin testimoni":"Tanpa izin"}</span><span>{selected.completed ? "Sudah ditindaklanjuti":selected.status === "Perlu tindak lanjut" ? "Perlu tindak lanjut":"Belum ditindaklanjuti"}</span></div><article className="a8-feedback-text"><p>“{selected.text}”</p></article><dl className="a8-ratings"><div><dt>Rating materi</dt><dd>{selected.material}</dd></div><div><dt>latihan</dt><dd>{selected.practice}</dd></div><div><dt>pengalaman</dt><dd>{selected.experience}</dd></div></dl><aside className="a8-recommendation"><strong>Rekomendasi sistem</strong><p>{selected.recommendation}</p></aside><div className="a8-actions"><button className="button button-primary" type="button" onClick={complete}>Tandai Selesai</button><button className="button button-dark" type="button" onClick={candidate}>Buat Kandidat Testimoni</button><Link className="button button-secondary" href="/admin/testimonials">Buka Moderasi Testimoni</Link></div><aside className="a8-privacy"><strong>PRIVACY RULE</strong><p>Hanya publikasikan kutipan atau media setelah izin pengguna dinyatakan valid.</p><small>Feedback tetap internal. Selesai bukan kandidat; kandidat bukan publikasi.</small></aside></section></div>
    {dialog && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setDialog(null)} aria-label="Tutup dialog moderasi feedback"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="feedback-dialog-title">
      {dialog === "complete" && <section className="a4-success"><p>Status feedback diperbarui dan tercatat pada audit log.</p><h2 id="feedback-dialog-title">Feedback ditandai selesai</h2><span aria-hidden="true">✓</span><p>Status feedback diperbarui dan tercatat pada audit log.</p><ul className="a8-steps"><li>Persetujuan valid</li><li>Konten disetujui</li><li>Audit tersimpan</li></ul><p className="admin-local-feedback" role="status">Fixture lokal saja; audit belum dipersistensikan dan testimoni tidak dibuat.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke Feedback</button></section>}
      {dialog === "candidate" && <section className="a4-success"><p>Kandidat masuk ke Moderasi Testimoni dan belum otomatis dipublikasikan.</p><h2 id="feedback-dialog-title">Kandidat testimoni berhasil dibuat</h2><span aria-hidden="true">✓</span><p>Kandidat masuk ke Moderasi Testimoni dan belum otomatis dipublikasikan.</p><ul className="a8-steps"><li>Persetujuan valid</li><li>Konten disetujui</li><li>Audit tersimpan</li></ul><p className="admin-local-feedback" role="status">Simulasi frontend saja. Kandidat belum Approved, Featured, atau Published.</p><Link className="button button-primary" href="/admin/testimonials">Buka Testimoni</Link></section>}
      {dialog === "blocked" && <><p className="admin-kicker">KONTEN &amp; KOMUNIKASI • FEEDBACK</p><h2 id="feedback-dialog-title">Kandidat tidak dapat dibuat</h2><p>Feedback berstatus Tanpa izin. Admin tidak dapat membuat persetujuan atau meneruskan feedback ini sebagai kandidat testimoni.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke Feedback</button></>}
    </section></div>}
  </main></AdminShell>;
}
