"use client";

import { useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Tab = "Role Permissions" | "Plan Entitlements" | "Feature Flags" | "Audit Log" | "Gamification";

export default function AccessSettingsPage() {
  const [tab, setTab] = useState<Tab>("Role Permissions");
  const [saved, setSaved] = useState(false);

  return <AdminShell current="users"><main className="admin-page admin-a4-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • PENGATURAN AKSES &amp; KEBIJAKAN</p><h1>Pengaturan Akses Pengguna</h1><p>Kelola hak akses pengguna, paket membership, perizinan fitur, dan aturan belajar siswa.</p></div><div className="admin-header-actions"><button className="button button-primary" type="button" onClick={() => setSaved(true)}>Simpan Pengaturan</button></div></header>
    <aside className="a4-authority-banner"><strong>Pengumuman</strong><p>Setiap perubahan hak akses langsung disinkronkan ke akun siswa untuk memastikan keamanan data.</p></aside>
    <section className="admin-kpi-grid">{[["Role Pengguna","2 Role","Student dan Admin."],["Paket Belajar","3 Paket","Free Member, Belajar Mandiri, Belajar dengan Sensei."],["Aturan Fitur","12 Aturan","Hak akses per fitur aplikasi."],["Perubahan Terakhir","Hari Ini","Riwayat pembaruan hak akses."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <div className="a4-tabs" role="tablist">{(["Role Permissions","Plan Entitlements","Feature Flags","Audit Log","Gamification"] as Tab[]).map((item) => <button className={tab === item ? "active" : ""} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>
    <section className="a4-policy-panel" role="tabpanel">{tab === "Role Permissions" && <><header><h2>Perizinan Role Pengguna</h2><p>Pengaturan izin berdasarkan hak akses pengguna di aplikasi.</p></header><div className="a4-role-list"><article><span aria-hidden="true">学</span><div><strong>Student</strong><p>Mengakses materi pembelajaran dan fitur sesuai paket yang aktif.</p></div><b>Umum</b></article><article><span aria-hidden="true">管</span><div><strong>Admin</strong><p>Mengelola konten materi, verifikasi pembayaran, dan konfigurasi sistem.</p></div><b>Pengelola</b></article></div><div className="admin-table-container"><table className="admin-table permission-table"><thead><tr><th>Fitur &amp; Akses</th><th>Student</th><th>Admin</th><th>Pemeriksaan Izin</th></tr></thead><tbody>{[["Melihat materi belajar","✓","✓","Sesuai Paket"],["Mengelola konten materi","—","✓","Izin Admin"],["Verifikasi invoice pembayaran","—","✓","Izin Admin"],["Mengubah akses paket siswa","—","✓","Izin Khusus"],["Melihat laporan analitik","Terbatas","✓","Privasi Akun"],["Mengekspor laporan data","—","Diizinkan","Izin Khusus"]].map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div></>}
      {tab === "Plan Entitlements" && <><header><h2>Paket Belajar (Plan Entitlements)</h2><p>Rincian fasilitas dan hak akses pembelajaran untuk masing-masing paket siswa.</p></header><div className="a4-plan-list">{[["Free Member","Akses Chapter 1 gratis setiap level • Komunitas mode baca"],["Belajar Mandiri","Seluruh Chapter penuh • Bank Try Out • Komunitas interaktif"],["Belajar dengan Sensei","Semua fasilitas Belajar Mandiri • Kelas Live Zoom • Bimbingan Sensei • Replay sesi"]].map(([plan,detail]) => <article key={plan}><strong>{plan}</strong><p>{detail}</p></article>)}</div></>}
      {tab === "Feature Flags" && <><header><h2>Status Ketersediaan Fitur</h2><p>Pengaturan status aktif atau nonaktif fitur pembelajaran di aplikasi.</p></header><div className="a4-feature-list">{[["配","Placement Test","Dapat diakses publik tanpa login akun.","Aktif"],["証","Digital Certificate","Diterbitkan otomatis setelah siswa menyelesaikan ujian level.","Aktif"],["初","Bantuan Bahasa Jepang (Furigana)","Tersedia pada modul pembelajaran untuk pemula.","Aktif"],["再","Replay Rekaman Kelas","Tampil setelah rekaman diverifikasi pengajar.","Aktif"],["問","Tanya Sensei","Fasilitas konsultasi khusus member Belajar dengan Sensei.","Khusus Sensei"]].map(([glyph,title,detail,state]) => <article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{detail}</p></div><button type="button">{state}</button></article>)}</div></>}
      {tab === "Audit Log" && <section className="a4-requirement-state"><p className="admin-kicker">CATATAN PERIZINAN</p><h2>Pencatatan Riwayat Akses Siswa</h2><p>Setiap perubahan hak akses, upgrade paket, dan perpanjangan membership dicatat secara otomatis untuk keamanan akun.</p></section>}
      {tab === "Gamification" && <><section className="a4-requirement-state"><p className="admin-kicker">KEBIJAKAN PRESTASI &amp; GAMIFIKASI</p><h2>Poin XP, streak harian, leaderboard, dan lencana pencapaian</h2><strong>Aktif</strong></section><div className="a4-feature-list">{[["点","Poin XP","Diperoleh dari penyelesaian modul dan latihan soal.","Aktif"],["火","Streak Harian","Dihitung dari keaktifan belajar setiap hari tanpa jeda.","Aktif"],["位","Privasi Papan Peringkat","Nama siswa dapat disamarkan di leaderboard kompetisi.","Aktif"],["章","Lencana Prestasi","Penghargaan pencapaian target belajar siswa.","Aktif"]].map(([glyph,title,detail,state]) => <article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{detail}</p></div><b>{state}</b></article>)}</div></>}
    </section>
    {saved && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setSaved(false)} aria-label="Tutup success state"/><section className="a4-dialog" role="dialog" aria-modal="true" aria-labelledby="settings-saved-title"><section className="a4-success"><p className="admin-kicker">ADMIN • SIMPAN AKSES</p><h2 id="settings-saved-title">Pengaturan akses berhasil disimpan</h2><span aria-hidden="true">✓</span><p>Perubahan hak akses dan perizinan fitur telah berhasil diperbarui ke sistem.</p><button className="button button-primary" type="button" onClick={() => setSaved(false)}>Kembali ke Pengaturan Akses</button></section></section></div>}
  </main></AdminShell>;
}



