"use client";

import Link from "next/link";
import { useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Tab = "Role Permissions" | "Plan Entitlements" | "Feature Flags" | "Audit Log" | "Gamification";

export default function AccessSettingsPage() {
  const [tab, setTab] = useState<Tab>("Role Permissions");
  const [saved, setSaved] = useState(false);

  return <AdminShell current="users"><main className="admin-page admin-a4-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • ACCESS &amp; GOVERNANCE</p><h1>Access Settings</h1><p>Kelola role teknis, plan entitlement, permission, feature access, backend authority, dan audit.</p></div><div className="admin-header-actions"><button className="button button-primary" type="button" onClick={() => setSaved(true)}>Simpan Settings</button><Link className="button button-secondary" href="/admin">Dashboard</Link></div></header>
    <aside className="a4-authority-banner"><strong>Pengumuman</strong><p>Authorization sensitif wajib diperiksa backend. UI hanya mencerminkan entitlement dan permission.</p></aside>
    <section className="admin-kpi-grid">{[["Technical roles","2","Student dan Admin."],["Student plans","3","Free Member, Belajar Mandiri, Belajar dengan Sensei."],["Feature rules","Dinamis","Dikelola sebagai policy."],["Recent changes","Dinamis","Perubahan yang tercatat."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <div className="a4-tabs" role="tablist">{(["Role Permissions","Plan Entitlements","Feature Flags","Audit Log","Gamification"] as Tab[]).map((item) => <button className={tab === item ? "active" : ""} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>
    <section className="a4-policy-panel" role="tabpanel">{tab === "Role Permissions" && <><header><h2>Role permissions</h2><p>Role teknis berbeda dari plan siswa.</p></header><div className="a4-role-list"><article><span aria-hidden="true">学</span><div><strong>Student</strong><p>Mengakses fitur sesuai entitlement plan.</p></div><b>Default</b></article><article><span aria-hidden="true">管</span><div><strong>Admin</strong><p>Mengelola konfigurasi dan operasi sensitif.</p></div><b>Restricted</b></article></div><div className="admin-table-container"><table className="admin-table permission-table"><thead><tr><th>Permission</th><th>Student</th><th>Admin</th><th>Backend Check</th></tr></thead><tbody>{[["View learning content","✓","✓","Entitlement"],["Manage content","—","✓","Permission"],["Verify invoice","—","✓","Permission + Audit"],["Change user access","—","✓","Permission + Reason"],["View analytics","Limited","✓","Role + Privacy"],["Export sensitive data","—","Restricted","Permission + Audit"]].map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div></>}
      {tab === "Plan Entitlements" && <><header><h2>Plan entitlements</h2><p>Policy presentation; tidak mengubah fixture Student.</p></header><div className="a4-plan-list">{[["Free Member","1 chapter • community read"],["Belajar Mandiri","Full journey • Try Out • write"],["Belajar dengan Sensei","Belajar dengan Sensei • cohort • Zoom • replay"]].map(([plan,detail]) => <article key={plan}><strong>{plan}</strong><p>{detail}</p></article>)}</div></>}
      {tab === "Feature Flags" && <><header><h2>Feature flags</h2><p>State presentasi lokal; bukan feature flag engine.</p></header><div className="a4-feature-list">{[["配","Placement Test","Public without account; lead required.","On"],["証","Digital Certificate","Issued after eligibility.","On"],["初","Jepang Pemula","Not a separate screen.","Editor State"],["再","Replay","Only after admin publish.","Conditional"],["問","Tanya Sensei","Belajar dengan Sensei entitlement.","Plan gated"]].map(([glyph,title,detail,state]) => <article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{detail}</p></div><button type="button">{state}</button></article>)}</div></>}
      {tab === "Audit Log" && <section className="a4-requirement-state"><p className="admin-kicker">AUDIT REQUIREMENTS</p><h2>Catat actor, waktu, perubahan, alasan, target, dan hasil pemeriksaan backend.</h2><p>Riwayat produksi tidak difabrikasi. Audit Logs menjadi modul Admin terpisah pada batch berikutnya.</p></section>}
      {tab === "Gamification" && <><section className="a4-requirement-state"><p className="admin-kicker">GAMIFICATION POLICY</p><h2>XP, streak, leaderboard, dan achievement</h2><strong>Merged</strong></section><div className="a4-feature-list">{[["点","XP source","Event belajar tervalidasi backend.","Dynamic"],["火","Streak policy","Grace period dan reset rule.","Config"],["位","Leaderboard privacy","Alias, cohort, dan periode.","Masked"],["章","Achievement rules","Milestone tidak menggantikan certificate.","Config"]].map(([glyph,title,detail,state]) => <article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{detail}</p></div><b>{state}</b></article>)}</div></>}
    </section>
    {saved && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setSaved(false)} aria-label="Tutup success state"/><section className="a4-dialog" role="dialog" aria-modal="true" aria-labelledby="settings-saved-title"><section className="a4-success"><p className="admin-kicker">ADMIN • SIMPAN AKSES</p><h2 id="settings-saved-title">Pengaturan akses berhasil disimpan</h2><span aria-hidden="true">✓</span><p>State frontend deterministik. Permission tidak disinkronkan, policy tidak dipersistensikan, dan audit belum ditulis.</p><button className="button button-primary" type="button" onClick={() => setSaved(false)}>Kembali ke Access Settings</button></section></section></div>}
  </main></AdminShell>;
}
