"use client";

import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type User = { id: string; name: string; email: string; membership: string; status: string; source: string; level: string };
type Dialog = "access" | "add" | "access-success" | "add-success" | null;

const fixtureUsers: User[] = [
  { id: "u1", name: "Member •••1", email: "m•••1@example.com", membership: "Belajar Mandiri", status: "Aktif", source: "Referral / Organik", level: "N4" },
  { id: "u2", name: "Member •••2", email: "m•••2@example.com", membership: "Free Member", status: "Aktif", source: "Referral / Organik", level: "N5" },
  { id: "u3", name: "Member •••3", email: "m•••3@example.com", membership: "Belajar dengan Sensei", status: "Pending", source: "Referral / Organik", level: "N4" },
  { id: "u4", name: "Member •••4", email: "m•••4@example.com", membership: "Belajar Mandiri", status: "Expired", source: "Referral / Organik", level: "N3" },
];

export default function UsersPage() {
  const [users, setUsers] = useState(fixtureUsers);
  const [selectedId, setSelectedId] = useState("u1");
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("Semua");
  const [dialog, setDialog] = useState<Dialog>(null);
  const [reason, setReason] = useState("");
  const [validation, setValidation] = useState("");
  const [membership, setMembership] = useState("Belajar Mandiri");
  const [level, setLevel] = useState("N4");
  const [role, setRole] = useState("Student");
  const selected = users.find((user) => user.id === selectedId) ?? users[0];
  const visible = useMemo(() => users.filter((user) => (filter === "Semua" || filter === "Pending" ? filter === "Semua" || user.status === "Pending" : user.membership === filter) && `${user.name} ${user.email} ${user.source}`.toLowerCase().includes(query.toLowerCase())), [users,filter,query]);

  function openAccess() { setMembership(selected.membership); setLevel(selected.level); setReason(""); setValidation(""); setDialog("access"); }
  function applyAccess() { if (!reason.trim()) { setValidation("Ringkasan wajib diisi sebelum perubahan akses diterapkan."); return; } setUsers((items) => items.map((user) => user.id === selected.id ? { ...user, membership, level } : user)); setDialog("access-success"); }
  function saveUser() { if (role === "Student" && !membership) { setValidation("Plan Student wajib dipilih."); return; } setValidation(""); setDialog("add-success"); }

  return <AdminShell current="users"><main className="admin-page admin-a4-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • USERS &amp; ENTITLEMENT</p><h1>User Management</h1><p>Kelola akun, membership, entitlement, progres, referral source, dan status akses.</p></div><div className="admin-header-actions"><button className="button button-primary" type="button" onClick={() => { setRole("Student"); setMembership("Free Member"); setLevel("N5"); setValidation(""); setDialog("add"); }}>Tambah Pengguna</button></div></header>
    <section className="admin-kpi-grid">{[["Total pengguna","1.284","Total akun terdaftar."],["Membership aktif","856","Pengguna paket aktif."],["Pending verification","12","Menunggu verifikasi pembayaran."],["Expired access","48","Perlu renewal atau follow-up."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a4-user-filters"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama, email, WhatsApp, atau referral" /></label><div className="admin-filters">{["Semua","Free Member","Belajar Mandiri","Belajar dengan Sensei","Pending"].map((item) => <button className={filter === item ? "active" : ""} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></section>
    <div className="a4-user-layout"><section className="admin-table-container a4-user-table">{visible.length ? <table className="admin-table"><thead><tr><th>Pengguna</th><th>Membership</th><th>Status</th><th>Sumber</th><th>Aksi</th></tr></thead><tbody>{visible.map((user) => <tr className={selected.id === user.id ? "selected" : ""} key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td><strong>{user.membership}</strong><small>Paket aktif siswa</small></td><td><span className={`admin-status status-${user.status === "Aktif" ? "active" : "pending"}`}>{user.status}</span></td><td><strong>{user.source}</strong><small>Kanal pendaftaran</small></td><td><button type="button" onClick={() => setSelectedId(user.id)}>Lihat Detail</button></td></tr>)}</tbody></table> : <section className="a4-empty-table"><p className="admin-kicker">ADMIN • KOSONG</p><h2>Belum ada data untuk filter ini</h2><p>Ubah kata kunci pencarian atau ganti filter kategori.</p><button className="button button-secondary" type="button" onClick={() => { setQuery(""); setFilter("Semua"); }}>Reset Filter</button></section>}</section>
      <aside className="a4-user-detail"><header><div><h2>{selected.name}</h2><p>Informasi akun dan akses belajar.</p></div><span>{selected.membership}</span></header><dl>{[["Level akses",`${selected.level} • Sesuai paket`],["Progres","65% modul selesai"],["Referral source","Kode Referral Siswa"],["Invoice terakhir","Lunas • INV-1008"]].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><aside><strong>CATATAN AKSES</strong><p>Setiap perubahan akses tercatat pada riwayat aktivitas admin.</p></aside><div style={{ display: "flex", justifyContent: "center", marginTop: "20px" }}><button className="button button-primary" type="button" onClick={openAccess} style={{ minWidth: "180px", justifyContent: "center" }}>Edit Akses</button></div></aside></div>

    {dialog && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setDialog(null)} aria-label="Tutup editor"/><section className="a4-dialog" role="dialog" aria-modal="true" aria-labelledby="a4-dialog-title">{dialog === "access" && <><p className="admin-kicker">USER ACCESS EDITOR</p><h2 id="a4-dialog-title">Ubah membership dan akses level</h2><aside><strong>Pengumuman</strong><p>Perubahan status paket akan langsung memengaruhi akses belajar siswa.</p></aside><p className="a4-dialog-context">{selected.name} • {selected.email}</p><label className="admin-field"><span>Membership</span><select value={membership} onChange={(event) => setMembership(event.target.value)}><option>Free Member</option><option>Belajar Mandiri</option><option>Belajar dengan Sensei</option></select></label><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}>{["N1","N2","N3","N4","N5"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="admin-field"><span>Periode Akses</span><input value="31 Desember 2026" readOnly /></label><label className="admin-field"><span>Ringkasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{validation && <p className="a4-validation" role="alert">{validation}</p>}<div><button className="button button-primary" type="button" onClick={applyAccess}>Terapkan Perubahan</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Batal</button></div></>}
      {dialog === "add" && <><p className="admin-kicker">PENGGUNA</p><h2 id="a4-dialog-title">Tambahkan pengguna baru</h2><p>Isi identitas, role, level, plan, masa akses, dan status verifikasi siswa.</p><label className="admin-field"><span>Email / Kontak</span><input defaultValue="siswa.baru@example.com" /></label><label className="admin-field"><span>Role Pengguna</span><select value={role} onChange={(event) => setRole(event.target.value)}><option>Student</option><option>Admin</option></select></label>{role === "Student" && <><label className="admin-field"><span>Plan</span><select value={membership} onChange={(event) => setMembership(event.target.value)}><option>Free Member</option><option>Belajar Mandiri</option><option>Belajar dengan Sensei</option></select></label><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}>{["N1","N2","N3","N4","N5"].map((item) => <option key={item}>{item}</option>)}</select></label></>}<label className="admin-field"><span>Periode Akses</span><input value="6 Bulan Aktif" readOnly /></label><label className="admin-field"><span>Status Verifikasi</span><select><option>Aktif</option><option>Pending</option></select></label>{validation && <p className="a4-validation" role="alert">{validation}</p>}<div><button className="button button-primary" type="button" onClick={saveUser}>Simpan Pengguna</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Batal</button></div></>}
      {dialog === "access-success" && <section className="a4-success"><p className="admin-kicker">ADMIN • TERAPKAN AKSES</p><h2 id="a4-dialog-title">Perubahan akses berhasil diterapkan</h2><span aria-hidden="true">✓</span><p>Status membership dan level belajar siswa berhasil diperbarui.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke User Management</button></section>}
      {dialog === "add-success" && <section className="a4-success"><p className="admin-kicker">PENGGUNA</p><h2 id="a4-dialog-title">Pengguna baru berhasil disimpan</h2><span aria-hidden="true">✓</span><p>Data pengguna baru berhasil ditambahkan ke sistem.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke User Management</button></section>}</section></div>}
  </main></AdminShell>;
}
