"use client";

import Link from "next/link";
import { useState } from "react";
import type { JourneyChapter, JourneyLevel } from "@/lib/journey-mock";
import type { Membership } from "@/lib/dashboard-mock";

export function ChapterJourney({ membership, level, chapters }: { membership: Membership; level: JourneyLevel; chapters: JourneyChapter[] }) {
  const [completionView, setCompletionView] = useState<"journey" | "complete" | "feedback" | "submitted">("journey");
  const [rating, setRating] = useState(4);
  const [feedback, setFeedback] = useState("");
  const [consent, setConsent] = useState(false);
  if (membership !== "sensei") return <section className="chapter-list" aria-label={`Chapter ${level.title}`}>{chapters.map((chapter) => <article className={`chapter-card chapter-${chapter.state}`} key={chapter.key}><div className="chapter-marker"><span>{chapter.state === "completed" ? "✓" : chapter.state === "current" ? "日" : "⌑"}</span><i /></div><div className="chapter-copy"><div className="chapter-meta"><span>{chapter.statusLabel}</span><small>{chapter.orderLabel}</small></div><h2>{chapter.title}</h2><p>{chapter.description}</p></div><div className="chapter-action">{chapter.href ? <Link className="chapter-action-button" href={chapter.href}>{chapter.statusLabel}<b aria-hidden="true">→</b></Link> : <span>{chapter.statusLabel}</span>}</div></article>)}</section>;

  if (completionView === "complete") return <section className="level-complete-state"><p className="dash-kicker">LEVEL SELESAI • FEEDBACK</p><h1>Selamat, seluruh Chapter pada level ini selesai</h1><span className="level-complete-status">Belum Aktif</span><strong className="level-complete-icon">鍵</strong><p>Feedback akhir level tersedia. Jadwal, replay, dan Tanya Sensei tetap tersimpan pada cohort aktif.</p><div className="level-complete-meta"><b>LEVEL SELESAI • FEEDBACK</b><span>Nilai tersimpan</span><span>Backend authority</span></div><div className="level-complete-actions"><button type="button" onClick={() => setCompletionView("feedback")}>Kembali ke Hasil</button><Link href="/progress?membership=sensei">Kembali ke Daftar</Link></div></section>;
  if (completionView === "feedback") return <section className="level-feedback"><header><div><p className="dash-kicker">FEEDBACK AKHIR LEVEL • BELAJAR DENGAN SENSEI</p><h1>Bagikan pengalaman setelah seluruh Chapter selesai</h1><p>Form ini hanya muncul setelah Chapter terakhir pada level aktif selesai.</p></div><span>LEVEL SELESAI</span></header><section className="level-feedback-summary"><strong>N4 • BELAJAR DENGAN SENSEI</strong><span>12 dari 12 Chapter selesai</span><small>Progress dan status selesai berasal dari backend.</small></section><form onSubmit={(event) => { event.preventDefault(); setCompletionView("submitted"); }}><fieldset className="feedback-rating"><legend>Penilaian keseluruhan</legend><p>Pilih rating untuk materi, latihan, dan pengalaman belajar.</p><div>{[1,2,3,4,5].map((value) => <button type="button" aria-label={`${value} bintang`} aria-pressed={rating === value} onClick={() => setRating(value)} key={value}>★</button>)}</div></fieldset><section className="feedback-categories">{[["Materi","Video, modul, dan contoh."],["Latihan","Latihan, checkpoint, dan Try Out."],["Pengalaman","Alur, progress, dan kemudahan."]].map(([title,description]) => <article key={title}><strong>{title}</strong><p>{description}</p><span aria-label="4 dari 5 bintang">★★★★☆</span></article>)}</section><label className="feedback-text">Ceritakan pengalamanmu<small>Apa yang paling membantu dan apa yang perlu diperbaiki?</small><textarea value={feedback} onChange={(event) => setFeedback(event.target.value)} placeholder="Tulis masukan untuk tim akademik dan pengembangan produk…" rows={6} required /></label><label className="feedback-consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span>Saya bersedia masukan ini dipertimbangkan sebagai testimoni publik Hiru Academy.<small>Opsional. Feedback tidak otomatis dipublikasikan dan tetap menunggu moderasi Admin.</small></span></label><div className="level-feedback-actions"><button type="submit">Kirim Feedback</button><Link href="/progress?membership=sensei">Lewati untuk Sekarang</Link></div></form><footer><p>Feedback dan testimoni disimpan sebagai dua status berbeda.</p><p>Tanpa izin, feedback hanya digunakan untuk evaluasi internal.</p></footer></section>;
  if (completionView === "submitted") return <section className="level-complete-state"><p className="dash-kicker">FEEDBACK • TERSIMPAN</p><h1>Feedback akhir level berhasil dikirim</h1><span className="level-complete-status">Belum Aktif</span><strong className="level-complete-icon">鍵</strong><p>Masukan tersimpan. Izin testimoni, bila dipilih, tetap menunggu moderasi Admin.</p><div className="level-complete-meta"><b>FEEDBACK • TERSIMPAN</b><span>Nilai tersimpan</span><span>Backend authority</span></div><div className="level-complete-actions"><Link href="/progress?membership=sensei">Kembali ke Hasil</Link><Link href="/dashboard?membership=sensei">Kembali ke Daftar</Link></div></section>;

  return (
    <>
      <header className="chapter-journey-head"><p className="dash-kicker">LEVEL AKTIF TERPILIH • CHAPTER JOURNEY</p><h1>Lanjutkan Chapter pada level dan cohort yang dipilih</h1><p>Nama level, Chapter, jadwal, dan progress dimuat berdasarkan level aktif yang dipilih.</p></header>
      <section className="chapter-progress-card"><div><p className="dash-kicker">PROGRES LEVEL TERPILIH</p><h2>Chapter 4 dari 12</h2><p>Progress, kelas Sensei, dan replay level lain tetap disimpan secara terpisah.</p></div><div className="journey-progress"><span>Progress dari backend</span><div><i /></div></div></section>
      <div className="chapter-journey-layout"><section className="chapter-list sensei-chapter-list" aria-label={`Chapter ${level.title}`}>{chapters.map((chapter) => <article className={`chapter-card chapter-${chapter.state}`} key={chapter.key}><span className="chapter-number">{chapter.orderLabel}</span><div className="chapter-copy"><h2>{chapter.title}</h2><p>{chapter.description}</p></div><div className="chapter-action">{chapter.href ? <Link className="chapter-action-button" href={chapter.href}>{chapter.statusLabel}<b aria-hidden="true">→</b></Link> : chapter.state === "finalPreview" ? <button className="chapter-action-button" type="button" onClick={() => setCompletionView("complete")}>{chapter.statusLabel}<b aria-hidden="true">→</b></button> : <span className={`chapter-status chapter-status-${chapter.state}`}>{chapter.state === "progressionLocked" && <i aria-hidden="true">⌑</i>}{chapter.statusLabel}</span>}</div></article>)}</section><aside className="chapter-milestone"><h2>Milestone berikutnya</h2><p>Selesaikan Chapter 4 untuk membuka materi berikutnya dan menjaga streak.</p><article><span aria-hidden="true">♨</span><div><small>XP Mingguan</small><strong>— XP</strong></div></article><Link href="/journey?membership=sensei">Kembali ke Level</Link></aside></div>
    </>
  );
}
