"use client";

import Link from "next/link";
import { useState } from "react";
import type { LearningData } from "@/lib/learning-mock";

export function ChapterCheckpoint({ data }: { data: LearningData }) {
  const [completed, setCompleted] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<string>();
  const basePath = `/learn/${data.levelSlug}/${data.chapterSlug}`;
  const query = `?membership=${data.membership}`;
  if (completed) return <section className="checkpoint-result"><p className="dash-kicker">CHECKPOINT • RESULT</p><h1>Checkpoint Chapter 4 selesai</h1><span className="checkpoint-completed">Completed</span><div className="checkpoint-result-stats"><div><span>Skor</span><strong>—</strong></div><div><span>Jawaban benar</span><strong>—</strong></div><div><span>Durasi</span><strong>—</strong></div></div><section><p className="dash-kicker">Pemahaman materi</p><div className="checkpoint-breakdown"><div><span>Tata Bahasa</span><strong>Dinamis</strong></div><div><span>Huruf &amp; Kanji</span><strong>Dinamis</strong></div><div><span>Audio &amp; Reading</span><strong>Dinamis</strong></div></div></section><section className="checkpoint-recommendation"><p className="dash-kicker">REKOMENDASI</p><p>Review area dengan confidence rendah sebelum melanjutkan chapter berikutnya. Nilai dan rekomendasi berasal dari backend.</p></section><div className="learning-question-actions"><Link className="button button-dark" href={`/journey/${data.levelSlug}${query}`}>Kembali ke Journey</Link><span className="button button-secondary disabled" aria-disabled="true">Ulangi Latihan</span></div></section>;
  return <div className="learning-question-page checkpoint-page"><header className="learning-question-head"><p className="dash-kicker">{data.level} • CHAPTER {data.chapterNumber} • CHECKPOINT</p><h1>Uji pemahaman sebelum melanjutkan journey</h1><p>Checkpoint menggabungkan materi video, dua modul, flashcard, audio, dan reading.</p></header><div className="learning-question-layout"><main><section className="checkpoint-timer"><span>Waktu tersisa</span><strong>08:24</strong></section><section className="learning-question-card"><p className="dash-kicker">SOAL 1 DARI 10</p><h2>Pilih arti yang tepat untuk kata berikut:</h2><p className="checkpoint-word"><ruby>毎朝<rt>まいあさ</rt></ruby></p><fieldset><legend className="sr-only">Pilihan jawaban</legend>{["Setiap pagi", "Setiap malam", "Minggu depan", "Kemarin"].map((answer, index) => <label className={selectedAnswer === answer ? "selected" : ""} key={answer}><input type="radio" name="checkpoint-answer" checked={selectedAnswer === answer} onChange={() => setSelectedAnswer(answer)} /><span>{String.fromCharCode(65 + index)}. {answer}</span></label>)}</fieldset></section><div className="learning-question-actions"><Link className="button button-secondary" href={`${basePath}/reading${query}`}>← Kembali Reading</Link><button className="button button-dark" type="button" onClick={() => setCompleted(true)}>Selesaikan Checkpoint</button></div></main><aside className="learning-question-sidebar"><section><p className="dash-kicker">Checkpoint Progress</p><strong>1 dari 10 soal</strong></section><nav aria-label="Navigasi soal"><span>Navigasi soal</span><div>{Array.from({ length: 10 }, (_, index) => <button type="button" className={index === 0 ? "active" : ""} disabled={index !== 0} key={index}>{index + 1}</button>)}</div></nav></aside></div></div>;
}
