"use client";

import Link from "next/link";
import { useState } from "react";
import { miniCheckpoints } from "@/lib/sensei-mock";

const defaultItem = miniCheckpoints.find((group) => group.level === "N4")!.items.find((item) => item.session === "sesi 2" && item.part === "part 1")!;

export function MiniCheckpointScreen() {
  const [view, setView] = useState<"list" | "info" | "runner" | "result" | "review">("list");
  const [selected, setSelected] = useState(defaultItem);
  const [answer, setAnswer] = useState("b");
  const [marked, setMarked] = useState(false);
  if (view === "runner") return <div className="mini-runner"><header><div><p className="dash-kicker">MINI CHECKPOINT 02 • KELAS SENSEI</p><h1>Soal 4 dari 10</h1><p>Jawaban tersimpan otomatis. Timer dikendalikan backend.</p></div><span>TIMER AKTIF</span></header><section className="mini-runner-stats"><div><strong>4 / 10</strong><span>Soal dijawab</span></div><div><strong>1 soal</strong><span>Ditandai</span></div><div><strong>Aktif</strong><span>Autosave</span></div></section><div className="mini-runner-layout"><main><section className="learning-question-card"><p className="dash-kicker">BAGIAN BUNPOU • SOAL 4</p><h2>Pilih jawaban yang paling tepat.</h2><p className="mini-question-japanese">日本へ行く前に、パスポートを＿＿＿＿。</p><small>Gambar soal dari Admin (opsional)</small><fieldset><legend className="sr-only">Pilihan jawaban</legend>{[["a","確認しておきます"],["b","確認しています"],["c","確認したことがあります"],["d","確認するでしょう"]].map(([id,label], index) => <label className={answer === id ? "selected" : ""} key={id}><input type="radio" name="mini-answer" checked={answer === id} onChange={() => setAnswer(id)} /><span>{String.fromCharCode(65 + index)}. {label}</span></label>)}</fieldset></section><div className="mini-question-actions"><button type="button" disabled>Sebelumnya</button><button className={marked ? "marked" : ""} type="button" onClick={() => setMarked((value) => !value)}>Tandai Soal</button><button type="button" disabled>Selanjutnya</button></div></main><aside><p className="dash-kicker">NAVIGATOR</p><strong>4 dijawab • {marked ? "1" : "0"} ditandai</strong><div>{Array.from({ length: 10 }, (_, index) => <button className={index === 3 ? "active" : ""} disabled={index !== 3} type="button" key={index}>{index + 1}</button>)}</div><button className="mini-submit" type="button" onClick={() => setView("result")}>Akhiri &amp; Kirim</button><button type="button" onClick={() => setView("list")}>Kembali ke Daftar</button></aside></div><footer>Jawaban terakhir tersimpan • 23:29 WIB<br />Saat timer mencapai 00:00, sistem mengirim jawaban otomatis dan menghitung skor.</footer></div>;
  if (view === "result") return <div className="mini-result"><header><p className="dash-kicker">MINI CHECKPOINT • N4 SESI 2 PART 1 • HASIL</p><h1>Hasil Mini Checkpoint berhasil diproses</h1><p>Skor, status kelulusan, review, dan rekomendasi berasal dari jawaban yang tersimpan.</p><span>SELESAI</span></header><section className="mini-score"><p className="dash-kicker">SKOR AKHIR</p><strong>8 / 10</strong><span>LULUS</span><p>LULUS • Passing score mengikuti Admin • Durasi tersimpan</p><div><button type="button" onClick={() => setView("review")}>Ulasan Jawaban</button><button type="button" onClick={() => setView("list")}>Kembali ke Daftar</button></div></section><section className="mini-breakdown"><header><p className="dash-kicker">RINGKASAN NILAI</p><h2>Performa per bagian</h2><p>Lulus jika skor ≥ passing score Admin. Tidak lulus jika skor &lt; passing score Admin.</p></header><div>{[["86%","Moji Goi"],["80%","Bunpou"],["78%","Dokkai"],["84%","Choukai"]].map(([value,label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></section><section className="mini-result-notes"><article><span>強</span><div><p className="dash-kicker">Kekuatan • AKTIF</p><strong>Kosakata dan listening menunjukkan hasil stabil.</strong><small>Pertahankan review flashcard</small></div></article><article><span>補</span><div><p className="dash-kicker">Perlu Diperkuat • REKOMENDASI</p><strong>Dokkai dan pola kalimat masih di bawah target.</strong><small>Direkomendasikan Reading Drill</small></div></article></section><section className="mini-consent"><strong>PROGRES KELAS &amp; REVIEW</strong><p>N4 sesi 2 part 1 • Ulasan jawaban aktif • Hasil tersimpan permanen</p><p>Admin mengatur timer, passing score, jumlah soal, media gambar, review, dan publikasi Mini Checkpoint.</p></section></div>;
  if (view === "review") return <div className="mini-review"><header><div><p className="dash-kicker">MINI CHECKPOINT • N4 SESI 2 PART 1 • ULASAN</p><h1>Tinjau jawaban dan pembahasan</h1><p>Review tersedia sesuai konfigurasi Mini Checkpoint. Soal dapat memuat gambar dari Admin.</p></div><span>REVIEW AKTIF</span></header><div className="mini-review-filters"><span>FILTER JAWABAN</span>{["SEMUA 10","SALAH 2","BENAR 8","DITANDAI 1","BUNPOU"].map((item) => <button type="button" key={item}>{item}</button>)}</div><div className="mini-review-layout"><aside><h2>DAFTAR SOAL</h2>{Array.from({ length: 10 }, (_, index) => <button className={index === 3 ? "active" : ""} type="button" key={index}>Soal {index + 1} <span>• {index === 3 ? "Salah" : "Benar"}</span></button>)}</aside><main><p className="dash-kicker">SOAL 4 • BUNPOU</p><h2>日本へ行く前に、パスポートを＿＿＿＿。</h2><div className="mini-review-answers"><div><span>Jawabanmu</span><strong>B. 確認しています</strong></div><div><span>Jawaban benar</span><strong>A. 確認しておきます</strong></div></div><section><p className="dash-kicker">PEMBAHASAN</p><p>Pola ～ておく digunakan untuk menyatakan persiapan yang dilakukan sebelumnya. Karena konteksnya “sebelum pergi ke Jepang”, jawaban A paling tepat.</p><p>Rekomendasi: buka Modul Tata Bahasa Chapter 4 dan ulangi Reading Drill.</p></section></main></div><div className="learning-question-actions"><button className="button button-secondary" type="button" onClick={() => setView("result")}>Kembali ke Hasil</button><Link className="button button-dark" href="/practice?membership=sensei">Latihan Rekomendasi</Link></div></div>;
  if (view === "info") return <><button className="sensei-back" onClick={() => setView("list")}>← Kembali ke Daftar</button><div className="mini-info-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()}</p><h1>{selected.level} {selected.session} {selected.part} siap dikerjakan</h1><p>Timer dimulai saat Mini Checkpoint dimulai.</p></header><span>TERSEDIA</span></div><section className="mini-intro"><p className="dash-kicker">MINI CHECKPOINT KELAS</p><h2>Soal singkat • timer aktif • passing score dari Admin</h2><p>Jawaban tersimpan otomatis. Saat timer habis, sistem melakukan auto-submit dan menghitung skor.</p><button type="button" onClick={() => setView("runner")}>Mulai Mini Checkpoint</button></section><section className="mini-rules"><header><p className="dash-kicker">ATURAN SESI</p><h2>Yang perlu diperhatikan</h2><p>Aturan akses mengikuti cohort, progres pertemuan, dan konfigurasi Mini Checkpoint di Admin.</p></header><div>{[["鍵","Akses","Belajar dengan Sensei • Cohort aktif","Plan, cohort, dan progres pertemuan diverifikasi backend"],["時","Timer","Durasi mengikuti konfigurasi Admin","Dapat dikerjakan kapan saja sampai diselesaikan"],["再","Frekuensi","Maksimal sekitar 2× per bulan sesuai jadwal cohort","Khusus N5, N4, N3, dan N2 • sesi & part"],["答","Ulasan Jawaban","Skor dan status lulus/tidak lulus tampil setelah submit","Review dan media gambar mengikuti konfigurasi Mini Checkpoint"]].map(([icon,title,detail,note]) => <article key={title}><span>{icon}</span><div><p className="dash-kicker">{title} • AKTIF</p><strong>{detail}</strong><small>{note}</small></div></article>)}</div></section><section className="mini-consent"><p>Dengan memulai, pengguna menyetujui autosave, pencatatan hasil, dan aturan akses berdasarkan progres pertemuan.</p><p>Koneksi terputus tidak menghapus jawaban yang tersimpan. Timer tetap mengikuti backend sampai submit atau waktu habis.</p></section></>;
  return <><div className="mini-list-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • KELAS SENSEI</p><h1>Mini Checkpoint per level, sesi, dan part</h1><p>Khusus member Belajar dengan Sensei. Mini Checkpoint tersedia untuk N5, N4, N3, dan N2.</p></header><span>COHORT DRIVEN</span></div><div className="mini-filters"><span>PROGRES KELAS</span>{["SEMUA COHORT","N4","TERSEDIA","SELESAI","REVIEW AKTIF"].map((filter) => <button className={filter === "N4" ? "active" : ""} type="button" key={filter}>{filter}</button>)}</div><section className="mini-list"><header><p className="dash-kicker">DAFTAR MINI CHECKPOINT</p><h2>Pilih level dan Mini Checkpoint</h2><p>Struktur mengikuti sesi dan part. Setiap Mini Checkpoint memakai timer, skor, passing score, dan riwayat hasil.</p></header>{miniCheckpoints.map((group) => <section className="mini-level-group" key={group.level}><div><h2>{group.level}</h2><span>{group.status}</span></div><div>{group.items.map((item) => <button type="button" onClick={() => { setSelected(item); setView("info"); }} key={item.id}>{item.level} {item.session} {item.part}</button>)}</div></section>)}</section><p className="mini-list-note">Mini Checkpoint berbeda dari Try Out: soal lebih sedikit, tetapi tetap memakai timer. Passing score, review, media gambar, dan status publish diatur Admin.</p></>;
}
