"use client";

import { useState } from "react";
import { miniCheckpoints } from "@/lib/sensei-mock";

const defaultItem = miniCheckpoints.find((group) => group.level === "N4")!.items.find((item) => item.session === "sesi 2" && item.part === "part 1")!;

export function MiniCheckpointScreen() {
  const [view, setView] = useState<"list" | "info">("list");
  const [selected, setSelected] = useState(defaultItem);
  if (view === "info") return <><button className="sensei-back" onClick={() => setView("list")}>← Kembali ke Daftar</button><div className="mini-info-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()}</p><h1>{selected.level} {selected.session} {selected.part} siap dikerjakan</h1><p>Timer dimulai saat Mini Checkpoint dimulai.</p></header><span>TERSEDIA</span></div><section className="mini-intro"><p className="dash-kicker">MINI CHECKPOINT KELAS</p><h2>Soal singkat • timer aktif • passing score dari Admin</h2><p>Jawaban tersimpan otomatis. Saat timer habis, sistem melakukan auto-submit dan menghitung skor.</p><button type="button" disabled>Mulai Mini Checkpoint</button></section><section className="mini-rules"><header><p className="dash-kicker">ATURAN SESI</p><h2>Yang perlu diperhatikan</h2><p>Aturan akses mengikuti cohort, progres pertemuan, dan konfigurasi Mini Checkpoint di Admin.</p></header><div>{[["鍵","Akses","Belajar dengan Sensei • Cohort aktif","Plan, cohort, dan progres pertemuan diverifikasi backend"],["時","Timer","Durasi mengikuti konfigurasi Admin","Dapat dikerjakan kapan saja sampai diselesaikan"],["再","Frekuensi","Maksimal sekitar 2× per bulan sesuai jadwal cohort","Khusus N5, N4, N3, dan N2 • sesi & part"],["答","Ulasan Jawaban","Skor dan status lulus/tidak lulus tampil setelah submit","Review dan media gambar mengikuti konfigurasi Mini Checkpoint"]].map(([icon,title,detail,note]) => <article key={title}><span>{icon}</span><div><p className="dash-kicker">{title} • AKTIF</p><strong>{detail}</strong><small>{note}</small></div></article>)}</div></section><section className="mini-consent"><p>Dengan memulai, pengguna menyetujui autosave, pencatatan hasil, dan aturan akses berdasarkan progres pertemuan.</p><p>Koneksi terputus tidak menghapus jawaban yang tersimpan. Timer tetap mengikuti backend sampai submit atau waktu habis.</p></section></>;
  return <><div className="mini-list-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • KELAS SENSEI</p><h1>Mini Checkpoint per level, sesi, dan part</h1><p>Khusus member Belajar dengan Sensei. Mini Checkpoint tersedia untuk N5, N4, N3, dan N2.</p></header><span>COHORT DRIVEN</span></div><div className="mini-filters"><span>PROGRES KELAS</span>{["SEMUA COHORT","N4","TERSEDIA","SELESAI","REVIEW AKTIF"].map((filter) => <button className={filter === "N4" ? "active" : ""} type="button" key={filter}>{filter}</button>)}</div><section className="mini-list"><header><p className="dash-kicker">DAFTAR MINI CHECKPOINT</p><h2>Pilih level dan Mini Checkpoint</h2><p>Struktur mengikuti sesi dan part. Setiap Mini Checkpoint memakai timer, skor, passing score, dan riwayat hasil.</p></header>{miniCheckpoints.map((group) => <section className="mini-level-group" key={group.level}><div><h2>{group.level}</h2><span>{group.status}</span></div><div>{group.items.map((item) => <button type="button" onClick={() => { setSelected(item); setView("info"); }} key={item.id}>{item.level} {item.session} {item.part}</button>)}</div></section>)}</section><p className="mini-list-note">Mini Checkpoint berbeda dari Try Out: soal lebih sedikit, tetapi tetap memakai timer. Passing score, review, media gambar, dan status publish diatur Admin.</p></>;
}
