"use client";

import Link from "next/link";
import { useState } from "react";
import { AssessmentUnavailable } from "@/components/assessment-unavailable";
import { miniCheckpoints } from "@/lib/sensei-mock";

const defaultItem = miniCheckpoints.find((group) => group.level === "N4")!.items.find((item) => item.session === "sesi 2" && item.part === "part 1")!;
type View = "list" | "info" | "runner" | "result" | "review" | "unavailable" | "review-unavailable";

export function MiniCheckpointScreen() {
  const [view, setView] = useState<View>("list");
  const [selected, setSelected] = useState(defaultItem);
  const [answer, setAnswer] = useState("b");
  const [marked, setMarked] = useState(false);
  const [filter, setFilter] = useState("N4");
  const [question, setQuestion] = useState(4);
  const [confirmSubmit, setConfirmSubmit] = useState(false);
  const [reviewFilter, setReviewFilter] = useState("SEMUA 10");
  const [reviewQuestion, setReviewQuestion] = useState(4);
  if (view === "unavailable") return <AssessmentUnavailable eyebrow="MINI CHECKPOINT • BELUM TERSEDIA" title="Mini Checkpoint belum dapat dikerjakan" description="Akses mengikuti cohort, progres pertemuan, dan konfigurasi Mini Checkpoint di Admin." facts={["Cohort aktif", "Progres kelas", "Publikasi Admin"]} primary={{ label: "Kembali ke Daftar", onClick: () => setView("list") }} secondary={{ label: "Kembali Dashboard", href: "/dashboard?membership=sensei" }} />;
  if (view === "review-unavailable") return <AssessmentUnavailable eyebrow="ULASAN • DINONAKTIFKAN" title="Ulasan jawaban belum tersedia" description="Admin dapat mengaktifkan atau menonaktifkan review per Mini Checkpoint. Nilai dan hasil tetap tersimpan." facts={["Aturan per Mini Checkpoint", "Nilai tersimpan", "Backend authority"]} primary={{ label: "Kembali ke Hasil", onClick: () => setView("result") }} secondary={{ label: "Kembali ke Daftar", onClick: () => setView("list") }} />;
  if (view === "runner") return <div className="mini-runner"><header><div><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()}</p><h1>Soal {question} dari 10</h1><p>Jawaban tersimpan otomatis. Timer dikendalikan backend.</p></div><span>TIMER AKTIF</span></header><section className="mini-runner-stats"><div><strong>4 / 10</strong><span>Soal dijawab</span></div><div><strong>1 soal</strong><span>Ditandai</span></div><div><strong>Aktif</strong><span>Autosave</span></div></section><div className="mini-runner-layout"><main><section className="learning-question-card"><p className="dash-kicker">BAGIAN BUNPOU • SOAL {question}</p><h2>Pilih jawaban yang paling tepat.</h2><p className="mini-question-japanese">日本へ行く前に、パスポートを＿＿＿＿。</p><small>Gambar soal dari Admin (opsional)</small><fieldset><legend className="sr-only">Pilihan jawaban</legend>{[["a","確認しておきます"],["b","確認しています"],["c","確認したことがあります"],["d","確認するでしょう"]].map(([id,label], index) => <label className={answer === id ? "selected" : ""} key={id}><input type="radio" name="mini-answer" checked={answer === id} onChange={() => setAnswer(id)} /><span>{String.fromCharCode(65 + index)}. {label}</span></label>)}</fieldset></section><div className="mini-question-actions"><button type="button" onClick={() => setQuestion((value) => Math.max(1, value - 1))} disabled={question === 1}>Sebelumnya</button><button className={marked ? "marked" : ""} type="button" onClick={() => setMarked((value) => !value)}>Tandai Soal</button><button type="button" onClick={() => setQuestion((value) => Math.min(10, value + 1))} disabled={question === 10}>Selanjutnya</button></div></main><aside><p className="dash-kicker">NAVIGATOR</p><strong>4 dijawab • {marked ? "1" : "0"} ditandai</strong><div>{Array.from({ length: 10 }, (_, index) => <button className={index + 1 === question ? "active" : ""} onClick={() => setQuestion(index + 1)} type="button" key={index}>{index + 1}</button>)}</div><button className="mini-submit" type="button" onClick={() => setConfirmSubmit(true)}>Akhiri &amp; Kirim</button><button type="button" onClick={() => setView("list")}>Kembali ke Daftar</button></aside></div>{confirmSubmit && <div className="assessment-modal" role="dialog" aria-modal="true" aria-labelledby="mini-submit-title"><section><h2 id="mini-submit-title">Selesaikan Mini Checkpoint?</h2><p>Jawaban fixture akan dikirim dan hasil ditampilkan.</p><div className="modal-actions"><button type="button" onClick={() => setConfirmSubmit(false)}>Kembali ke Soal</button><button type="button" onClick={() => { setConfirmSubmit(false); setView("result"); }}>Kirim Jawaban</button></div></section></div>}<footer>Jawaban terakhir tersimpan • 23:29 WIB<br />Saat timer mencapai 00:00, sistem mengirim jawaban otomatis dan menghitung skor.</footer></div>;
  if (view === "result") return <div className="mini-result"><header><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()} • HASIL</p><h1>Hasil Mini Checkpoint berhasil diproses</h1><p>Skor, status kelulusan, review, dan rekomendasi berasal dari jawaban yang tersimpan.</p><span>SELESAI</span></header><section className="mini-score"><p className="dash-kicker">SKOR AKHIR</p><strong>8 / 10</strong><span>LULUS</span><p>LULUS • Passing score mengikuti Admin • Durasi tersimpan</p><div><button type="button" onClick={() => setView("review")}>Ulasan Jawaban</button><button type="button" onClick={() => setView("list")}>Kembali ke Daftar</button></div></section><section className="mini-breakdown"><header><p className="dash-kicker">RINGKASAN NILAI</p><h2>Performa per bagian</h2><p>Lulus jika skor ≥ passing score Admin. Tidak lulus jika skor &lt; passing score Admin.</p></header><div>{[["86%","Moji Goi"],["80%","Bunpou"],["78%","Dokkai"],["84%","Choukai"]].map(([value,label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></section><section className="mini-result-notes"><article><span>強</span><div><p className="dash-kicker">Kekuatan • AKTIF</p><strong>Kosakata dan listening menunjukkan hasil stabil.</strong><small>Pertahankan review flashcard</small></div></article><article><span>補</span><div><p className="dash-kicker">Perlu Diperkuat • REKOMENDASI</p><strong>Dokkai dan pola kalimat masih di bawah target.</strong><small>Direkomendasikan Reading Drill</small></div></article></section><section className="mini-consent"><strong>PROGRES KELAS &amp; REVIEW</strong><p>N4 sesi 2 part 1 • Ulasan jawaban aktif • Hasil tersimpan permanen</p><p>Admin mengatur timer, passing score, jumlah soal, media gambar, review, dan publikasi Mini Checkpoint.</p></section></div>;
  if (view === "review") return <div className="mini-review"><header><div><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()} • ULASAN</p><h1>Tinjau jawaban dan pembahasan</h1><p>Review tersedia sesuai konfigurasi Mini Checkpoint. Soal dapat memuat gambar dari Admin.</p></div><span>REVIEW AKTIF</span></header><div className="mini-review-filters"><span>FILTER JAWABAN</span>{["SEMUA 10","SALAH 2","BENAR 8","DITANDAI 1","BUNPOU"].map((item) => <button className={reviewFilter === item ? "active" : ""} type="button" onClick={() => setReviewFilter(item)} key={item}>{item}</button>)}</div><div className="mini-review-layout"><aside><h2>DAFTAR SOAL</h2>{Array.from({ length: 10 }, (_, index) => <button className={reviewQuestion === index + 1 ? "active" : ""} type="button" onClick={() => setReviewQuestion(index + 1)} key={index}>Soal {index + 1} <span>• {index === 3 ? "Salah" : "Benar"}</span></button>)}</aside><main><p className="dash-kicker">SOAL {reviewQuestion} • BUNPOU</p>{reviewQuestion === 4 ? <><h2>日本へ行く前に、パスポートを＿＿＿＿。</h2><div className="mini-review-answers"><div><span>Jawabanmu</span><strong>B. 確認しています</strong></div><div><span>Jawaban benar</span><strong>A. 確認しておきます</strong></div></div><section><p className="dash-kicker">PEMBAHASAN</p><p>Pola ～ておく digunakan untuk menyatakan persiapan yang dilakukan sebelumnya. Karena konteksnya “sebelum pergi ke Jepang”, jawaban A paling tepat.</p><p>Rekomendasi: buka Modul Tata Bahasa Chapter 4 dan ulangi Reading Drill.</p></section></> : <section className="tryout-review-placeholder"><p>Konten ulasan fixture hanya tersedia untuk soal 4.</p></section>}</main></div><div className="learning-question-actions"><button className="button button-secondary" type="button" onClick={() => setView("result")}>Kembali ke Hasil</button><Link className="button button-dark" href="/practice?membership=sensei">Latihan Rekomendasi</Link></div></div>;
  if (view === "info") return <><button className="sensei-back" onClick={() => setView("list")}>← Kembali ke Daftar</button><div className="mini-info-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • {selected.level} {selected.session.toUpperCase()} {selected.part.toUpperCase()}</p><h1>{selected.level} {selected.session} {selected.part} siap dikerjakan</h1><p>Timer dimulai saat Mini Checkpoint dimulai.</p></header><span>TERSEDIA</span></div><section className="mini-intro"><p className="dash-kicker">MINI CHECKPOINT KELAS</p><h2>Soal singkat • timer aktif • passing score dari Admin</h2><p>Jawaban tersimpan otomatis. Saat timer habis, sistem melakukan auto-submit dan menghitung skor.</p><button type="button" onClick={() => setView("runner")}>Mulai Mini Checkpoint</button></section><section className="mini-rules"><header><p className="dash-kicker">ATURAN SESI</p><h2>Yang perlu diperhatikan</h2><p>Aturan akses mengikuti cohort, progres pertemuan, dan konfigurasi Mini Checkpoint di Admin.</p></header><div>{[["鍵","Akses","Belajar dengan Sensei • Cohort aktif","Plan, cohort, dan progres pertemuan diverifikasi backend"],["時","Timer","Durasi mengikuti konfigurasi Admin","Dapat dikerjakan kapan saja sampai diselesaikan"],["再","Frekuensi","Maksimal sekitar 2× per bulan sesuai jadwal cohort","Khusus N5, N4, N3, dan N2 • sesi & part"],["答","Ulasan Jawaban","Skor dan status lulus/tidak lulus tampil setelah submit","Review dan media gambar mengikuti konfigurasi Mini Checkpoint"]].map(([icon,title,detail,note]) => <article key={title}><span>{icon}</span><div><p className="dash-kicker">{title} • AKTIF</p><strong>{detail}</strong><small>{note}</small></div></article>)}</div></section><section className="mini-consent"><p>Dengan memulai, pengguna menyetujui autosave, pencatatan hasil, dan aturan akses berdasarkan progres pertemuan.</p><p>Koneksi terputus tidak menghapus jawaban yang tersimpan. Timer tetap mengikuti backend sampai submit atau waktu habis.</p></section></>;
  return <><div className="mini-list-head"><header className="sensei-page-head"><p className="dash-kicker">MINI CHECKPOINT • KELAS SENSEI</p><h1>Mini Checkpoint per level, sesi, dan part</h1><p>Khusus member Belajar dengan Sensei. Mini Checkpoint tersedia untuk N5, N4, N3, dan N2.</p></header><span>COHORT DRIVEN</span></div><div className="mini-filters"><span>PROGRES KELAS</span>{["SEMUA COHORT","N4","TERSEDIA","SELESAI","REVIEW AKTIF"].map((item) => <button className={filter === item ? "active" : ""} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="mini-list"><header><p className="dash-kicker">DAFTAR MINI CHECKPOINT</p><h2>Pilih level dan Mini Checkpoint</h2><p>Struktur mengikuti sesi dan part. Setiap Mini Checkpoint memakai timer, skor, passing score, dan riwayat hasil.</p></header>{miniCheckpoints.filter((group) => filter === "SEMUA COHORT" || filter === "N4" ? filter === "SEMUA COHORT" || group.level === "N4" : true).map((group) => <section className="mini-level-group" key={group.level}><div><h2>{group.level}</h2><span>{group.status}</span></div><div>{group.items.filter((item, index) => filter === "TERSEDIA" ? !(group.level === "N4" && (index === 1 || index === 3)) && item.id !== defaultItem.id : filter === "SELESAI" ? item.id === defaultItem.id || group.level === "N4" && index === 3 : filter === "REVIEW AKTIF" ? item.id === defaultItem.id : true).map((item) => { const index = group.items.findIndex((candidate) => candidate.id === item.id); const unavailable = group.level === "N4" && index === 1; const reviewUnavailable = group.level === "N4" && index === 3; const completed = item.id === defaultItem.id || reviewUnavailable; return <button className={unavailable ? "unavailable" : completed ? "completed" : ""} type="button" onClick={() => { setSelected(item); setView(unavailable ? "unavailable" : reviewUnavailable ? "review-unavailable" : completed ? "result" : "info"); }} key={item.id}>{item.level} {item.session} {item.part}<small>{unavailable ? "BELUM TERSEDIA" : reviewUnavailable ? "SELESAI • REVIEW OFF" : completed ? "SELESAI" : "TERSEDIA"}</small></button>; })}</div></section>)}</section><p className="mini-list-note">Mini Checkpoint berbeda dari Try Out: soal lebih sedikit, tetapi tetap memakai timer. Passing score, review, media gambar, dan status publish diatur Admin.</p></>;
}
