"use client";

import Link from "next/link";
import { useState } from "react";

const tryouts = [
  { icon: "試", title: "Try Out N4 — Simulasi 1", status: "TERSEDIA", description: "Simulasi penuh dengan review jawaban setelah submit.", meta: "100 soal • 90 menit • 2 attempt", available: true },
  { icon: "時", title: "Try Out N3 — Agustus", status: "MENUNGGU", description: "Dijadwalkan dan belum dapat dimulai.", meta: "Mulai 12 Agustus • 1 attempt" },
  { icon: "鍵", title: "Try Out N2 — Latihan Resmi", status: "TERKUNCI", description: "Memerlukan level N2 aktif atau aturan khusus Admin.", meta: "Level tidak aktif • review tersedia" },
  { icon: "再", title: "Try Out N4 — Simulasi 2025", status: "ATTEMPT HABIS", description: "Seluruh attempt sudah digunakan.", meta: "Nilai terakhir 78 • 0 attempt" },
  { icon: "答", title: "Try Out N4 — Review Tertutup", status: "SELESAI", description: "Hasil tersedia tetapi pembahasan dinonaktifkan.", meta: "Nilai 82 • review off" },
];

export function SenseiTryoutScreen() {
  const [view, setView] = useState<"list" | "info">("list");
  if (view === "info") return <div className="sensei-tryout"><button className="sensei-back" type="button" onClick={() => setView("list")}>← Kembali ke Daftar</button><div className="tryout-info-head"><header><p className="dash-kicker">TRY OUT N4 • SIMULASI 1</p><h1>Periksa aturan sebelum memulai</h1><p>Attempt baru dicatat setelah sesi benar-benar dimulai.</p></header><span>TERSEDIA</span></div><section className="tryout-info-summary"><p className="dash-kicker">SIMULASI JLPT N4</p><h2>100 soal • 90 menit • 2 attempt tersedia</h2><p>Jawaban tersimpan otomatis. Saat waktu habis, sistem melakukan auto-submit dan mengarahkan ke hasil.</p><div><button type="button" disabled>Mulai Try Out</button><button type="button" onClick={() => setView("list")}>Kembali ke Daftar</button></div></section><section className="tryout-info-rules"><header><p className="dash-kicker">ATURAN SESI</p><h2>Yang perlu diperhatikan</h2><p>Semua ketentuan berasal dari konfigurasi Try Out di Admin.</p></header><div>{[["鍵","Akses","Belajar dengan Sensei • Level N4 aktif","Plan dan level diverifikasi backend"],["時","Waktu","90 menit sejak tombol mulai ditekan","Timer tetap berjalan selama sesi"],["再","Percobaan","2 attempt tersedia untuk akun ini","Submit dan timeout mengurangi attempt"],["答","Ulasan Jawaban","Aktif setelah hasil diproses","Dapat dinonaktifkan per Try Out"]].map(([icon,title,detail,meta]) => <article key={title}><span>{icon}</span><div><p className="dash-kicker">{title} • AKTIF</p><strong>{detail}</strong><small>{meta}</small></div></article>)}</div></section><section className="tryout-info-consent"><p>Dengan memulai, pengguna menyetujui timer, autosave, auto-submit, dan pencatatan attempt.</p><p>Koneksi terputus tidak menghapus jawaban yang sudah tersimpan di backend.</p></section></div>;
  return <div className="sensei-tryout"><div className="tryout-list-head"><header><p className="dash-kicker">TRY OUT • SIMULASI JLPT</p><h1>Pilih Try Out yang tersedia</h1><p>Akses, tanggal, attempt, dan ulasan jawaban mengikuti konfigurasi Admin.</p></header><span>BACKEND DRIVEN</span></div><div className="tryout-list-filters"><span>ATURAN AKSES</span>{["SEMUA LEVEL","N4","TERSEDIA","SELESAI","REVIEW AKTIF"].map((filter) => <button className={filter === "N4" ? "active" : ""} type="button" key={filter}>{filter}</button>)}</div><section className="tryout-list"><header><p className="dash-kicker">DAFTAR TRY OUT</p><h2>Simulasi yang tersedia</h2><p>Setiap kartu menjelaskan status, attempt, dan akses review.</p></header><div>{tryouts.map((item) => <article key={item.title}><span aria-hidden="true">{item.icon}</span><div><small>{item.status}</small><h2>{item.title}</h2><p>{item.description}</p><b>{item.meta}</b></div>{item.available ? <button type="button" onClick={() => setView("info")}>Buka Info →</button> : <span className="tryout-item-state">{item.status}</span>}</article>)}<article><span aria-hidden="true">練</span><div><small>AKTIF</small><h2>Latihan Harian</h2><p>Kembali ke drill singkat dan rekomendasi harian.</p><b>Tidak menggunakan attempt Try Out</b></div><Link href="/practice?membership=sensei">Buka →</Link></article></div></section><p className="tryout-list-note">Try Out berbeda dari Latihan Harian: memiliki timer, jumlah soal, attempt, hasil, dan aturan review tersendiri.</p></div>;
}
