"use client";

import Link from "next/link";
import { useState } from "react";
import { AssessmentUnavailable } from "@/components/assessment-unavailable";

type View = "list" | "info" | "runner" | "timeout" | "result" | "review" | "review-unavailable" | "locked" | "waiting" | "exhausted";

const tryouts: { icon: string; title: string; status: string; description: string; meta: string; view: View }[] = [
  { icon: "試", title: "Try Out N4 — Simulasi 1", status: "TERSEDIA", description: "Simulasi penuh dengan review jawaban setelah submit.", meta: "100 soal • 90 menit • 2 attempt", view: "info" },
  { icon: "時", title: "Try Out N3 — Agustus", status: "MENUNGGU", description: "Dijadwalkan dan belum dapat dimulai.", meta: "Mulai 12 Agustus • 1 attempt", view: "waiting" },
  { icon: "鍵", title: "Try Out N2 — Latihan Resmi", status: "TERKUNCI", description: "Memerlukan level N2 aktif atau aturan khusus Admin.", meta: "Level tidak aktif • review tersedia", view: "locked" },
  { icon: "再", title: "Try Out N4 — Simulasi 2025", status: "ATTEMPT HABIS", description: "Seluruh attempt sudah digunakan.", meta: "Nilai terakhir 78 • 0 attempt", view: "exhausted" },
  { icon: "答", title: "Try Out N4 — Review Tertutup", status: "SELESAI", description: "Hasil tersedia tetapi pembahasan dinonaktifkan.", meta: "Nilai 82 • review off", view: "review-unavailable" },
];

export function SenseiTryoutScreen() {
  const [view, setView] = useState<View>("list");
  const [answer, setAnswer] = useState("b");
  const [marked, setMarked] = useState(false);
  const list = () => setView("list");
  if (view === "locked") return <AssessmentUnavailable eyebrow="TRY OUT • AKSES TERKUNCI" title="Try Out ini belum tersedia untuk akunmu" description="Akses mengikuti plan, level, tanggal, dan prerequisite Chapter yang dikonfigurasi Admin." facts={["Aturan backend", "Level spesifik", "Progress aman"]} primary={{ label: "Lihat Paket Level", href: "/program?membership=sensei" }} secondary={{ label: "Kembali ke Try Out", onClick: list }} />;
  if (view === "waiting") return <AssessmentUnavailable eyebrow="TRY OUT • BELUM DIMULAI" title="Jadwal Try Out belum aktif" description="Try Out akan terbuka otomatis sesuai tanggal mulai yang ditetapkan Admin." facts={["Jadwal backend", "Tidak mengurangi attempt", "Pengingat tersedia"]} primary={{ label: "Kembali ke Daftar", onClick: list }} secondary={{ label: "Kembali Dashboard", href: "/dashboard?membership=sensei" }} />;
  if (view === "exhausted") return <AssessmentUnavailable eyebrow="TRY OUT • ATTEMPT HABIS" title="Seluruh percobaan sudah digunakan" description="Admin menentukan jumlah attempt dan kemungkinan reset. Hasil terakhir tetap tersimpan." facts={["Attempt tercatat", "Hasil tersimpan", "Reset oleh Admin"]} primary={{ label: "Lihat Hasil Terakhir", onClick: () => setView("result") }} secondary={{ label: "Kembali ke Daftar", onClick: list }} />;
  if (view === "timeout") return <AssessmentUnavailable eyebrow="TRY OUT • WAKTU HABIS" title="Jawaban otomatis dikirim" description="Saat timer berakhir, jawaban yang tersimpan dikirim otomatis dan pengguna dapat membuka hasil." facts={["Autosave aktif", "Auto-submit", "Attempt tercatat"]} primary={{ label: "Lihat Hasil", onClick: () => setView("result") }} secondary={{ label: "Kembali ke Daftar", onClick: list }} />;
  if (view === "review-unavailable") return <AssessmentUnavailable eyebrow="ULASAN • DINONAKTIFKAN" title="Ulasan jawaban belum tersedia" description="Admin dapat mengaktifkan atau menonaktifkan review per Try Out. Nilai dan hasil tetap tersimpan." facts={["Aturan per Try Out", "Nilai tersimpan", "Backend authority"]} primary={{ label: "Kembali ke Hasil", onClick: () => setView("result") }} secondary={{ label: "Kembali ke Daftar", onClick: list }} />;
  if (view === "runner") return <div className="sensei-tryout tryout-runner"><header><div><p className="dash-kicker">TRY OUT N4 • SESI BERJALAN</p><h1>Soal 18 dari 100</h1><p>Jawaban tersimpan otomatis dan timer dikendalikan backend.</p></div><button className="tryout-timeout-trigger" type="button" onClick={() => setView("timeout")}><span>ATTEMPT 1/2</span><small>SISA WAKTU</small><strong>01:12:36</strong><small>Picu waktu habis</small></button></header><section className="tryout-runner-stats">{[["14 / 100","Soal dijawab"],["3 soal","Ditandai"],["Aktif","Autosave"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><div className="tryout-runner-layout"><main><section className="learning-question-card"><p className="dash-kicker">BAGIAN BUNPOU • SOAL 18</p><h2>Pilih jawaban yang paling tepat.</h2><p className="tryout-question-japanese">日本へ行く前に、パスポートを＿＿＿＿。</p><small>Gambar soal dari Admin (opsional)</small><fieldset><legend className="sr-only">Pilihan jawaban</legend>{[["a","確認しておきます"],["b","確認しています"],["c","確認したことがあります"],["d","確認するでしょう"]].map(([id,label], index) => <label className={answer === id ? "selected" : ""} key={id}><input type="radio" name="tryout-answer" checked={answer === id} onChange={() => setAnswer(id)} /><span>{String.fromCharCode(65 + index)}. {label}</span></label>)}</fieldset></section><div className="tryout-runner-actions"><button type="button" disabled>Sebelumnya</button><button className={marked ? "marked" : ""} type="button" onClick={() => setMarked((value) => !value)}>Tandai Soal</button><button type="button" disabled>Selanjutnya</button></div></main><aside><p className="dash-kicker">NAVIGATOR</p><strong>14 dijawab • {marked ? "3" : "2"} ditandai</strong><div>{Array.from({ length: 25 }, (_, index) => <button className={index === 17 ? "active" : ""} disabled={index !== 17} type="button" key={index}>{index + 1}</button>)}</div><button className="tryout-submit" type="button" onClick={() => setView("result")}>Akhiri &amp; Kirim</button><button type="button" onClick={list}>Kembali ke Daftar</button></aside></div></div>;
  if (view === "result") return <div className="sensei-tryout tryout-result"><header><p className="dash-kicker">TRY OUT N4 • HASIL</p><h1>Hasil simulasi berhasil diproses</h1><p>Skor, breakdown, dan rekomendasi berasal dari jawaban yang tersimpan.</p><span>SELESAI</span></header><section className="tryout-score"><p className="dash-kicker">SKOR AKHIR</p><strong>82 / 100</strong><p>Lulus target latihan • Attempt 1 dari 2 • Durasi 78 menit</p><div><button type="button" onClick={() => setView("review")}>Ulasan Jawaban</button><button type="button" onClick={list}>Kembali ke Daftar</button></div></section></div>;
  if (view === "review") return <div className="sensei-tryout tryout-review"><header><div><p className="dash-kicker">TRY OUT N4 • ULASAN</p><h1>Tinjau jawaban dan pembahasan</h1><p>Review tersedia karena diaktifkan pada konfigurasi Try Out ini.</p></div><span>REVIEW AKTIF</span></header><div className="tryout-review-layout"><main><p className="dash-kicker">SOAL 4 • BUNPOU</p><h2>日本へ行く前に、パスポートを＿＿＿＿。</h2><section><p>Pola ～ておく digunakan untuk menyatakan persiapan yang dilakukan sebelumnya.</p></section></main></div><div className="learning-question-actions"><button className="button button-secondary" type="button" onClick={() => setView("result")}>Kembali ke Hasil</button><Link className="button button-dark" href="/practice?membership=sensei">Latihan Rekomendasi</Link></div></div>;
  if (view === "info") return <div className="sensei-tryout"><button className="sensei-back" type="button" onClick={list}>← Kembali ke Daftar</button><div className="tryout-info-head"><header><p className="dash-kicker">TRY OUT N4 • SIMULASI 1</p><h1>Periksa aturan sebelum memulai</h1><p>Attempt baru dicatat setelah sesi benar-benar dimulai.</p></header><span>TERSEDIA</span></div><section className="tryout-info-summary"><p className="dash-kicker">SIMULASI JLPT N4</p><h2>100 soal • 90 menit • 2 attempt tersedia</h2><p>Jawaban tersimpan otomatis. Saat waktu habis, sistem melakukan auto-submit dan mengarahkan ke hasil.</p><div><button type="button" onClick={() => setView("runner")}>Mulai Try Out</button><button type="button" onClick={list}>Kembali ke Daftar</button></div></section></div>;
  return <div className="sensei-tryout"><div className="tryout-list-head"><header><p className="dash-kicker">TRY OUT • SIMULASI JLPT</p><h1>Pilih Try Out yang tersedia</h1><p>Akses, tanggal, attempt, dan ulasan jawaban mengikuti konfigurasi Admin.</p></header><span>BACKEND DRIVEN</span></div><section className="tryout-list"><header><p className="dash-kicker">DAFTAR TRY OUT</p><h2>Simulasi yang tersedia</h2><p>Setiap kartu menjelaskan status, attempt, dan akses review.</p></header><div>{tryouts.map((item) => <article key={item.title}><span aria-hidden="true">{item.icon}</span><div><small>{item.status}</small><h2>{item.title}</h2><p>{item.description}</p><b>{item.meta}</b></div><button type="button" onClick={() => setView(item.view)}>{item.view === "info" ? "Buka Info →" : "Lihat Status →"}</button></article>)}</div></section></div>;
}
