"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { replays, scheduleSessions } from "@/lib/sensei-mock";

export function ScheduleScreen() {
  return <><div className="sensei-title-row"><PageHead eyebrow="BELAJAR DENGAN SENSEI • JADWAL KELAS" title="Jadwal cohort dan sesi bersama Sensei" description="Tanggal, jam, durasi, Sensei, cohort, dan link kelas mengikuti konfigurasi admin." /><Link href="/replay?membership=sensei">Lihat Replay</Link></div><div className="sensei-controls"><button aria-label="Periode sebelumnya">‹</button><span>Periode aktif dari admin</span><button aria-label="Periode berikutnya">›</button><b>Cohort Aktif</b><button>Kalender</button><button>Daftar</button></div><section className="schedule-layout"><div className="calendar-card"><div className="calendar-grid schedule-placeholder">{["Sen","Sel","Rab","Kam","Jum","Sab","Min","—","—","Zoom","—","—","Replay","—"].map((day, index) => <span className={day === "Zoom" || day === "Replay" ? "event" : ""} key={`${day}-${index}`}>{day}</span>)}</div></div><aside className="upcoming-panel"><p className="dash-kicker">Sesi mendatang</p><small>Data sesi diperbarui oleh admin.</small>{scheduleSessions.map((session) => session.id === "chapter-4" ? <Link className="schedule-session" href="/schedule/chapter-4?membership=sensei" key={session.id}><div><strong>{session.title}</strong><small>{session.meta}</small></div><span>{session.status}</span></Link> : <div className="schedule-session" key={session.id}><div><strong>{session.title}</strong><small>{session.meta}</small></div><span>{session.status}</span></div>)}</aside></section><section className="sensei-announcement"><strong>Pengumuman</strong><p>Link Zoom aktif sesuai waktu dan status yang ditentukan admin.</p></section><Link className="sensei-back" href="/dashboard?membership=sensei">← Kembali Dashboard</Link></>;
}

export function ClassDetailScreen() {
  return <><Link className="sensei-back" href="/schedule?membership=sensei">← Kembali Jadwal</Link><PageHead eyebrow="DETAIL KELAS • DATA DINAMIS" title="Chapter 4 — Sesi bersama Sensei" description="Seluruh detail kelas berasal dari konfigurasi cohort dan admin." /><section className="class-session-card"><div><span>Cohort Aktif</span><b>Terjadwal</b></div><p className="dash-kicker">Zoom</p><h2>Sensei dan jadwal dari admin</h2><p>Hari/Tanggal • Jam WIB • Durasi dinamis • Link Zoom tersedia sesuai status sesi.</p><span className="button button-dark disabled" aria-disabled="true">Link Aktif Saat Sesi</span></section><section className="class-detail-grid"><article><h2>Agenda kelas</h2>{["Review materi Chapter 4","Latihan pola kalimat","Tanya jawab dan rangkuman kelas","Arahan aktivitas berikutnya"].map((item, index) => <div className="class-agenda" key={item}><strong>{String(index + 1).padStart(2,"0")}</strong><span>{item}</span></div>)}</article><article><h2>Materi pendukung</h2>{[["文","Ringkasan grammar","Dibuka dari material chapter."],["字","Kanji sesi","Daftar kanji yang dibahas."],["問","Pertanyaan cohort","Topik yang dikirim sebelum kelas."]].map(([icon,title,detail]) => <div className="class-material" key={title}><strong>{icon}</strong><span><b>{title}</b><small>{detail}</small></span></div>)}</article></section><section className="class-reminders"><h2>Pengingat kelas</h2><div><span>Notifikasi aplikasi</span><strong>Aktif</strong><span>Email reminder</span><strong>Mengikuti pengaturan</strong><span>Pengingat waktu</span><strong>Dari admin</strong></div></section><div className="learning-question-actions"><Link className="button button-secondary" href="/replay?membership=sensei">Lihat Replay</Link></div><section className="sensei-announcement"><strong>Pengumuman</strong><p>Link, jadwal, Sensei, dan status replay diperbarui oleh admin.</p></section></>;
}

export function ReplayScreen() {
  const [filter, setFilter] = useState("Semua");
  const [search, setSearch] = useState("");
  const [playing, setPlaying] = useState<string | null>(null);
  const visible = useMemo(() => replays.filter((item) => (filter === "Semua" || item.category === filter) && item.title.toLowerCase().includes(search.toLowerCase())), [filter, search]);
  if (playing) { const replay = replays.find((item) => item.id === playing)!; return <><button className="sensei-back" onClick={() => setPlaying(null)}>← Daftar Replay</button><PageHead eyebrow="BELAJAR DENGAN SENSEI • REPLAY KELAS" title={replay.title} description={replay.meta} /><section className="replay-player"><span aria-hidden="true">▶</span><p>Player replay demo</p></section><section className="replay-player-meta"><h2>{replay.title}</h2><p>Sensei, cohort, durasi, dan status replay berasal dari admin.</p></section></>; }
  const featured = replays[0];
  return <><PageHead eyebrow="BELAJAR DENGAN SENSEI • REPLAY KELAS" title="Tonton kembali sesi yang telah dipublikasikan" description="Sensei, cohort, durasi, dan status replay berasal dari admin." /><label className="replay-search">Cari replay, chapter, atau Sensei<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari replay, chapter, atau Sensei" /></label><div className="replay-filters">{["Semua","Chapter 4","Tersimpan"].map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="replay-featured"><div><p className="dash-kicker">Replay terbaru</p><h2>{featured.title}</h2><p>{featured.meta}</p><button onClick={() => setPlaying(featured.id)}>Putar Replay</button></div><span aria-hidden="true">▶</span></section><section className="replay-grid">{visible.filter((item) => !item.featured).map((item) => <article key={item.id}><span aria-hidden="true">▶</span><h2>{item.title}</h2><p>{item.meta}</p><button onClick={() => setPlaying(item.id)}>Putar Replay</button></article>)}</section></>;
}

function PageHead({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header className="sensei-page-head"><p className="dash-kicker">{eyebrow}</p><h1>{title}</h1><p>{description}</p></header>;
}
