"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { replayMarkers, replays, scheduleSessions } from "@/lib/sensei-mock";

type StateAction = { label: string; href?: string; onClick?: () => void };

function SenseiState({ eyebrow, title, status, description, facts, primary, secondary }: { eyebrow: string; title: string; status: string; description: string; facts: string[]; primary: StateAction; secondary: StateAction }) {
  const action = (item: StateAction, primaryAction: boolean) => item.href ? <Link className={`button ${primaryAction ? "button-primary" : "button-secondary"}`} href={item.href}>{item.label}</Link> : <button className={`button ${primaryAction ? "button-primary" : "button-secondary"}`} type="button" onClick={item.onClick}>{item.label}</button>;
  return <section className="sensei-status-panel"><p className="dash-kicker">{eyebrow}</p><h1>{title}</h1><span className="supporting-badge">{status}</span><p>{description}</p><div className="status-topic">{facts.map((fact) => <strong key={fact}>{fact}</strong>)}</div><div className="status-actions">{action(primary, true)}{action(secondary, false)}</div></section>;
}

export function ScheduleScreen() {
  const [view, setView] = useState<"calendar" | "list" | "empty">("calendar");
  const [period, setPeriod] = useState(0);
  if (view === "empty") return <SenseiState eyebrow="ZOOM • EMPTY" title="Belum ada sesi pada periode ini" status="Processing" description="Jadwal akan muncul setelah cohort dan sesi dipublikasikan admin." facts={["Backend status", "Dynamic schedule", "Entitlement check"]} primary={{ label: "Kembali Jadwal", onClick: () => { setPeriod(0); setView("calendar"); } }} secondary={{ label: "Lihat Replay", href: "/replay?membership=sensei" }} />;
  return <><div className="sensei-title-row"><PageHead eyebrow="BELAJAR DENGAN SENSEI • JADWAL KELAS" title="Jadwal cohort dan sesi bersama Sensei" description="Tanggal, jam, durasi, Sensei, cohort, dan link kelas mengikuti konfigurasi admin." /><Link href="/replay?membership=sensei">Lihat Replay</Link></div><div className="sensei-controls"><button type="button" aria-label="Periode sebelumnya" onClick={() => { setPeriod(-1); setView("empty"); }}>Sebelumnya</button><span>{period === 0 ? "Periode aktif dari admin" : "Periode tanpa sesi"}</span><button type="button" aria-label="Periode berikutnya" onClick={() => { setPeriod(1); setView("empty"); }}>Berikutnya</button><b>Cohort Aktif</b><button className={view === "calendar" ? "active" : ""} type="button" onClick={() => setView("calendar")}>Kalender</button><button className={view === "list" ? "active" : ""} type="button" onClick={() => setView("list")}>Daftar</button></div>{view === "calendar" ? <section className="schedule-layout"><div className="calendar-card"><div className="calendar-grid schedule-placeholder">{["Sen","Sel","Rab","Kam","Jum","Sab","Min","—","—","Zoom","—","—","Replay","—"].map((day, index) => day === "Zoom" ? <Link className="event" href="/schedule/chapter-4?membership=sensei" key={`${day}-${index}`}>{day}</Link> : <span className={day === "Replay" ? "event" : ""} key={`${day}-${index}`}>{day}</span>)}</div></div><SessionList /></section> : <SessionList />}<section className="sensei-announcement"><strong>Pengumuman</strong><p>Link Zoom aktif sesuai waktu dan status yang ditentukan admin.</p></section><Link className="sensei-back" href="/dashboard?membership=sensei">Kembali Dashboard</Link></>;
}

function SessionList() {
  return <aside className="upcoming-panel"><p className="dash-kicker">Sesi mendatang</p><small>Data sesi diperbarui oleh admin.</small>{scheduleSessions.map((session) => session.id === "chapter-4" ? <Link className="schedule-session" href="/schedule/chapter-4?membership=sensei" key={session.id}><div><strong>{session.title}</strong><small>{session.meta}</small></div><span>{session.status}</span></Link> : <div className="schedule-session" key={session.id}><div><strong>{session.title}</strong><small>{session.meta}</small></div><span>{session.status}</span></div>)}</aside>;
}

export function ClassDetailScreen() {
  const [state, setState] = useState<"detail" | "zoom" | "reminder">("detail");
  if (state === "zoom") return <SenseiState eyebrow="ZOOM • LINK UNAVAILABLE" title="Link Zoom belum aktif" status="Unavailable" description="Link tersedia sesuai waktu, status sesi, dan konfigurasi admin." facts={["Backend status", "Dynamic schedule", "Entitlement check"]} primary={{ label: "Kembali ke Detail", onClick: () => setState("detail") }} secondary={{ label: "Lihat Jadwal", href: "/schedule?membership=sensei" }} />;
  if (state === "reminder") return <SenseiState eyebrow="CLASS • REMINDER" title="Pengingat kelas tersimpan" status="Saved" description="Channel, lead time, dan delivery mengikuti preference serta konfigurasi kelas." facts={["Backend status", "Dynamic schedule", "Entitlement check"]} primary={{ label: "Kembali ke Kelas", onClick: () => setState("detail") }} secondary={{ label: "Lihat Jadwal", href: "/schedule?membership=sensei" }} />;
  return <><Link className="sensei-back" href="/schedule?membership=sensei">Kembali Jadwal</Link><PageHead eyebrow="DETAIL KELAS • DATA DINAMIS" title="Chapter 4 — Sesi bersama Sensei" description="Seluruh detail kelas berasal dari konfigurasi cohort dan admin." /><section className="class-session-card"><div><span>Cohort Aktif</span><b>Terjadwal</b></div><p className="dash-kicker">Zoom</p><h2>Sensei dan jadwal dari admin</h2><p>Hari/Tanggal • Jam WIB • Durasi dinamis • Link Zoom tersedia sesuai status sesi.</p><button className="button button-dark" type="button" onClick={() => setState("zoom")}>Link Aktif Saat Sesi</button></section><section className="class-detail-grid"><article><h2>Agenda kelas</h2>{["Review materi Chapter 4","Latihan pola kalimat","Tanya jawab dan rangkuman kelas","Arahan aktivitas berikutnya"].map((item, index) => <div className="class-agenda" key={item}><strong>{String(index + 1).padStart(2,"0")}</strong><span>{item}</span></div>)}</article><article><h2>Materi pendukung</h2>{[["文","Ringkasan grammar","Dibuka dari material chapter."],["字","Kanji sesi","Daftar kanji yang dibahas."],["問","Pertanyaan cohort","Topik yang dikirim sebelum kelas."]].map(([icon,title,detail]) => <div className="class-material" key={title}><strong>{icon}</strong><span><b>{title}</b><small>{detail}</small></span></div>)}</article></section><section className="class-reminders"><h2>Pengingat kelas</h2><div><span>Notifikasi aplikasi</span><strong>Aktif</strong><span>Email reminder</span><strong>Mengikuti pengaturan</strong><span>Pengingat waktu</span><strong>Dari admin</strong></div><button className="button button-primary" type="button" onClick={() => setState("reminder")}>Simpan Pengingat</button></section><div className="learning-question-actions"><Link className="button button-secondary" href="/replay?membership=sensei">Lihat Replay</Link></div><section className="sensei-announcement"><strong>Pengumuman</strong><p>Link, jadwal, Sensei, dan status replay diperbarui oleh admin.</p></section></>;
}

export function ReplayScreen() {
  const [filter, setFilter] = useState("Semua");
  const [search, setSearch] = useState("");
  const [processing, setProcessing] = useState(false);
  const visible = useMemo(() => replays.filter((item) => (filter === "Semua" || item.category === filter) && item.title.toLowerCase().includes(search.toLowerCase())), [filter, search]);
  const featured = replays[0];
  if (processing) return <SenseiState eyebrow="REPLAY • PROCESSING" title="Replay sedang diproses" status="Processing" description="Rekaman, transkrip, dan materi sedang disiapkan sebelum dipublikasikan." facts={["Backend status", "Dynamic schedule", "Entitlement check"]} primary={{ label: "Kembali ke Replay", onClick: () => setProcessing(false) }} secondary={{ label: "Lihat Jadwal", href: "/schedule?membership=sensei" }} />;
  return <><div className="sensei-title-row"><PageHead eyebrow="BELAJAR DENGAN SENSEI • REPLAY KELAS" title="Tonton kembali sesi yang telah dipublikasikan" description="Sensei, cohort, durasi, dan status replay berasal dari admin." /><Link href="/schedule?membership=sensei">Lihat Jadwal</Link></div><label className="replay-search">Cari replay, chapter, atau Sensei<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari replay, chapter, atau Sensei" /></label><div className="replay-filters">{["Semua","Chapter 4","Tersimpan"].map((item) => <button type="button" className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="replay-featured"><button className="replay-processing-trigger" type="button" onClick={() => setProcessing(true)}><p className="dash-kicker">Replay terbaru</p><span>REPLAY TERBARU • Dipublikasikan • Cohort Aktif</span><h2>{featured.title}</h2><p>{featured.description}</p><small>Sensei dari admin • Durasi dan publikasi dinamis</small></button><Link href="/replay/chapter-4?membership=sensei">Putar Replay</Link></section><h2 className="replay-section-title">Replay lainnya</h2>{visible.length ? <section className="replay-grid">{visible.filter((item) => !item.featured).map((item) => <article key={item.id}><small>REPLAY • Dipublikasikan • Cohort Aktif</small><h2>{item.title}</h2><p>{item.description}</p><small>Sensei dari admin • Durasi dan publikasi dinamis</small><Link href="/replay/chapter-4?membership=sensei">Buka Replay</Link></article>)}</section> : <section className="library-empty"><h2>Tidak ada replay ditemukan</h2><p>Ubah pencarian atau filter untuk melihat replay fixture lain.</p></section>}<section className="sensei-announcement"><strong>Pengumuman</strong><p>Replay tampil setelah admin mempublikasikan rekaman sesi.</p></section></>;
}

export function ReplayPlayerScreen() {
  const [tab, setTab] = useState("Ringkasan");
  const [state, setState] = useState<"player" | "error">("player");
  const [marker, setMarker] = useState("00:00");
  if (state === "error") return <SenseiState eyebrow="REPLAY • ERROR" title="Replay belum dapat dimuat" status="Error" description="Coba kembali atau ulangi pemuatan. Status error dan sumber video diperiksa backend." facts={["Backend status", "Dynamic schedule", "Entitlement check"]} primary={{ label: "Coba Lagi", onClick: () => setState("player") }} secondary={{ label: "Kembali ke List", href: "/replay?membership=sensei" }} />;
  return <><Link className="sensei-back" href="/replay?membership=sensei">Kembali ke Replay</Link><PageHead eyebrow="REPLAY • CHAPTER 4 • COHORT AKTIF" title="Pola Kalimat dan Kehidupan Sehari-hari" description="Sumber video, durasi, Sensei, chapter markers, dan materi berasal dari admin." /><section className="replay-player"><button type="button" onClick={() => setState("error")}>Mulai video</button><p>Replay • lazy-loaded</p><small>Sensei dan cohort dari admin<br />Tanggal sesi • durasi • status publikasi dinamis</small></section><div className="replay-tabs" role="tablist">{["Ringkasan","Transkrip","Materi","Catatan"].map((item) => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><section className="replay-content" role="tabpanel">{tab === "Ringkasan" && <><h2>Ringkasan kelas</h2><p>Replay mencakup review Chapter 4, latihan pola kalimat, diskusi cohort, serta arahan aktivitas berikutnya.</p></>}{tab === "Transkrip" && <><p className="dash-kicker">TRANSKRIP PREVIEW</p><p>Transkrip lengkap mengikuti file yang dipublikasikan admin. Gunakan marker waktu untuk melompat ke bagian tertentu.</p></>}{tab === "Materi" && <><h2>Materi terkait</h2><div className="replay-summary"><span>Ringkasan Grammar</span><span>Daftar Kanji</span><span>Latihan Sesi</span></div></>}{tab === "Catatan" && <p>Catatan mengikuti konfigurasi replay.</p>}</section><section className="replay-markers"><h2>Chapter markers</h2>{replayMarkers.map(([time,label]) => <button className={marker === time ? "active" : ""} type="button" onClick={() => setMarker(time)} key={time}><strong>{time}</strong><span>{label}</span></button>)}</section><section className="sensei-announcement"><strong>Status publikasi</strong><p>Replay, transkrip, dan materi tersedia setelah admin mempublikasikannya.</p></section><Link className="button button-secondary" href="/schedule/chapter-4?membership=sensei">Lihat Detail Kelas</Link></>;
}

function PageHead({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header className="sensei-page-head"><p className="dash-kicker">{eyebrow}</p><h1>{title}</h1><p>{description}</p></header>;
}
