import { StudentNavigation } from "@/components/student-navigation";
import { supportingData, type SupportingKind } from "@/lib/supporting-mock";
import Link from "next/link";
import { useState } from "react";

export function SupportingScreen({ kind, membership }: { kind: SupportingKind; membership: "free" | "lms" | "sensei" }) {
  const data = supportingData[kind];
  if (kind === "practice" && membership === "sensei") return <SenseiPractice />;
  if (kind === "library") return <LibraryScreen membership={membership} />;
  if (kind === "progress") return <ProgressScreen membership={membership} />;
  if (kind === "leaderboard") return <LeaderboardScreen membership={membership} />;
  if (kind === "createPost") return <CreatePostScreen membership={membership} />;
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current={kind === "notifications" ? "notifications" : kind === "profile" ? "profile" : "supporting"} /><main className="supporting-main"><header className="supporting-header"><p className="dash-kicker">{data.eyebrow}</p><h1>{data.title}</h1><p>{data.description}</p>{data.locked && <span className="supporting-badge">TERBATAS</span>}</header><section className="supporting-grid">{data.cards.map((card) => <article className="supporting-card" key={card.title}><span className="supporting-icon" aria-hidden="true">{card.icon}</span><div><span className="supporting-status">{card.status}</span><h2>{card.title}</h2><p>{card.description}</p></div>{card.href ? <Link className="supporting-action" href={`${card.href}?membership=${membership}`}>{card.action ?? "Buka"} +</Link> : <span className="supporting-action disabled" aria-disabled="true">{card.action ?? "Tersedia"}</span>}</article>)}</section>{data.notice && <aside className="supporting-notice"><strong>{data.notice.title}</strong><p>{data.notice.description}</p></aside>}</main></div>;
}

function CreatePostScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="supporting" /><main className="supporting-main"><header className="supporting-header"><p className="dash-kicker">BUAT POSTINGAN</p><h1>Bagikan pertanyaan atau pengalaman belajar</h1><p>Postingan mengikuti aturan komunitas dan dapat melalui moderasi.</p></header><form className="form-stack"><label><span>Kategori</span><select><option>Diskusi Member</option></select></label><label><span>Judul</span><input placeholder="Tulis judul postingan" /></label><label><span>Ringkasan</span><textarea placeholder="Tulis ringkasan postingan" /></label><div className="button-group"><button type="submit" className="button button-primary">Publikasikan</button><Link href={`/community?membership=${membership}`} className="button button-secondary">Batal</Link></div></form></main></div>;
}

function ProgressScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const query = `?membership=${membership}`;
  const milestones = [["o","Fondasi N4","Chapter awal dan checkpoint","Selesai"],["o","Rutinitas Harian","Video, modul, dan latihan","Selesai"],["03","Pola Kalimat","Chapter aktif","Aktif"],["04","Try Out N4","Tersedia setelah journey","Terkunci"],["05","Sertifikat N4","Mengikuti eligibility","Terkunci"]];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="progress" /><main className="supporting-main progress-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">PROGRES &amp; ACHIEVEMENT</p><h1>Rayakan progres tanpa kehilangan fokus</h1><p>Progress, streak, mastery, dan achievement dihitung dari journey serta aktivitas backend.</p></header><Link href={`/profile${query}`}>Profil</Link></div><section className="progress-summary"><div><p className="dash-kicker">MEMBER  LEVEL N4</p><h2>Perjalanan belajar terus bertumbuh</h2><p>Persentase dan milestone mengikuti completion serta assessment yang valid.</p><span>12 Hari Streak</span></div><div className="progress-stats">{[["65%","Journey N4"],["450","Kanji mastered"],["?","Latihan selesai"],["?","Try Out terbaik"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="progress-milestones"><h2>Milestone journey</h2>{milestones.map(([number,title,description,status]) => <article key={title}><span>{number}</span><div><strong>{title}</strong><small>{description}</small></div><b>{status}</b></article>)}</section><section className="progress-achievements"><div className="progress-tabs"><button className="active" type="button">Achievement</button><Link href={`/leaderboard${query}`}>Leaderboard</Link></div><div>{[["?","Streak 7 Hari","Belajar konsisten selama tujuh hari.","Terbuka"],["o-","Flashcard Master","Menyelesaikan target flashcard.","Terbuka"],["c","Try Out Finisher","Menyelesaikan Try Out pertama.","Belum terbuka"],["\"","Certificate Ready","Memenuhi eligibility sertifikat.","Belum terbuka"]].map(([icon,title,description,status]) => <article key={title}><span>{icon}</span><h2>{title}</h2><p>{description}</p><b>{status}</b></article>)}</div></section></main></div>;
}

function LeaderboardScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [period, setPeriod] = useState("Mingguan");
  const query = `?membership=${membership}`;
  const rows = [["04","Member 4","Member community","+ 2"],["05","Member 5","Member community","?"],["06","Member 6","Member community","+ 1"],["07","Kamu","Posisimu saat ini","+ 3"],["08","Member 8","Member community","?"]];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="leaderboard" /><main className="supporting-main leaderboard-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">LEADERBOARD</p><h1>Bandingkan konsistensi, bukan tekanan</h1><p>Poin, periode, cohort, rank, dan movement berasal dari backend serta dapat menggunakan nama samaran.</p></header><Link href={`/progress${query}`}>Progres</Link></div><div className="leaderboard-filters">{["Mingguan","Bulanan","N4","Cohort","Semua Member"].map((filter) => <button className={period === filter ? "active" : ""} type="button" onClick={() => setPeriod(filter)} key={filter}>{filter}</button>)}</div><section className="leaderboard-podium">{[["#02","Member 2"],["#01","Member 1"],["#03","Member 3"]].map(([rank,name]) => <article className={rank === "#01" ? "winner" : ""} key={rank}><strong>{rank}</strong><h2>{name}</h2><span>Poin ?</span></article>)}</section><section className="leaderboard-list">{rows.map(([rank,name,meta,movement]) => <article className={name === "Kamu" ? "current" : ""} key={rank}><strong>{rank}</strong><div><h2>{name}</h2><span>{meta}</span></div><div><b>Poin ?</b><small>Poin dinamis</small></div><i>{movement}</i></article>)}</section><aside className="leaderboard-notice"><strong>Pengumuman</strong><p>Leaderboard dapat menggunakan nama samaran dan hanya menampilkan aktivitas yang diizinkan.</p></aside></main></div>;
}

function LibraryScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [search, setSearch] = useState("");
  const [level, setLevel] = useState("Semua");
  const [type, setType] = useState("Semua");
  const [locked, setLocked] = useState(false);
  const materials = [
    { icon: "-", type: "Tata Bahasa", title: "Pola Kalimat Sehari-hari", description: "Modul Chapter 4 yang terakhir dibuka.", status: "Tersimpan", href: `/learn/n4/chapter-4/grammar?membership=${membership}` },
    { icon: "", type: "Kanji", title: "Keadaan, Waktu & Aktivitas", description: "Kanji chapter dengan bookmark dan catatan.", status: "Tersedia", href: `/learn/n4/chapter-4/kanji?membership=${membership}` },
    { icon: "AUDIO", type: "Audio", title: "Simulasi Choukai N4", description: "Akses audio lengkap mengikuti membership.", status: "Terkunci" },
  ];
  const visible = materials.filter((item) => (type === "Semua" || item.type === type) && item.title.toLowerCase().includes(search.toLowerCase()) && (level === "Semua" || level === "N4"));
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="library" /><main className="supporting-main library-page"><header className="supporting-header"><p className="dash-kicker">PERPUSTAKAAN MATERI</p><h1>Temukan kembali materi dari seluruh journey</h1><p>Akses material mengikuti level dan entitlement membership.</p></header><label className="library-search"><span aria-hidden="true">O </span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari materi, tata bahasa, kanji, atau audio" /></label><div className="library-filters">{["Semua","N5","N4","N3","SSW","Interview"].map((item) => <button className={level === item ? "active" : ""} type="button" onClick={() => setLevel(item)} key={item}>{item}</button>)}</div><div className="library-filters types">{["Semua","Tata Bahasa","Kanji","Kosakata","Audio","Reading"].map((item) => <button className={type === item ? "active" : ""} type="button" onClick={() => setType(item)} key={item}>{item}</button>)}</div>{visible.length ? <><section className="library-section-head"><h2>Rekomendasi N4</h2></section><section className="library-material-grid">{visible.map((item) => <article key={item.title}><span aria-hidden="true">{item.icon}</span><small>{item.type}</small><h2>{item.title}</h2><p>{item.description}</p><b>{item.status}</b>{item.href ? <Link aria-label={`${item.type}: ${item.title}`} href={item.href}>Buka materi</Link> : <button type="button" onClick={() => setLocked(true)} aria-label={`${item.type}: ${item.title}`}>Lihat status</button>}</article>)}</section><section className="library-recent"><p className="dash-kicker">Baru dibuka</p>{[["z","Flashcard Chapter 4","Kosakata"],["-","Reading Aktivitas Harian","Reading"],["c","Review Try Out 1","Try Out"]].map(([icon,title,meta]) => <div key={title}><span>{icon}</span><strong>{title}</strong><small>{meta}</small></div>)}</section></> : <section className="library-empty"><p className="dash-kicker">LIBRARY  EMPTY</p><h2>Belum ada materi pada filter ini</h2><span>c</span><p>Ubah level, kategori, atau kata kunci untuk menemukan materi yang tersedia.</p><small>Filter dapat direset  Entitlement tetap diperiksa  Data berasal dari backend</small><button type="button" onClick={() => { setSearch(""); setLevel("Semua"); setType("Semua"); }}>Reset Filter</button></section>}{locked && <div className="library-locked" role="dialog" aria-modal="true" aria-labelledby="library-locked-title"><section><p className="dash-kicker">CONTENT  LOCKED</p><h2 id="library-locked-title">Materi belum termasuk dalam aksesmu</h2><span></span><p>Akses mengikuti level dan plan membership. Progress yang sudah tersimpan tidak hilang.</p><small>Plan gated  Backend authority  Renewal atau upgrade tersedia</small><div><Link href={`/renewal?membership=${membership}`}>Lihat Membership</Link><button type="button" onClick={() => setLocked(false)}>Kembali ke Library</button></div></section></div>}</main></div>;
}

function SenseiPractice() {
  const base = "/learn/n4/chapter-4";
  const query = "?membership=sensei";
  const modes = [
    ["o-", "REKOMENDASI", "Flashcard Review", "Ulangi kosakata dan pola dengan confidence state.", "5-10 menit  deck level aktif", `${base}/flashcards${query}`],
    ["AUDIO", "TERSEDIA", "Audio Drill", "Latihan listening dari Chapter aktif.", "10 soal  hasil langsung", `${base}/audio${query}`],
    ["-", "TERSEDIA", "Reading Drill", "Bacaan pendek dengan penjelasan jawaban.", "8 soal  fokus Dokkai", `${base}/reading${query}`],
    ["c", "TERSEDIA", "Checkpoint Retry", "Ulangi checkpoint sesuai attempt rule Chapter.", "Nilai terbaru tersimpan", `${base}/checkpoint${query}`],
  ];
  return <div className="supporting-shell student-shell"><StudentNavigation membership="sensei" current="supporting" /><main className="supporting-main practice-page"><header className="supporting-header"><p className="dash-kicker">LATIHAN HARIAN  BELAJAR DENGAN SENSEI</p><h1>Latihan singkat berdasarkan progresmu</h1><p>Aktivitas harian terpisah dari Try Out. Soal latihan dapat memuat gambar yang diunggah Admin.</p><span className="supporting-badge practice-active">AKTIF</span></header><section className="practice-recommendation"><div><p className="dash-kicker">REKOMENDASI HARI INI</p><h2>Perkuat Chapter 4 dalam 15-20 menit</h2><p>Urutan latihan dibuat dari kesalahan terakhir, confidence flashcard, dan checkpoint yang perlu diulang.</p><div><Link className="button button-primary" href={`${base}/flashcards${query}`}>Mulai Rekomendasi</Link><Link className="button button-dark" href={`/tryout${query}`}>Buka Daftar Try Out</Link></div></div><div className="practice-metrics">{[["4 aktivitas","Target harian"],["12 hari","Hari beruntun"],["18","Selesai minggu ini"],["82%","Akurasi"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="practice-section-head"><p className="dash-kicker">PILIH MODE</p><h2>Latihan Harian</h2><p>Pilih aktivitas singkat tanpa masuk ke alur Try Out.</p></section><section className="practice-mode-grid">{modes.map(([icon,status,title,description,meta,href]) => <article key={title}><span className="supporting-icon" aria-hidden="true">{icon}</span><small>{status}</small><h2>{title}</h2><p>{description}</p><b>{meta}</b><Link href={href}>Buka +</Link></article>)}</section><section className="practice-history"><p className="dash-kicker">RIWAYAT HARIAN</p><h2>Aktivitas terakhir</h2><p>Riwayat latihan tetap terpisah dari hasil Try Out.</p><div><span>Hari ini  Flashcard Review  86% akurasi</span><span>Kemarin  Audio Drill  8/10 benar</span><span>2 hari lalu  Reading Drill  7/8 benar</span></div></section></main></div>;
}
