import { StudentNavigation } from "@/components/student-navigation";
import { supportingData, type SupportingKind } from "@/lib/supporting-mock";
import Link from "next/link";
import { useState } from "react";

export function SupportingScreen({ kind, membership }: { kind: SupportingKind; membership: "free" | "lms" | "sensei" }) {
  const data = supportingData[kind];
  if (kind === "practice" && membership !== "free") return <PaidPractice membership={membership} />;
  if (kind === "library") return <LibraryScreen membership={membership} />;
  if (kind === "progress") return <ProgressScreen membership={membership} />;
  if (kind === "leaderboard") return <LeaderboardScreen membership={membership} />;
  if (kind === "certificate") return <CertificateScreen membership={membership} />;
  if (kind === "community") return <CommunityScreen membership={membership} />;
  if (kind === "notifications") return <NotificationScreen membership={membership} />;
  if (kind === "profile") return <ProfileScreen membership={membership} />;
  if (kind === "renewal") return <RenewalScreen membership={membership} />;
  if (kind === "createPost") return <CreatePostScreen membership={membership} />;
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="supporting" /><main className="supporting-main"><header className="supporting-header"><p className="dash-kicker">{data.eyebrow}</p><h1>{data.title}</h1><p>{data.description}</p>{data.locked && <span className="supporting-badge">TERBATAS</span>}</header><section className="supporting-grid">{data.cards.map((card) => <article className="supporting-card" key={card.title}><span className="supporting-icon" aria-hidden="true">{card.icon}</span><div><span className="supporting-status">{card.status}</span><h2>{card.title}</h2><p>{card.description}</p></div>{card.href ? <Link className="supporting-action" href={`${card.href}?membership=${membership}`}>{card.action ?? "Buka"} +</Link> : <span className="supporting-action disabled" aria-disabled="true">{card.action ?? "Tersedia"}</span>}</article>)}</section>{data.notice && <aside className="supporting-notice"><strong>{data.notice.title}</strong><p>{data.notice.description}</p></aside>}</main></div>;
}

function ProfileScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const query = `?membership=${membership}`;
  const membershipCopy = membership === "free" ? "Free Member" : "Belajar Mandiri";
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="profile" /><main className="supporting-main profile-page"><header className="supporting-header"><p className="dash-kicker">AKUN &amp; MEMBERSHIP</p><h1>Profil dan status belajarmu</h1><p>Kelola informasi akun, membership, sertifikat, dan preferensi.</p></header><section className="profile-identity"><span>H</span><div><h2>Hilmi</h2><p>hilmi.student@example.com</p><b>Level N4</b></div></section><section className="profile-membership"><div><p className="dash-kicker">STATUS MEMBERSHIP</p><h2>{membershipCopy}</h2><p>Periode akses dan tanggal akhir berasal dari backend.</p></div><Link className="button button-primary" href={`/renewal${query}`}>Perpanjang Membership</Link></section><section className="profile-stats">{[["65%","Progres N4"],["450","Kanji dikuasai"],["12","Hari beruntun"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><section className="profile-certificates"><h2>Sertifikat</h2><div><Link href={`/certificate${query}`}><span>Diterbitkan</span><strong>Sertifikat N5</strong></Link><article><span>Belum Memenuhi</span><strong>Sertifikat N4</strong></article></div></section><section className="profile-settings"><h2>Pengaturan akun</h2><div>{[["人","Edit Profil","Nama, WhatsApp, dan preferensi belajar."],["鍵","Ganti Kata Sandi","Perbarui keamanan akun."],["知","Notifikasi","Atur pengingat belajar dan informasi kelas."]].map(([icon,title,description]) => title === "Notifikasi" ? <Link href={`/notifications${query}`} key={title}><span>{icon}</span><div><strong>{title}</strong><small>{description}</small></div></Link> : <article key={title}><span>{icon}</span><div><strong>{title}</strong><small>{description}</small></div></article>)}</div></section><section className="profile-referral"><p className="dash-kicker">REFERRAL &amp; DISKON</p><h2>Kode referral saya</h2><strong>HIRU-HILMI</strong><p>Teman mendapat diskon. Reward milikmu aktif setelah invoice teman diverifikasi Admin.</p><div><span>1 reward diskon tersedia<small>Nilai &amp; masa berlaku dari backend</small></span><button type="button" disabled>Salin Kode</button><button type="button" disabled>Bagikan</button><Link href={`/renewal${query}`}>Gunakan</Link></div></section></main></div>;
}

function RenewalScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [plan, setPlan] = useState<"lms" | "sensei">("lms");
  const [rewardApplied, setRewardApplied] = useState(false);
  const query = `?membership=${membership}`;
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="profile" /><main className="supporting-main renewal-page"><header className="supporting-header"><p className="dash-kicker">MEMBERSHIP RENEWAL</p><h1>Lanjutkan akses tanpa kehilangan progres</h1><p>Harga dan periode baru tampil setelah plan dipilih; data berasal dari konfigurasi admin.</p></header><section className="renewal-current"><span>Membership Aktif</span><h2>Belajar Mandiri • N4</h2><p>Tanggal berakhir dan sisa hari ditampilkan dari backend. Progres tetap tersimpan setelah renewal.</p></section><section className="renewal-plans"><h2>Pilih plan lanjutan</h2><div><button className={plan === "lms" ? "active" : ""} type="button" onClick={() => setPlan("lms")}><small>LMS</small><strong>Belajar Mandiri</strong><span>Journey penuh, try out, review, sertifikat, dan community write.</span><b>Harga dinamis setelah pilihan</b></button><button className={plan === "sensei" ? "active" : ""} type="button" onClick={() => setPlan("sensei")}><small>{membership === "sensei" ? "SENSEI" : "LMS + Zoom"}</small><strong>Belajar dengan Sensei</strong><span>Semua LMS ditambah cohort, jadwal Zoom, Sensei, dan replay.</span><b>Harga dinamis setelah pilihan</b></button></div></section><section className="renewal-reward"><p className="dash-kicker">REWARD REFERRAL TERSEDIA</p><h2>Gunakan reward diskon pada invoice renewal berikutnya</h2><p>Nilai, batas penggunaan, dan masa berlaku dihitung backend.</p><button type="button" aria-pressed={rewardApplied} onClick={() => setRewardApplied(true)}>{rewardApplied ? "Reward Diterapkan" : "Gunakan Reward"}</button></section><section className="renewal-summary"><p className="dash-kicker">RINGKASAN RENEWAL</p><h2>{plan === "lms" ? "Belajar Mandiri" : "Belajar dengan Sensei"} • periode baru</h2><p>{rewardApplied && "Reward referral diterapkan. "}Nominal dan tanggal aktif baru mengikuti pilihan dan verifikasi invoice.</p><button className="button button-primary disabled" type="button" aria-disabled="true">Buat Invoice &amp; Buka WhatsApp</button></section><aside className="renewal-announcement"><strong>Pengumuman</strong><p>Membership aktif setelah pembayaran via WhatsApp dan invoice diverifikasi Admin.</p></aside><Link className="sensei-back" href={`/profile${query}`}>← Kembali ke Profil</Link></main></div>;
}

function NotificationScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [filter, setFilter] = useState("Semua");
  const [allRead, setAllRead] = useState(false);
  const [page, setPage] = useState(1);
  const query = `?membership=${membership}`;
  const third = membership === "sensei" ? { icon: "再", category: "Kelas", title: "Replay kelas sudah dipublikasikan", description: "Replay dapat ditonton selama entitlement aktif.", action: "Buka Replay", href: `/replay${query}`, isRead: false } : membership === "lms" ? { icon: "再", category: "Kelas", title: "Feedback materi sudah diperbarui", description: "Perubahan feedback mengikuti proses review tim akademik.", action: "Buka Feedback", href: undefined, isRead: false } : { icon: "再", category: "Kelas", title: "Progress chapter diperbarui", description: "Perubahan progress mengikuti aktivitas dan data backend.", action: "Buka Progress", href: `/progress${query}`, isRead: false };
  const today = [
    { icon: "章", category: "Belajar", title: "Materi Chapter 4 tersedia", description: "Lanjutkan video, modul, dan latihan pada journey aktif.", action: "Buka Chapter", href: `/learn/n4/${membership === "free" ? "chapter-1" : "chapter-4"}${query}`, isRead: false },
    { icon: "時", category: "Kelas", title: "Pengingat sesi Zoom", description: "Jadwal, Sensei, dan link mengikuti konfigurasi admin.", action: "Lihat Jadwal", href: membership === "sensei" ? `/schedule${query}` : undefined, isRead: false },
    third,
  ];
  const previous = [
    { icon: "火", category: "Achievement", title: "Achievement baru terbuka", description: "Streak belajar berhasil mencapai milestone baru.", action: "Lihat Achievement", href: `/progress${query}`, isRead: true },
    { icon: "期", category: "Akun", title: "Periode membership akan berakhir", description: "Tanggal dan opsi renewal mengikuti data backend.", action: "Lihat Membership", href: `/profile${query}`, isRead: true },
    { icon: "証", category: "Achievement", title: "Sertifikat digital tersedia", description: "Sertifikat dapat dilihat dan diunduh dari Certificate Center.", action: "Buka Sertifikat", href: membership === "free" ? undefined : `/certificate${query}`, isRead: true },
  ];
  const matches = (item: { category: string; isRead?: boolean }) => {
    if (filter === "Semua") return true;
    if (filter === "Belum Dibaca") return !allRead && !item.isRead;
    if (filter === "Akun") return item.category === "Akun";
    return item.category === filter;
  };
  const visibleToday = today.filter(matches);
  const visiblePrevious = previous.filter(matches);
  const renderItem = (item: typeof today[number]) => <article className={allRead || item.isRead ? "read" : "unread"} key={item.title}><span className="notification-icon">{item.icon}</span><div><small>{item.category} • Waktu dari backend</small><h2>{item.title}</h2><p>{item.description}</p></div>{item.href ? <Link href={item.href}>{item.action}</Link> : <span className="notification-locked" aria-disabled="true">{item.action}</span>}</article>;
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="notifications" /><main className="supporting-main notification-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">NOTIFICATION CENTER</p><h1>Informasi penting tanpa mengganggu fokus</h1><p>Notifikasi, status baca, trigger, waktu, dan delivery berasal dari backend serta preference akun.</p></header><Link href={`/profile${query}`}>Profil</Link></div><div className="notification-toolbar"><div>{["Semua","Belum Dibaca","Belajar","Kelas","Akun"].map((item) => <button className={filter === item ? "active" : ""} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><button type="button" onClick={() => setAllRead(true)}>Tandai Semua Dibaca</button></div>{visibleToday.length || visiblePrevious.length ? <><section className="notification-group"><h2>Hari ini</h2>{visibleToday.map(renderItem)}</section><section className="notification-group"><h2>Sebelumnya</h2>{visiblePrevious.map(renderItem)}</section></> : <section className="library-empty"><h2>Tidak ada notifikasi</h2><p>Tidak ada data fixture untuk filter ini.</p></section>}<div className="notification-pagination"><span>Menampilkan 1–20 dari 148 data</span><nav aria-label="Pagination">{["‹","1","2","3","…","8","›"].map((item, index) => <button className={String(page) === item ? "active" : ""} type="button" onClick={() => { if (item === "‹") setPage((value) => Math.max(1, value - 1)); else if (item === "›") setPage((value) => Math.min(8, value + 1)); else { const value = Number(item); if (value) setPage(value); } }} key={`${item}-${index}`}>{item}</button>)}</nav></div><section className="notification-preferences"><header><h2>Preferensi notifikasi</h2><p>Channel dan kategori mengikuti pengaturan akun.</p></header><div>{[["知","In-App","Pengumuman dan aktivitas aplikasi.","Aktif"],["郵","Email","Kelas, akun, dan transaksi.","Aktif"],["章","Belajar","Journey, latihan, dan achievement.","Aktif"],["話","Community","Balasan dan aktivitas thread.","Opsional"],["営","Promosi","Konten marketing opsional.","Off"]].map(([icon,title,description,state]) => <article key={title}><span>{icon}</span><div><strong>{title}</strong><small>{description}</small></div><b>{state}</b></article>)}</div></section><aside className="notification-announcement"><strong>Pengumuman</strong><p>Notifikasi transaksi dan keamanan tertentu tetap dikirim sesuai kebutuhan sistem.</p></aside></main></div>;
}

function CertificateScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const query = `?membership=${membership}`;
  if (membership === "free") return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="certificate" /><main className="supporting-main"><section className="sensei-status-panel"><p className="dash-kicker">AKSES PREMIUM</p><h1>Akses ini belum aktif pada Free Member</h1><p>Sertifikat tersedia sesuai membership dan eligibility yang telah diverifikasi.</p><div className="status-actions"><Link className="button button-primary" href={`/renewal${query}`}>Lihat Membership</Link><Link className="button button-secondary" href={`/dashboard${query}`}>Kembali Dashboard</Link></div></section></main></div>;
  const certificates = [
    { icon: "証", title: "Sertifikat JLPT N5", program: "Program JLPT N5", recipient: "Member •••1", status: "Diterbitkan", href: `/certificate/n5${query}`, action: "Lihat Sertifikat", available: true },
    { icon: "鍵", title: "Sertifikat belum tersedia", program: "Sertifikat JLPT N4", status: "Eligible • Pending", action: "Lihat Kriteria", href: `/certificate/n4${query}`, available: false },
    { icon: "鍵", title: "Sertifikat belum tersedia", program: "Sertifikat JLPT N3", status: "Belum Eligible", action: "Lihat Kriteria", href: `/certificate/n3${query}`, available: false },
  ];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="certificate" /><main className="supporting-main certificate-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">CERTIFICATE CENTER</p><h1>Sertifikat digital dari milestone yang tervalidasi</h1><p>Eligibility, issuance, download, dan status sertifikat berasal dari backend. Scope menggunakan sertifikat digital saja.</p></header><Link href={`/profile${query}`}>Profil</Link></div><section className="certificate-summary"><p className="dash-kicker">DIGITAL CREDENTIALS</p><h2>Satu sertifikat telah diterbitkan</h2><p>Jumlah, program, dan eligibility mengikuti progres serta assessment yang valid.</p><div className="certificate-flow"><span>Selesaikan journey</span><span>Penuhi assessment</span><span>Sertifikat terbit</span><span>Download / share</span></div></section><section className="certificate-grid">{certificates.map((item, index) => <article key={index} className={item.available ? "available" : "locked"}><span aria-hidden="true">{item.icon}</span><small>{item.available ? "DIGITAL" : ""}</small><h2>{item.title}</h2><p>{item.recipient ? `${item.recipient} • ` : ""}{item.program}</p><b>{item.status}</b>{item.href ? <Link href={item.href}>{item.action} →</Link> : <button className="disabled" type="button" aria-disabled="true">{item.action} →</button>}</article>)}</section><aside className="certificate-notice"><strong>Pengumuman</strong><p>Sertifikat diterbitkan otomatis atau melalui review setelah semua kriteria backend terpenuhi.</p></aside></main></div>;
}

function CommunityScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [search, setSearch] = useState("");
  const query = `?membership=${membership}`;
  const isSensei = membership === "sensei";
  const canWrite = membership !== "free";
  const posts = [
    { id: "post-1", tag: isSensei ? "Tanya Sensei" : "Diskusi Member", title: "Perbedaan penggunaan に dan で untuk tempat?", summary: "Pertanyaan grammar untuk memahami konteks aktivitas dan lokasi.", href: `/community/post-1${query}` },
    { id: "post-2", tag: "Semua Akses", title: "Pengingat jadwal dan materi minggu ini", summary: "Info dari Hiru untuk pembelajar.", href: undefined },
    { id: "post-3", tag: "Diskusi Member", title: "Tips menjaga konsistensi flashcard N4", summary: "Forum diskusi dengan sesama pembelajar.", href: undefined },
  ];
  const visible = posts.filter((p) => p.title.toLowerCase().includes(search.toLowerCase()));

  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="community" /><main className="supporting-main community-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">FORUM KOMUNITAS</p><h1>Berdiskusi, bertanya, dan berbagi perjalanan belajar</h1><p>{isSensei ? "Belajar dengan Sensei dapat membuat post, membalas komentar, dan menggunakan Tanya Sensei sesuai entitlement." : canWrite ? "Belajar Mandiri dapat membuat post, membalas komentar, dan melaporkan konten sesuai entitlement." : "Free Member dapat membaca. Post, komentar, dan Tanya Sensei tetap terkunci sesuai entitlement."}</p></header>{canWrite && <Link className="button button-dark" href={`/community/create${query}`}>Buat Postingan</Link>}</div><section className="community-access-grid">{[["Tanya Sensei", "Pertanyaan untuk pengajar pada plan Belajar dengan Sensei."],["Diskusi Member", "Forum diskusi dengan sesama pembelajar."],["Info dari Hiru", "Pengumuman, event, dan informasi akademi."],["Kerja ke Jepang", "Informasi karier dan persiapan profesional."]].map(([title, desc]) => <article key={title}><strong>{title}</strong><p>{desc}</p></article>)}</section><section className="community-feed-head"><div><p className="dash-kicker">Diskusi terbaru</p><small>Urutan dan engagement berasal dari data backend.</small></div><label className="library-search"><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari diskusi atau topik" /></label></section><section className="community-list">{visible.map((post) => <article key={post.id}><div><span>{post.tag}</span><h2>{post.title}</h2><p>{post.summary}</p></div>{post.href ? <Link className="button button-primary" href={post.href}>Buka</Link> : <span className="button button-secondary disabled" aria-disabled="true">Belum tersedia</span>}</article>)}</section></main></div>;
}

function CreatePostScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [submitted, setSubmitted] = useState(false);
  const query = `?membership=${membership}`;
  if (membership === "free") return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="community" /><main className="supporting-main"><section className="sensei-status-panel"><p className="dash-kicker">COMMUNITY • READ ONLY</p><h1>Postingan baru belum tersedia</h1><p>Free Member dapat membaca thread. Hak membuat postingan mengikuti entitlement.</p><Link className="button button-secondary" href={`/community${query}`}>Kembali ke Community</Link></section></main></div>;
  if (submitted) return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="community" /><main className="supporting-main"><section className="sensei-status-panel"><p className="dash-kicker">COMMUNITY</p><h1>Postingan siap ditinjau</h1><p>Postingan fixture mengikuti aturan komunitas dan dapat melalui moderasi.</p><Link className="button button-primary" href={`/community${query}`}>Kembali ke Community</Link></section></main></div>;
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="community" /><main className="supporting-main"><header className="supporting-header"><p className="dash-kicker">BUAT POSTINGAN</p><h1>Bagikan pertanyaan atau pengalaman belajar</h1></header><form className="form-stack" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label><span>Kategori</span><select><option>Diskusi Member</option></select></label><label><span>Judul</span><input required placeholder="Tulis judul postingan" /><small>Teks bantuan opsional</small></label><label><span>Ringkasan</span><textarea required /></label><p>Postingan mengikuti aturan komunitas dan dapat melalui moderasi.</p><div className="button-group"><button type="submit" className="button button-primary">Publikasikan</button><Link href={`/community${query}`} className="button button-secondary">Batal</Link></div></form></main></div>;
}

function ProgressScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const query = `?membership=${membership}`;
  const milestones = [["o","Fondasi N4","Chapter awal dan checkpoint","Selesai"],["o","Rutinitas Harian","Video, modul, dan latihan","Selesai"],["03","Pola Kalimat","Chapter aktif","Aktif"],["04","Try Out N4","Tersedia setelah journey","Terkunci"],["05","Sertifikat N4","Mengikuti eligibility","Terkunci"]];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="progress" /><main className="supporting-main progress-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">PROGRES &amp; ACHIEVEMENT</p><h1>Rayakan progres tanpa kehilangan fokus</h1><p>Progress, streak, mastery, dan achievement dihitung dari journey serta aktivitas backend.</p></header><Link href={`/profile${query}`}>Profil</Link></div><section className="progress-summary"><div><p className="dash-kicker">MEMBER  LEVEL N4</p><h2>Perjalanan belajar terus bertumbuh</h2><p>Persentase dan milestone mengikuti completion serta assessment yang valid.</p><span>12 Hari Streak</span></div><div className="progress-stats">{[["65%","Journey N4"],["450","Kanji mastered"],["?","Latihan selesai"],["?","Try Out terbaik"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="progress-milestones"><h2>Milestone journey</h2>{milestones.map(([number,title,description,status]) => <article key={title}><span>{number}</span><div><strong>{title}</strong><small>{description}</small></div><b>{status}</b></article>)}</section><section className="progress-achievements"><div className="progress-tabs"><button className="active" type="button">Achievement</button><Link href={`/leaderboard${query}`}>Leaderboard</Link></div><div>{[["?","Streak 7 Hari","Belajar konsisten selama tujuh hari.","Terbuka"],["o-","Flashcard Master","Menyelesaikan target flashcard.","Terbuka"],["c","Try Out Finisher","Menyelesaikan Try Out pertama.","Belum terbuka"],["\"","Certificate Ready","Memenuhi eligibility sertifikat.","Belum terbuka"]].map(([icon,title,description,status]) => <article key={title}><span>{icon}</span><h2>{title}</h2><p>{description}</p><b>{status}</b></article>)}</div></section></main></div>;
}

function LeaderboardScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [period, setPeriod] = useState("Mingguan");
  const query = `?membership=${membership}`;
  const rows = [["04","Member 4","Member community","+ 2"],["05","Member 5","Member community","?"],["06","Member 6","Member community","+ 1"],["07","Kamu","Posisimu saat ini","+ 3"],["08","Member 8","Member community","?"]];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="leaderboard" /><main className="supporting-main leaderboard-page"><div className="progress-title-row"><header className="supporting-header"><p className="dash-kicker">LEADERBOARD</p><h1>Bandingkan konsistensi, bukan tekanan</h1><p>Poin, periode, cohort, rank, dan movement berasal dari backend serta dapat menggunakan nama samaran.</p></header><Link href={`/progress${query}`}>Progres</Link></div><div className="leaderboard-filters">{["Mingguan","Bulanan","N4","Cohort","Semua Member"].map((filter) => <button className={period === filter ? "active" : ""} type="button" onClick={() => setPeriod(filter)} key={filter}>{filter}</button>)}</div><section className="leaderboard-podium">{[["#02","Member 2"],["#01","Member 1"],["#03","Member 3"]].map(([rank,name]) => <article className={rank === "#01" ? "winner" : ""} key={rank}><strong>{rank}</strong><h2>{name}</h2><span>Poin ?</span></article>)}</section><section className="leaderboard-list">{rows.map(([rank,name,meta,movement]) => <article className={name === "Kamu" ? "current" : ""} key={rank}><strong>{rank}</strong><div><h2>{name}</h2><span>{meta}</span></div><div><b>Poin ?</b><small>Poin dinamis</small></div><i>{movement}</i></article>)}</section><aside className="leaderboard-notice"><strong>Pengumuman</strong><p>Leaderboard dapat menggunakan nama samaran dan hanya menampilkan aktivitas yang diizinkan.</p></aside></main></div>;
}

function LibraryScreen({ membership }: { membership: "free" | "lms" | "sensei" }) {
  const [search, setSearch] = useState("");
  const [level, setLevel] = useState("Semua");
  const [type, setType] = useState("Semua");
  const [locked, setLocked] = useState(false);
  const materials = [
    { icon: "-", type: "Tata Bahasa", title: "Pola Kalimat Sehari-hari", description: "Modul Chapter 4 yang terakhir dibuka.", status: "Tersimpan", href: `/learn/n4/${membership === "free" ? "chapter-1" : "chapter-4"}/grammar?membership=${membership}` },
    { icon: "", type: "Kanji", title: "Keadaan, Waktu & Aktivitas", description: "Kanji chapter dengan bookmark dan catatan.", status: "Tersedia", href: `/learn/n4/${membership === "free" ? "chapter-1" : "chapter-4"}/kanji?membership=${membership}` },
    { icon: "AUDIO", type: "Audio", title: "Simulasi Choukai N4", description: "Akses audio lengkap mengikuti membership.", status: "Terkunci" },
  ];
  const visible = materials.filter((item) => (type === "Semua" || item.type === type) && item.title.toLowerCase().includes(search.toLowerCase()) && (level === "Semua" || level === "N4"));
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="library" /><main className="supporting-main library-page"><header className="supporting-header"><p className="dash-kicker">PERPUSTAKAAN MATERI</p><h1>Temukan kembali materi dari seluruh journey</h1><p>Akses material mengikuti level dan entitlement membership.</p></header><label className="library-search"><span aria-hidden="true">O </span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari materi, tata bahasa, kanji, atau audio" /></label><div className="library-filters">{["Semua","N5","N4","N3","SSW","Interview"].map((item) => <button className={level === item ? "active" : ""} type="button" onClick={() => setLevel(item)} key={item}>{item}</button>)}</div><div className="library-filters types">{["Semua","Tata Bahasa","Kanji","Kosakata","Audio","Reading"].map((item) => <button className={type === item ? "active" : ""} type="button" onClick={() => setType(item)} key={item}>{item}</button>)}</div>{visible.length ? <><section className="library-section-head"><h2>Rekomendasi N4</h2></section><section className="library-material-grid">{visible.map((item) => <article key={item.title}><span aria-hidden="true">{item.icon}</span><small>{item.type}</small><h2>{item.title}</h2><p>{item.description}</p><b>{item.status}</b>{item.href ? <Link aria-label={`${item.type}: ${item.title}`} href={item.href}>Buka materi</Link> : <button type="button" onClick={() => setLocked(true)} aria-label={`${item.type}: ${item.title}`}>Lihat status</button>}</article>)}</section><section className="library-recent"><p className="dash-kicker">Baru dibuka</p>{[["z","Flashcard Chapter 4","Kosakata"],["-","Reading Aktivitas Harian","Reading"],["c","Review Try Out 1","Try Out"]].map(([icon,title,meta]) => <div key={title}><span>{icon}</span><strong>{title}</strong><small>{meta}</small></div>)}</section></> : <section className="library-empty"><p className="dash-kicker">LIBRARY  EMPTY</p><h2>Belum ada materi pada filter ini</h2><span>c</span><p>Ubah level, kategori, atau kata kunci untuk menemukan materi yang tersedia.</p><small>Filter dapat direset  Entitlement tetap diperiksa  Data berasal dari backend</small><button type="button" onClick={() => { setSearch(""); setLevel("Semua"); setType("Semua"); }}>Reset Filter</button></section>}{locked && <div className="library-locked" role="dialog" aria-modal="true" aria-labelledby="library-locked-title"><section><p className="dash-kicker">CONTENT  LOCKED</p><h2 id="library-locked-title">Materi belum termasuk dalam aksesmu</h2><span></span><p>Akses mengikuti level dan plan membership. Progress yang sudah tersimpan tidak hilang.</p><small>Plan gated  Backend authority  Renewal atau upgrade tersedia</small><div><Link href={`/renewal?membership=${membership}`}>Lihat Membership</Link><button type="button" onClick={() => setLocked(false)}>Kembali ke Library</button></div></section></div>}</main></div>;
}

function PaidPractice({ membership }: { membership: "lms" | "sensei" }) {
  const base = "/learn/n4/chapter-4";
  const query = `?membership=${membership}`;
  const modes = [
    ["o-", "REKOMENDASI", "Flashcard Review", "Ulangi kosakata dan pola dengan confidence state.", "5-10 menit  deck level aktif", `${base}/flashcards${query}`],
    ["AUDIO", "TERSEDIA", "Audio Drill", "Latihan listening dari Chapter aktif.", "10 soal  hasil langsung", `${base}/audio${query}`],
    ["-", "TERSEDIA", "Reading Drill", "Bacaan pendek dengan penjelasan jawaban.", "8 soal  fokus Dokkai", `${base}/reading${query}`],
    ["c", "TERSEDIA", "Checkpoint Retry", "Ulangi checkpoint sesuai attempt rule Chapter.", "Nilai terbaru tersimpan", `${base}/checkpoint${query}`],
  ];
  return <div className="supporting-shell student-shell"><StudentNavigation membership={membership} current="supporting" /><main className="supporting-main practice-page"><header className="supporting-header"><p className="dash-kicker">LATIHAN HARIAN • {membership === "sensei" ? "BELAJAR DENGAN SENSEI" : "BELAJAR MANDIRI"}</p><h1>Latihan singkat berdasarkan progresmu</h1><p>Aktivitas harian terpisah dari Try Out. Soal latihan dapat memuat gambar yang diunggah Admin.</p><span className="supporting-badge practice-active">AKTIF</span></header><section className="practice-recommendation"><div><p className="dash-kicker">REKOMENDASI HARI INI</p><h2>Perkuat Chapter 4 dalam 15-20 menit</h2><p>Urutan latihan dibuat dari kesalahan terakhir, confidence flashcard, dan checkpoint yang perlu diulang.</p><div><Link className="button button-primary" href={`${base}/flashcards${query}`}>Mulai Rekomendasi</Link><Link className="button button-dark" href={`/tryout${query}`}>Buka Daftar Try Out</Link></div></div><div className="practice-metrics">{[["4 aktivitas","Target harian"],["12 hari","Hari beruntun"],["18","Selesai minggu ini"],["82%","Akurasi"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="practice-section-head"><p className="dash-kicker">PILIH MODE</p><h2>Latihan Harian</h2><p>Pilih aktivitas singkat tanpa masuk ke alur Try Out.</p></section><section className="practice-mode-grid">{modes.map(([icon,status,title,description,meta,href]) => <article key={title}><span className="supporting-icon" aria-hidden="true">{icon}</span><small>{status}</small><h2>{title}</h2><p>{description}</p><b>{meta}</b><Link href={href}>Buka +</Link></article>)}</section><section className="practice-history"><p className="dash-kicker">RIWAYAT HARIAN</p><h2>Aktivitas terakhir</h2><p>Riwayat latihan tetap terpisah dari hasil Try Out.</p><div><span>Hari ini  Flashcard Review  86% akurasi</span><span>Kemarin  Audio Drill  8/10 benar</span><span>2 hari lalu  Reading Drill  7/8 benar</span></div></section></main></div>;
}
