"use client";

import Link from "next/link";
import { useState } from "react";
import type { LearningData } from "@/lib/learning-mock";

export function VideoLesson({ data }: { data: LearningData }) {
  const [completed, setCompleted] = useState(false);
  const [tab, setTab] = useState<"summary" | "transcript" | "notes">("summary");
  const query = `?membership=${data.membership}`;
  return <>
    <header className="learning-page-head"><p className="dash-kicker">{data.level} â€¢ CHAPTER {data.chapterNumber} â€¢ VIDEO</p><h1>{data.videoTitle}</h1><p>Tonton video, tandai selesai, lalu lanjutkan ke modul berikutnya.</p></header>
    <div className="video-learning-layout"><div className="video-learning-main"><section className="video-card"><div className="video-surface"><span aria-hidden="true">â–¶</span><strong>Mulai video</strong><small>YouTube â€¢ lazy-loaded</small></div><p>Durasi dan sumber video mengikuti konfigurasi konten.</p>{completed ? <Link className="button button-primary" href={`/learn/${data.levelSlug}/${data.chapterSlug}/grammar${query}`}>Lanjut Modul Tata Bahasa</Link> : <button type="button" onClick={() => setCompleted(true)}>Tandai Selesai</button>}</section><div className="video-tabs" role="tablist" aria-label="Materi video"><button type="button" role="tab" aria-selected={tab === "summary"} onClick={() => setTab("summary")}>Ringkasan</button><button type="button" role="tab" aria-selected={tab === "transcript"} onClick={() => setTab("transcript")}>Transkrip</button><button type="button" role="tab" aria-selected={tab === "notes"} onClick={() => setTab("notes")}>Catatan</button></div>{tab === "summary" ? <section className="video-summary"><h2>Ringkasan materi</h2><p>Video membahas pola kalimat yang digunakan untuk menjelaskan rutinitas, kebiasaan, dan aktivitas sehari-hari. Gunakan transkrip dan catatan untuk meninjau kembali contoh penting.</p><div>{[["æ™‚", "Waktu"], ["ç¿’", "Kebiasaan"], ["å‹•", "Aktivitas"]].map(([glyph, label]) => <article key={label}><span aria-hidden="true">{glyph}</span><strong>{label}</strong></article>)}</div></section> : <section className="video-empty-tab"><h2>{tab === "transcript" ? "Transkrip" : "Catatan"}</h2><p>Konten mengikuti konfigurasi materi.</p></section>}</div><aside className="video-chapter-rail"><h2>Isi Chapter {data.chapterNumber}</h2><ol>{data.activities.map((activity) => <li className={activity.key === "video" ? "active" : ""} key={activity.key}><span>{activity.order}</span><strong>{activity.railTitle}</strong></li>)}</ol><div className="dash-progress-ring" style={{ position: "relative", width: "48px", height: "48px", margin: "16px 0" }}><svg viewBox="0 0 36 36" className="dash-ring-svg"><path className="dash-ring-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" /><path className="dash-ring-fill" strokeDasharray="28, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" /></svg><div className="dash-ring-value" style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "12px" }}><strong>28%</strong></div></div><Link href={`/learn/${data.levelSlug}/${data.chapterSlug}${query}`}>Kembali ke Chapter</Link></aside></div>
  </>;
}

