"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Cohort={id:string;name:string;level:string;status:"Active"|"Planned"|"Completed"|"Draft";sensei:string};
const fixtures:Cohort[]=[{id:"c1",name:"N4 • Cohort Aktif",level:"N4",status:"Active",sensei:"Sensei •••1"},{id:"c2",name:"N4 • Cohort Berikutnya",level:"N4",status:"Planned",sensei:"Sensei •••2"},{id:"c3",name:"N5 • Cohort Dasar",level:"N5",status:"Active",sensei:"Sensei •••2"},{id:"c4",name:"N4 • Cohort Sebelumnya",level:"N4",status:"Completed",sensei:"Sensei •••1"},{id:"c5",name:"N3 • Cohort Draft",level:"N3",status:"Draft",sensei:"Belum assigned"}];
type Dialog="cohort"|"schedule"|"upload"|"replay"|null;
export default function CohortsPage(){
 const [items,setItems]=useState(fixtures),[selectedId,setSelectedId]=useState("c1"),[query,setQuery]=useState(""),[filter,setFilter]=useState("Semua"),[dialog,setDialog]=useState<Dialog>(null),[program,setProgram]=useState("N4 • Belajar dengan Sensei"),[period,setPeriod]=useState("Tanggal dari backend"),[capacity,setCapacity]=useState("Aturan dari admin"),[sensei,setSensei]=useState("Sensei •••1"),[sessionName,setSessionName]=useState("Chapter 4 — Kelas bersama Sensei"),[dateTime,setDateTime]=useState("Tanggal dan waktu dari Admin"),[platform,setPlatform]=useState("Zoom / Meet / platform eksternal"),[classLink,setClassLink]=useState("URL dinamis dari Admin"),[sessionStatus,setSessionStatus]=useState("Draft"),[replayStatus,setReplayStatus]=useState<"Belum ada"|"Draft">("Belum ada"),[newMode,setNewMode]=useState(false);
 const scheduleRef=useRef<HTMLElement>(null),editorRef=useRef<HTMLElement>(null),selected=items.find((item)=>item.id===selectedId)??items[0];
 const visible=useMemo(()=>items.filter((item)=>`${item.name} Belajar dengan Sensei ${item.sensei} ${item.status}`.toLowerCase().includes(query.toLowerCase())&&(filter==="Semua"||item.status===filter||item.level===filter)),[items,query,filter]);
 function select(item:Cohort){setSelectedId(item.id);setNewMode(false);setProgram(`${item.level} • Belajar dengan Sensei`);setSensei(item.sensei);editorRef.current?.scrollIntoView({behavior:"smooth",block:"start"});}
 function create(){setNewMode(true);setProgram("N4 • Belajar dengan Sensei");setPeriod("Tanggal dari backend");setCapacity("Aturan dari admin");setSensei("Belum assigned");editorRef.current?.scrollIntoView({behavior:"smooth",block:"start"});}
 return <AdminShell current="sensei"><main className="admin-page admin-a8-page"><header className="admin-header"><div><p className="admin-kicker">ADMIN • COHORT &amp; KELAS</p><h1>Pengelolaan Cohort &amp; Kelas</h1><p>Kelola program, periode, kapasitas, siswa, Sensei, jadwal kelas, replay, dan lifecycle cohort.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={()=>scheduleRef.current?.scrollIntoView({behavior:"smooth"})}>Kalender</button><button className="button button-primary" type="button" onClick={create}>Tambah Cohort</button></div></header>
 <section className="admin-kpi-grid">{[["Cohort aktif",items.filter((item)=>item.status==="Active").length,"Cohort berjalan."],["Cohort direncanakan",items.filter((item)=>item.status==="Planned").length,"Belum dimulai."],["Siswa terdaftar","Dinamis","Student dengan entitlement."],["Peringatan kapasitas","Dinamis","Mendekati atau melebihi aturan."]].map(([label,value,meta])=><article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
 <section className="a8-toolbar"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input type="search" aria-label="Cari cohort" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Cari cohort, program, Sensei, atau status" /></label><div className="admin-filters">{["Semua","Active","Planned","Completed","N4","N5"].map((value)=><button aria-pressed={filter===value} className={filter===value?"active":""} type="button" onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div></section>
 <div className="a8-layout"><section className="a8-queue"><header><h2>Daftar cohort</h2><p>Periode, kapasitas, dan assignment tetap dinamis.</p></header>{visible.length?visible.map((item)=><button aria-pressed={selected.id===item.id&&!newMode} aria-label={`Kelola ${item.name}`} className={selected.id===item.id&&!newMode?"active":""} type="button" onClick={()=>select(item)} key={item.id}><span><strong><i className="a9-glyph">班</i>{item.name}</strong><small>Belajar dengan Sensei • {item.sensei}</small></span><span><b>Dinamis</b><small>{item.status}</small></span><em>Kelola</em></button>):<section className="a8-empty"><strong>Tidak ada cohort sesuai filter.</strong><button className="button button-secondary" type="button" onClick={()=>{setQuery("");setFilter("Semua");}}>Reset</button></section>}</section>
 <section className="a8-review" ref={editorRef}><header><div><p className="admin-kicker">{newMode?"COHORT DRAFT BARU":selected.name.toUpperCase()}</p><h2>{newMode?"Cohort baru":selected.name}</h2><p>Belajar dengan Sensei</p></div><span>{newMode?"Draft":selected.status}</span></header><div className="a8-form-grid"><label className="admin-field"><span>Program</span><select value={program} onChange={(event)=>setProgram(event.target.value)}><option>N5 • Belajar dengan Sensei</option><option>N4 • Belajar dengan Sensei</option><option>N3 • Belajar dengan Sensei</option></select></label><label className="admin-field"><span>Periode</span><input value={period} onChange={(event)=>setPeriod(event.target.value)} /></label><label className="admin-field"><span>Kapasitas</span><input value={capacity} onChange={(event)=>setCapacity(event.target.value)} /></label><label className="admin-field"><span>Sensei</span><select value={sensei} onChange={(event)=>setSensei(event.target.value)}><option>Belum assigned</option><option>Sensei •••1</option><option>Sensei •••2</option><option>Sensei •••3</option></select></label></div><div className="a11-runtime">{["Students","Sessions","Replay"].map((label)=><div key={label}><strong>—</strong><span>{label}</span></div>)}</div><section className="a11-block"><strong>ATURAN SESI</strong>{[["Jumlah sesi","Dinamis"],["Durasi sesi","Dinamis"],["Reminder","Dari konfigurasi"],["Replay visibility","Setelah publish"],["Tanya Sensei","Plan gated"]].map(([label,value])=><div className="a11-row" key={label}><b>{label}</b><span>{value}</span></div>)}</section><section className="a11-placement"><strong>PENEMPATAN SISWA</strong><p>Student dapat ditambahkan bila entitlement dan kapasitas valid.</p><div className="a8-actions"><button className="button button-primary" type="button" onClick={()=>setDialog("cohort")}>Simpan Cohort</button><Link className="button button-secondary" href="/admin/users">Kelola Student</Link><button className="button button-dark" type="button" onClick={()=>scheduleRef.current?.scrollIntoView({behavior:"smooth"})}>Kelola Jadwal</button></div></section><aside className="a8-privacy"><strong>TATA KELOLA</strong><p>Periode, kapasitas, assignment, dan perubahan lifecycle harus tervalidasi serta tercatat.</p><small>Entitlement, capacity, assignment, dan lifecycle tetap backend authority.</small></aside></section></div>
 <section className="a10-panel a11-checkpoint"><header><h2>MINI CHECKPOINT KELAS</h2><p>Evaluasi singkat per level, sesi, dan part</p></header><div><div className="a11-runtime">{[["JUMLAH CHECKPOINT","N5, N4, N3, N2"],["UNLOCK","Per sesi dan part"],["STRUKTUR","Sesi & part"],["WAKTU","Timer configurable"]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p>Mini Checkpoint khusus Belajar dengan Sensei. Struktur level → sesi → part. N1 tidak termasuk.</p><Link className="button button-primary" href="/admin/mini-checkpoint">Kelola Mini Checkpoint</Link></div></section>
 <section className="a10-panel a11-schedule" ref={scheduleRef}><header><h2>JADWAL KELAS &amp; REPLAY</h2><p>Kelola sesi cohort tanpa modul Zoom khusus. Platform, link kelas, reminder, dan replay tersimpan pada cohort.</p></header><div><div className="a11-schedule-grid"><label className="admin-field"><span>Nama Sesi</span><input value={sessionName} onChange={(event)=>setSessionName(event.target.value)} /></label><label className="admin-field"><span>Tanggal &amp; Waktu</span><input value={dateTime} onChange={(event)=>setDateTime(event.target.value)} /></label><label className="admin-field"><span>Durasi</span><input value="Dinamis per sesi" readOnly /></label><label className="admin-field"><span>Sensei</span><input value="Assignment cohort aktif" readOnly /></label><label className="admin-field"><span>Platform Kelas</span><select value={platform} onChange={(event)=>setPlatform(event.target.value)}><option>Zoom / Meet / platform eksternal</option><option>Zoom</option><option>Meet</option><option>Platform eksternal</option></select></label><label className="admin-field"><span>Link Kelas</span><input value={classLink} onChange={(event)=>setClassLink(event.target.value)} /></label><label className="admin-field"><span>Reminder</span><input value="In-app dan email" readOnly /></label><label className="admin-field"><span>Status Sesi</span><select value={sessionStatus} onChange={(event)=>setSessionStatus(event.target.value)}><option>Draft</option><option>Terjadwal</option><option>Selesai</option></select></label><label className="admin-field"><span>Link Replay</span><input value={replayStatus==="Belum ada"?"URL atau file rekaman":"Media fixture dipilih"} readOnly /></label><label className="admin-field"><span>Visibilitas</span><input value="Setelah dipublikasikan" readOnly /></label><label className="admin-field"><span>Status Replay</span><input value={replayStatus} readOnly /></label></div><p className="admin-local-feedback">Perubahan link kelas dan replay tercatat pada audit log serta hanya tersedia bagi entitlement cohort aktif. Frontend tidak menjadi authority.</p><div className="a8-actions"><button className="button button-primary" type="button" onClick={()=>setDialog("schedule")}>Simpan Jadwal</button><button className="button button-secondary" type="button" onClick={()=>{setReplayStatus("Draft");setDialog("upload");}}>Unggah Replay</button><button className="button button-dark" type="button" onClick={()=>setDialog("replay")}>Publikasikan Replay</button></div></div></section>
 {dialog&&<div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={()=>setDialog(null)} aria-label="Tutup state Cohort"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="cohort-state-title">{dialog==="cohort"&&<Result kicker="ADMIN • SIMPAN COHORT" title="Perubahan cohort berhasil disimpan" text="Program, periode, kapasitas, Sensei, aturan sesi, dan assignment telah disimpan." note="Fixture lokal saja; capacity, entitlement, backend, dan audit tidak berubah." close={()=>setDialog(null)} />}{dialog==="schedule"&&<Result kicker="ADMIN • SIMPAN JADWAL" title="Jadwal kelas berhasil disimpan" text="Cohort, Sensei, tanggal, durasi, link Zoom, agenda, dan pengingat telah disimpan." note="Fixture lokal saja; tidak ada calendar engine, meeting API, reminder, atau audit nyata." close={()=>setDialog(null)} />}{dialog==="upload"&&<Result kicker="ADMIN • UNGGAH REPLAY" title="Replay kelas berhasil diunggah" text="Rekaman, transkrip, dan materi tersimpan. Publikasi tetap menunggu validasi admin." note="Status Draft lokal saja; file, storage, metadata, Student Replay, dan audit tidak berubah." close={()=>setDialog(null)} />}{dialog==="replay"&&<><p className="admin-kicker">ADMIN • VALIDASI REPLAY</p><h2 id="cohort-state-title">Replay belum dapat dipublikasikan</h2><p>Lengkapi link kelas, rekaman, visibility, dan data sesi sebelum replay dipublikasikan.</p><ul className="a8-steps"><li>Validasi rekaman</li><li>Validasi akses</li><li>Audit publikasi</li></ul><p className="admin-local-feedback" role="alert">Upload bukan publish. Replay tetap {replayStatus}; Student Replay tidak berubah.</p><button className="button button-primary" type="button" onClick={()=>{setDialog(null);scheduleRef.current?.scrollIntoView({behavior:"smooth"});}}>Periksa Kelas</button></>}</section></div>}
 </main></AdminShell>;
}
function Result({kicker,title,text,note,close}:{kicker:string;title:string;text:string;note:string;close:()=>void}){return <section className="a4-success"><p className="admin-kicker">{kicker}</p><h2 id="cohort-state-title">{title}</h2><span aria-hidden="true">✓</span><p>{text}</p><p className="admin-local-feedback" role="status">{note}</p><button className="button button-primary" type="button" onClick={close}>Kembali ke Cohort</button></section>}
