import Link from "next/link";
import { PublicPage } from "@/components/public-shell";
import { levelCatalog, plans } from "@/lib/public-mock";

export default function ProgramPage() {
  return <PublicPage active="Program"><main className="public-main program-page">
    <section className="program-intro-card"><div className="program-intro-copy"><p className="kicker">PROGRAM & LEVEL</p><p className="program-overline">Pilih berdasarkan tujuan dan kemampuanmu</p><h1>Pilih cara belajar, lalu tentukan level N5–N1</h1><p>Semua level dapat dibeli secara bebas. Chapter di dalam level aktif tetap mengikuti urutan belajar yang terstruktur.</p><Link className="button button-dark" href="/placement">Coba Placement Test <span aria-hidden="true">→</span></Link></div><div className="program-intro-flow"><p className="kicker">ALUR MEMILIH PROGRAM</p><ol><li><strong>01</strong><div><h2>Pilih cara belajar</h2><p>Free Member, Belajar Mandiri, atau Belajar dengan Sensei.</p></div></li><li><strong>02</strong><div><h2>Pilih level N5–N1</h2><p>Semua level dapat dipilih tanpa membeli level sebelumnya.</p></div></li><li><strong>03</strong><div><h2>Lihat ringkasan</h2><p>Harga muncul setelah pilihan lengkap.</p></div></li></ol></div></section>
    <section className="public-section"><div className="public-section-head program-section-title"><span aria-hidden="true">本</span><div><p className="kicker">CARA BELAJAR</p><h2>Pilih cara belajar terlebih dahulu</h2></div></div><div className="public-cards">{plans.map((plan) => <article className={`public-card program-plan-card${plan.title === "Belajar Mandiri" ? " selected" : ""}`} key={plan.title}><div className="program-card-head"><small>CARA BELAJAR</small><span>{plan.badge}</span></div><h3>{plan.title}</h3><p>{plan.description}</p><ul>{plan.points.map((point) => <li key={point}>{point}</li>)}</ul></article>)}</div></section>
    <section className="public-section level-section"><div className="public-section-head level-section-head"><div className="program-section-title"><span aria-hidden="true">道</span><div><p className="kicker">LEVEL JOURNEY</p><h2>Pilih level N5–N1 secara bebas</h2></div></div><p>Tidak ada prerequisite pembelian antar level.</p></div><div className="public-levels">{levelCatalog.map((level) => <Link className={`public-level${level.code === "N4" ? " selected" : ""}`} href={`/program/${level.code.toLowerCase()}`} key={level.code}><div className="public-level-top"><strong>{level.code}</strong><span>{level.code === "N4" ? "Dipilih" : "Tersedia"}</span></div><small>{level.name}</small><h3>{level.title}</h3><p>{level.description}</p><ul>{level.topics.map((topic) => <li key={topic}>{topic}</li>)}</ul><footer><em>{level.code === "N4" ? "Pilihan level contoh saat ini" : "Dapat dipilih langsung tanpa prerequisite"}</em><b aria-hidden="true">→</b></footer></Link>)}</div></section>
    <aside className="program-summary"><span className="program-summary-icon" aria-hidden="true">▤</span><div><p className="kicker">RINGKASAN PILIHAN</p><h3>JLPT N4 • Belajar Mandiri</h3><p>Contoh pilihan aktif ditampilkan di bawah; level lain dapat dipilih secara independen.</p></div><Link className="button button-primary" href="/register">Lanjutkan Pendaftaran <span aria-hidden="true">→</span></Link></aside>
  </main></PublicPage>;
}
