"use client";

import { useState } from "react";
import { AdminShell } from "@/components/admin-shell";

const events=[["landing_view","Landing dibuka"],["free_trial_click","Klik Coba Gratis"],["placement_start","Placement dimulai"],["placement_complete","Placement selesai"],["plan_select","Plan dipilih"],["level_select","Level dipilih"],["sign_up","Registrasi selesai"],["referral_apply","Kode referral diterapkan"],["invoice_create","Invoice dibuat"],["payment_verified","Pembayaran diverifikasi"],["tryout_complete","Try Out selesai"],["feedback_submit","Feedback dikirim"]];
export default function AnalyticsPage(){
 const [period,setPeriod]=useState("Bulan Ini (Februari 2026)"),[exportOpen,setExportOpen]=useState(false);
 return <AdminShell current="analytics"><main className="admin-page admin-a12-page"><header className="admin-header"><div><p className="admin-kicker">ADMIN • ANALITIK &amp; GOOGLE ANALYTICS</p><h1>Analitik &amp; Google Analytics</h1><p>Pantau trafik kunjungan, pertumbuhan siswa, konversi paket belajar, dan keaktifan kelas.</p></div><div className="admin-header-actions"><label className="admin-field a12-period"><span>Periode</span><select value={period} onChange={(event)=>setPeriod(event.target.value)}><option>Bulan Ini (Februari 2026)</option><option>Bulan Lalu</option><option>Tahun Ini</option></select></label><button className="button button-primary" type="button" onClick={()=>setExportOpen(true)}>Ekspor</button></div></header>
 <section className="admin-kpi-grid">{[["Pembelajar aktif","1.284 Siswa","Total pembelajar terdaftar."],["Konversi membership","68,4%","Persentase upgrade paket."],["Learning engagement","84,2%","Tingkat penyelesaian modul harian."],["Transaksi terverifikasi","142 Invoice","Pembayaran terverifikasi bulan ini."]].map(([label,value,meta])=><article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
 <section className="a12-authority"><div><strong>GOOGLE ANALYTICS / GA4</strong><p>Traffic pengunjung, sumber kampanye iklan, dan corong akuisisi pengguna.</p></div><div><strong>SISTEM AKADEMIK</strong><p>Verifikasi transaksi, paket belajar siswa, referral reward, dan progres kelulusan.</p></div><p>Google Analytics digunakan untuk memantau trafik pengunjung dan efektivitas kampanye promosi.</p></section>
 <div className="a12-grid"><Panel title="Aktivitas belajar" text="Grafik intensitas penyelesaian aktivitas belajar harian." badge="Aktivitas Siswa"><div className="a12-activity" aria-label="Visual ilustratif aktivitas belajar">{[3,6,4,8,5,10,7,9,5,7,4,8].map((height,index)=><i style={{height:`${height*8}px`}} key={index} />)}</div><small>Rata-rata 420 aktivitas modul diselesaikan per hari.</small></Panel>
 <Panel title="Membership funnel" text="Pengunjung → Placement → Registrasi → Invoice → Aktif"><ol className="a12-funnel">{[["Visitor","8.420"],["Placement lead","3.150"],["Registered","1.284"],["Invoice","186"],["Membership active","142"]].map(([item,count])=><li key={item}><strong>{item}</strong><span>{count}</span></li>)}</ol></Panel>
 <Panel title="Learning engagement" text="Konsistensi belajar harian siswa dalam satu bulan terakhir."><div className="a12-intensity" aria-label="Visual ilustratif intensitas aktivitas">{Array.from({length:28},(_,index)=><i className={`level-${index%4}`} key={index} />)}</div><small>Tingkat keaktifan rata-rata 84% hadir dalam sesi.</small></Panel>
 <Panel title="Distribusi plan" text="Proporsi siswa berdasarkan paket belajar aktif."><div className="a12-distribution">{[["Free Member","428 Siswa"],["Belajar Mandiri","512 Siswa"],["Belajar dengan Sensei","344 Siswa"]].map(([item,val])=><div key={item}><strong>{item}</strong><span>{val}</span><i /></div>)}</div></Panel>
 <Panel title="Assessment performance" text="Tingkat kelulusan evaluasi belajar per kategori."><div className="a12-assessment">{[["Checkpoint completion","88% Selesai"],["Try Out completion","76% Selesai"],["Review opened","92% Dibaca"]].map(([item,val])=><div key={item}><strong>{item}</strong><span>{val}</span><i /></div>)}</div></Panel>
 <Panel title="Kepercayaan Data & Tata Kelola"><div className="a12-governance">{[["源","Sumber","Integrasi data analitik traffic dan laporan sistem akademik."],["時","Pembaruan","Waktu pembaruan data disinkronkan secara berkala."],["隠","Privasi","Perlindungan privasi data pengguna diterapkan."],["出","Ekspor","Laporan dapat diunduh untuk kebutuhan evaluasi tim."]].map(([glyph,title,text])=><article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div></Panel></div>
 <section className="a10-panel a12-events"><header><h2>GOOGLE ANALYTICS &amp; AKTIVITAS PENDAFTARAN</h2><p>Daftar event konversi yang dipantau untuk menganalisis alur belajar dan pendaftaran siswa.</p></header><div><div className="a8-badges"><b>GA4 Terhubung</b><span>UTM &amp; Kampanye Aktif</span><span>Pelaporan Rutin</span></div><p className="admin-local-feedback">Event terhubung dengan alur pendaftaran dan aktivitas penting di aplikasi.</p><div className="a12-event-list">{events.map(([name,text])=><article key={name}><code>{name}</code><span>{text}</span></article>)}</div><aside className="a8-privacy"><strong>PEMANTAUAN AKADEMIK</strong><p>Data analitik membantu Sensei dan admin memahami materi yang paling diminati serta kebutuhan bimbingan siswa.</p></aside></div></section>
 {exportOpen&&<div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={()=>setExportOpen(false)} aria-label="Tutup Export Analytics"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="analytics-export-title"><p className="admin-kicker">ADMIN • EXPORT</p><h2 id="analytics-export-title">Export sedang diproses</h2><strong>Status Proses</strong><p>Dataset, masking, permission, dan ukuran file diperiksa sebelum tautan download tersedia.</p><ul className="a8-steps"><li>Pemeriksaan akses</li><li>Pemeriksaan data</li><li>Audit event</li></ul><p className="admin-local-feedback" role="status">Presentasi frontend saja; tidak ada file, Blob, dataset, atau URL download dibuat.</p><div><button className="button button-primary" type="button" onClick={()=>setExportOpen(false)}>Kembali ke Analytics</button><button className="button button-secondary" type="button" onClick={()=>setExportOpen(false)}>Tutup</button></div></section></div>}
 </main></AdminShell>;
}
function Panel({title,text,badge,children}:{title:string;text?:string;badge?:string;children:React.ReactNode}){return <section className="a12-panel"><header><div><h2>{title}</h2>{text&&<p>{text}</p>}</div>{badge&&<span>{badge}</span>}</header><div>{children}</div></section>}
