"use client";

import Link from "next/link";
import { useState } from "react";
import { AdminShell } from "@/components/admin-shell";

const events=[["landing_view","Landing dibuka"],["free_trial_click","Klik Coba Gratis"],["placement_start","Placement dimulai"],["placement_complete","Placement selesai"],["plan_select","Plan dipilih"],["level_select","Level dipilih"],["sign_up","Registrasi selesai"],["referral_apply","Kode referral diterapkan"],["invoice_create","Invoice dibuat"],["payment_verified","Pembayaran diverifikasi"],["tryout_complete","Try Out selesai"],["feedback_submit","Feedback dikirim"]];
export default function AnalyticsPage(){
 const [period,setPeriod]=useState("Periode dari backend"),[exportOpen,setExportOpen]=useState(false);
 return <AdminShell current="analytics"><main className="admin-page admin-a12-page"><header className="admin-header"><div><p className="admin-kicker">ADMIN • ANALITIK &amp; GOOGLE ANALYTICS</p><h1>Analitik &amp; Google Analytics</h1><p>Pantau acquisition dan campaign melalui Google Analytics; transaksi, membership, entitlement, dan diskon tetap berasal dari backend.</p></div><div className="admin-header-actions"><label className="admin-field a12-period"><span>Periode</span><select value={period} onChange={(event)=>setPeriod(event.target.value)}><option>Periode dari backend</option></select></label><button className="button button-primary" type="button" onClick={()=>setExportOpen(true)}>Ekspor</button><Link className="button button-secondary" href="/admin">Dashboard</Link></div></header>
 <section className="admin-kpi-grid">{["Pembelajar aktif","Konversi membership","Learning engagement","Transaksi terverifikasi"].map((label)=><article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>Dinamis</strong><small>Data real-time dari backend.</small></article>)}</section>
 <section className="a12-authority"><div><strong>GOOGLE ANALYTICS / GA4</strong><p>Traffic, source / medium, UTM, campaign, dan acquisition funnel.</p></div><div><strong>BACKEND</strong><p>Transaction value, payment verification, membership, entitlement, referral reward, dan learning authority.</p></div><p>Google Analytics tidak mengaktifkan membership, menghitung reward referral, atau memverifikasi invoice. Semua keputusan tersebut berasal dari backend.</p></section>
 <div className="a12-grid"><Panel title="Aktivitas belajar" text="Bentuk visual ilustratif; nilai aktual berasal dari backend." badge="Backend + GA4"><div className="a12-activity" aria-label="Visual ilustratif aktivitas belajar">{[3,6,4,8,5,10,7,9,5,7,4,8].map((height,index)=><i style={{height:`${height*8}px`}} key={index} />)}</div><small>Ilustrasi tanpa sumbu atau nilai historis produksi.</small></Panel>
 <Panel title="Membership funnel" text="Landing → Placement → Register → Invoice → Active"><ol className="a12-funnel">{["Visitor","Placement lead","Registered","Invoice","Membership active"].map((item)=><li key={item}><strong>{item}</strong><span>—</span></li>)}</ol></Panel>
 <Panel title="Learning engagement" text="Intensitas visual mengikuti aktivitas harian; tidak menampilkan angka lama."><div className="a12-intensity" aria-label="Visual ilustratif intensitas aktivitas">{Array.from({length:28},(_,index)=><i className={`level-${index%4}`} key={index} />)}</div><small>Intensitas fixture; bukan streak atau hitungan member.</small></Panel>
 <Panel title="Distribusi plan" text="Nilai aktual mengikuti membership aktif."><div className="a12-distribution">{["Free Member","Belajar Mandiri","Belajar dengan Sensei"].map((item)=><div key={item}><strong>{item}</strong><span>—</span><i /></div>)}</div></Panel>
 <Panel title="Assessment performance" text="Checkpoint dan Try Out dipisahkan per level dan section."><div className="a12-assessment">{["Checkpoint completion","Try Out completion","Review opened"].map((item)=><div key={item}><strong>{item}</strong><span>Dinamis dari backend</span><i /></div>)}</div></Panel>
 <Panel title="Kepercayaan Data & Tata Kelola"><div className="a12-governance">{[["源","Sumber","GA untuk traffic dan campaign; backend untuk transaksi serta entitlement."],["時","Pembaruan","Tampilkan waktu pembaruan data. Dinamis / dari backend."],["隠","Privasi","Masking untuk data sensitif."],["出","Ekspor","Export mengikuti role dan permission."]].map(([glyph,title,text])=><article key={title}><span aria-hidden="true">{glyph}</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div></Panel></div>
 <section className="a10-panel a12-events"><header><h2>GOOGLE ANALYTICS &amp; CONVERSION EVENTS</h2><p>Gunakan GA4 untuk source/medium, UTM, dan funnel akuisisi. Nilai transaksi serta status akses tetap diverifikasi backend.</p></header><div><div className="a8-badges"><b>GA4 Terhubung • fixture</b><span>UTM &amp; Source Aktif • fixture</span><span>Backend Sinkron • fixture</span></div><p className="admin-local-feedback">Status integrasi hanya presentasi deterministik. Tidak ada SDK, Measurement ID, credential, API, atau koneksi nyata.</p><div className="a12-event-list">{events.map(([name,text])=><article key={name}><code>{name}</code><span>{text}</span></article>)}</div><aside className="a8-privacy"><strong>ANALYTICS OBSERVES • BACKEND DECIDES</strong><p>GA event tidak memverifikasi pembayaran, mengaktifkan plan, memberi entitlement, membuat reward, menentukan skor, atau membuat testimoni.</p><small>Event catalog tidak menembakkan tracking.</small></aside></div></section>
 {exportOpen&&<div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={()=>setExportOpen(false)} aria-label="Tutup Export Analytics"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="analytics-export-title"><p className="admin-kicker">ADMIN • EXPORT</p><h2 id="analytics-export-title">Export sedang diproses</h2><strong>System State</strong><p>Dataset, masking, permission, dan ukuran file diperiksa sebelum tautan download tersedia.</p><ul className="a8-steps"><li>Permission check</li><li>Backend validation</li><li>Audit event</li></ul><p className="admin-local-feedback" role="status">Presentasi frontend saja; tidak ada file, Blob, dataset, atau URL download dibuat.</p><div><button className="button button-primary" type="button" onClick={()=>setExportOpen(false)}>Kembali ke Analytics</button><button className="button button-secondary" type="button" onClick={()=>setExportOpen(false)}>Tutup</button></div></section></div>}
 </main></AdminShell>;
}
function Panel({title,text,badge,children}:{title:string;text?:string;badge?:string;children:React.ReactNode}){return <section className="a12-panel"><header><div><h2>{title}</h2>{text&&<p>{text}</p>}</div>{badge&&<span>{badge}</span>}</header><div>{children}</div></section>}
