"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Section = { id:string; label:string; active:boolean; fixed?:boolean };
type Dialog = "saved"|"preview"|"blocked"|"publish"|"published"|"restore"|"restored"|null;
const initialSections:Section[] = [{id:"hero",label:"Hero",active:true},{id:"program",label:"Program & Level",active:true},{id:"features",label:"Fitur",active:true},{id:"stats",label:"Statistik",active:true},{id:"placement",label:"Placement CTA",active:true},{id:"footer",label:"Footer",active:true,fixed:true}];
const versions = [{id:"v18",status:"Draft aktif",summary:"Perubahan CTA Coba Gratis"},{id:"v17",status:"Dipublikasikan",summary:"Program & Level diperbarui"},{id:"v16",status:"Diarsipkan",summary:"Versi sebelum meeting 28 Juli"}];

export default function LandingPageManagement() {
  const [headline,setHeadline] = useState("Belajar Jepang dengan journey yang terarah"),[subheadline,setSubheadline] = useState("Value proposition dari Admin"),[trust,setTrust] = useState("Chapter 1 gratis pada N1–N5"),[heroMedia,setHeroMedia] = useState("Asset hero fixture"),[programTitle,setProgramTitle] = useState("Pilih cara belajar dan level"),[featureTitle,setFeatureTitle] = useState("Fitur utama Hiru Academy"),[placementLabel,setPlacementLabel] = useState("Mulai Placement Test"),[seoTitle,setSeoTitle] = useState("Hiru Academy — Belajar Bahasa Jepang"),[meta,setMeta] = useState("Ringkasan untuk search engine"),[schedule,setSchedule] = useState("Publikasikan sekarang"),[sections,setSections] = useState(initialSections),[dialog,setDialog] = useState<Dialog>(null),[selectedVersion,setSelectedVersion] = useState("v17"),[status,setStatus] = useState("Draft aktif"),[dirty,setDirty] = useState(false),[previewReady,setPreviewReady] = useState(false);
  const [cta1,setCta1] = useState("Coba Gratis"),[cta2,setCta2] = useState("Placement Test"),[cta3,setCta3] = useState("Lihat Program"),[dest1,setDest1] = useState("Program & Level"),[dest2,setDest2] = useState("Placement Start"),[dest3,setDest3] = useState("Program & Level");
  const valid = useMemo(() => Boolean(headline.trim() && subheadline.trim() && heroMedia && seoTitle.trim() && meta.trim() && previewReady && sections.some((item) => item.active) && [dest1,dest2,dest3].every((item) => ["Program & Level","Placement Start"].includes(item))),[headline,subheadline,heroMedia,seoTitle,meta,previewReady,sections,dest1,dest2,dest3]);
  function changed() { setDirty(true);setPreviewReady(false);setStatus("Draft aktif"); }
  function move(index:number,direction:-1|1) { const target=index+direction;if (target < 0 || target >= sections.length || sections[index].fixed || sections[target].fixed && direction === 1) return;setSections((list) => {const next=[...list];[next[index],next[target]]=[next[target],next[index]];return next;});changed(); }
  function publish() { setDialog(valid ? "publish":"blocked"); }
  function restore() { const version=versions.find((item) => item.id === selectedVersion);if (!version) return;setHeadline(version.id === "v17" ? "Belajar Jepang dengan journey terarah":"Draft Landing versi sebelumnya");setStatus("Draft aktif");setDirty(false);setPreviewReady(false);setDialog("restored"); }
  return <AdminShell current="communication"><main className="admin-page admin-a10-page">
    <header className="admin-header"><div><p className="admin-kicker">KONTEN &amp; KOMUNIKASI • LANDING PAGE</p><h1>Pengelolaan Landing Page</h1><p>Kelola isi, urutan, visibility, CTA, dan SEO tanpa mengubah struktur layout secara bebas.</p></div><div className="admin-header-actions"><Link className="button button-secondary" href="/admin">Dashboard</Link><button className="button button-secondary" type="button" onClick={() => {setDirty(false);setDialog("saved");}}>Simpan Draft</button><button className="button button-dark" type="button" onClick={() => {setPreviewReady(true);setDialog("preview");}}>Pratinjau</button><button className="button button-primary" type="button" onClick={publish}>Publikasikan</button></div></header>
    <section className="admin-kpi-grid">{[["Status",status,"Belum memengaruhi halaman publik"],["Versi","Dinamis","Versi terakhir dari backend"],["Section aktif",sections.filter((item) => item.active).length,"Visibility dapat diubah"],["Terakhir diperbarui",dirty ? "Belum disimpan":"Dinamis","Waktu dan editor tercatat"]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <aside className="a10-controlled"><strong>CONTROLLED CRUD</strong><p>Admin dapat mengubah konten, urutan, visibility, CTA, media, dan SEO.</p><p>Admin tidak dapat mengubah grid, breakpoint, atau struktur responsive secara bebas.</p></aside>
    <div className="a10-layout"><div className="a10-editor"><Editor title="HERO & CTA" text="Konten utama yang tampil pertama kali pada Landing Page."><label className="admin-field"><span>Headline</span><input value={headline} onChange={(e) => {setHeadline(e.target.value);changed();}} /></label><label className="admin-field"><span>Subheadline</span><textarea rows={3} value={subheadline} onChange={(e) => {setSubheadline(e.target.value);changed();}} /></label><div className="a10-cta-grid">{[["CTA Utama",cta1,setCta1,dest1,setDest1],["CTA Kedua",cta2,setCta2,dest2,setDest2],["CTA Ketiga",cta3,setCta3,dest3,setDest3]].map(([label,value,setValue,destination,setDestination]) => <fieldset key={String(label)}><legend>{String(label)}</legend><label className="admin-field"><span>Label</span><input value={String(value)} onChange={(e) => {(setValue as (v:string)=>void)(e.target.value);changed();}} /></label><label className="admin-field"><span>Destination</span><select value={String(destination)} onChange={(e) => {(setDestination as (v:string)=>void)(e.target.value);changed();}}><option>Program & Level</option><option>Placement Start</option></select></label></fieldset>)}</div><section className="a10-media"><div><strong>Media Hero</strong><small>{heroMedia || "Belum dipilih"}</small></div><button type="button" onClick={() => {setHeroMedia(heroMedia ? "":"Asset hero fixture");changed();}}>{heroMedia ? "Hapus fixture":"Pilih asset fixture"}</button></section><label className="admin-field"><span>Trust Copy</span><input value={trust} onChange={(e) => {setTrust(e.target.value);changed();}} /></label></Editor>
      <Editor title="PROGRAM, FITUR & PLACEMENT CTA" text="Konten dapat diedit; layout, grid, dan responsive behavior tetap dikunci oleh sistem."><div className="a8-form-grid"><label className="admin-field"><span>Judul Program</span><input value={programTitle} onChange={(e) => {setProgramTitle(e.target.value);changed();}} /></label><label className="admin-field"><span>Urutan Plan</span><input value="Free → Mandiri → Sensei" readOnly /></label><label className="admin-field"><span>Judul Fitur</span><input value={featureTitle} onChange={(e) => {setFeatureTitle(e.target.value);changed();}} /></label><label className="admin-field"><span>Jumlah Card</span><input value="6 fasilitas dari client" readOnly /></label><label className="admin-field"><span>Placement CTA</span><input value={placementLabel} onChange={(e) => {setPlacementLabel(e.target.value);changed();}} /></label><label className="admin-field"><span>Destination</span><input value="FREE / 07 — Placement Start" readOnly /></label></div><aside className="a10-testimonial"><strong>Testimoni tidak menjadi section Landing Page</strong><p>Sesuai keputusan client, testimoni publik hanya tampil pada halaman Testimoni.</p></aside></Editor>
      <Editor title="FOOTER & SEO"><label className="admin-field"><span>SEO Title</span><input value={seoTitle} onChange={(e) => {setSeoTitle(e.target.value);changed();}} /></label><label className="admin-field"><span>Meta Description</span><textarea rows={3} value={meta} onChange={(e) => {setMeta(e.target.value);changed();}} /></label><div className="a8-form-grid"><label className="admin-field"><span>Footer Links</span><input value="Program, Placement, Testimoni, Blog" readOnly /></label><label className="admin-field"><span>Social & Legal</span><input value="URL dinamis dari Admin" readOnly /></label></div></Editor></div>
      <aside className="a10-side"><section><h2>STATUS PUBLIKASI</h2><strong>{status}</strong><p>Perubahan belum tampil pada halaman publik.</p><label className="admin-field"><span>Jadwal Publikasi</span><select value={schedule} onChange={(e) => {setSchedule(e.target.value);changed();}}><option>Publikasikan sekarang</option><option>Jadwalkan • backend-owned</option></select></label></section><section><h2>VISIBILITY & URUTAN SECTION</h2>{sections.map((item,index) => <div className="a10-section-row" key={item.id}><label><input type="checkbox" checked={item.active} onChange={(e) => {setSections((list) => list.map((entry) => entry.id === item.id ? {...entry,active:e.target.checked}:entry));changed();}} /> <span>{index+1}. {item.label}</span></label><small>{item.active ? "Aktif":"Nonaktif"}</small><span><button type="button" disabled={index === 0 || item.fixed} onClick={() => move(index,-1)} aria-label={`Naikkan ${item.label}`}>↑</button><button type="button" disabled={index === sections.length-1 || item.fixed || sections[index+1]?.fixed} onClick={() => move(index,1)} aria-label={`Turunkan ${item.label}`}>↓</button></span></div>)}<div className="a10-section-row locked"><strong>Testimoni</strong><small>Tidak digunakan</small></div></section><section><h2>RIWAYAT VERSI</h2>{versions.map((item) => <label className="a10-version" key={item.id}><input type="radio" name="version" value={item.id} checked={selectedVersion === item.id} onChange={() => setSelectedVersion(item.id)} /><span><strong>{item.id} • {item.status}</strong><small>{item.summary}</small></span></label>)}<button className="button button-secondary" type="button" onClick={() => setDialog("restore")}>Pulihkan Versi Sebelumnya</button></section></aside></div>
    {dialog && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setDialog(null)} aria-label="Tutup state Landing Page"/><section className="a4-dialog a8-dialog a10-dialog" role="dialog" aria-modal="true" aria-labelledby="landing-state-title">
      {dialog === "saved" && <Result kicker="ADMIN • LANDING PAGE DRAFT" title="Draft Landing Page berhasil disimpan" text="Konten, visibility, urutan section, CTA, media, dan SEO disimpan sebagai draft." note="Fixture lokal saja; backend, audit, versioning, dan halaman publik tidak berubah." close={() => setDialog(null)} />}
      {dialog === "preview" && <><p className="admin-kicker">ADMIN • PRATINJAU LANDING PAGE</p><h2 id="landing-state-title">Pratinjau Landing Page siap</h2><p>Pratinjau menggunakan data draft dan tidak mengubah halaman publik yang aktif.</p><div className="a10-preview"><small>DRAFT PREVIEW • TIDAK PUBLIK</small><h3>{headline}</h3><p>{subheadline}</p><div><b>{cta1}</b><span>{cta3}</span></div><ol>{sections.filter((item) => item.active).map((item) => <li key={item.id}>{item.label}</li>)}</ol><strong>{placementLabel}</strong></div><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke Landing Page</button></>}
      {dialog === "blocked" && <><p className="admin-kicker">ADMIN • PUBLIKASI LANDING PAGE</p><h2 id="landing-state-title">Landing Page belum dapat dipublikasikan</h2><p>Lengkapi CTA, media, visibility, SEO, dan pratinjau draft sebelum publikasi.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Periksa Editor</button></>}
      {dialog === "publish" && <><p className="admin-kicker">ADMIN • PUBLIKASI LANDING PAGE</p><h2 id="landing-state-title">Publikasikan Landing Page?</h2><p>Versi draft akan menggantikan versi publik setelah semua CTA, media, visibility, dan SEO tervalidasi.</p><ul className="a8-steps"><li>Validasi CTA</li><li>Validasi media &amp; SEO</li><li>Pratinjau draft siap</li></ul><div><button className="button button-primary" type="button" onClick={() => {setStatus("Dipublikasikan • simulasi lokal");setDialog("published");}}>Publikasikan</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Kembali ke Landing Page</button></div></>}
      {dialog === "published" && <Result kicker="ADMIN • LANDING PAGE PUBLIK" title="Landing Page berhasil dipublikasikan" text="Versi publik telah diperbarui dan versi sebelumnya tetap tersimpan pada riwayat." note="Simulasi frontend saja; /, SEO, cache, media, dan versi publik nyata tidak berubah." close={() => setDialog(null)} />}
      {dialog === "restore" && <><p className="admin-kicker">ADMIN • RIWAYAT LANDING PAGE</p><h2 id="landing-state-title">Pulihkan versi sebelumnya?</h2><p>Versi terpilih akan menjadi draft aktif. Halaman publik tidak berubah sampai versi tersebut dipublikasikan.</p><ul className="a8-steps"><li>Versi dipilih: {selectedVersion}</li><li>Draft baru dibuat secara lokal</li></ul><div><button className="button button-primary" type="button" onClick={restore}>Pulihkan Versi</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Kembali ke Landing Page</button></div></>}
      {dialog === "restored" && <Result kicker="ADMIN • RIWAYAT LANDING PAGE" title="Versi sebelumnya berhasil dipulihkan" text="Konten versi terpilih menjadi draft aktif dan dapat ditinjau sebelum publikasi." note="Draft dipulihkan secara lokal; versi publik tetap aktif dan Publish terpisah tetap diperlukan." close={() => setDialog(null)} />}
    </section></div>}
  </main></AdminShell>;
}
function Editor({title,text,children}:{title:string;text?:string;children:React.ReactNode}) { return <section className="a10-panel"><header><h2>{title}</h2>{text && <p>{text}</p>}</header><div>{children}</div></section>; }
function Result({kicker,title,text,note,close}:{kicker:string;title:string;text:string;note:string;close:()=>void}) { return <section className="a4-success"><p className="admin-kicker">{kicker}</p><h2 id="landing-state-title">{title}</h2><span aria-hidden="true">✓</span><p>{text}</p><p className="admin-local-feedback" role="status">{note}</p><button className="button button-primary" type="button" onClick={close}>Kembali ke Landing Page</button></section>; }
