"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Referral = { id:string; owner:string; user:string; invoice:string; status:string; reward:string; verified:boolean; clicks:number; signups:number; purchases:number; totalCommission:string; unpaidCommission:string };
type State = "rules" | "activated" | "blocked" | "cancel" | "cancelled" | "export" | null;
const fixtures:Referral[] = [
  { id:"HIRU-HILMI25", owner:"Hilmi", user:"Ahmad", invoice:"INV •••1024", status:"Komisi valid", reward:"Rp. 20.000", verified:true, clicks:120, signups:18, purchases:5, totalCommission:"Rp750.000", unpaidCommission:"Rp300.000" },
  { id:"HIRU-RINA", owner:"Rina", user:"Shinta", invoice:"INV •••1017", status:"Menunggu pembayaran", reward:"Rp. 0", verified:false, clicks:80, signups:12, purchases:3, totalCommission:"Rp420.000", unpaidCommission:"Rp170.000" },
  { id:"HIRU-AYU", owner:"Ayu", user:"Budi", invoice:"INV •••1008", status:"Komisi dicairkan", reward:"Rp450.000", verified:true, clicks:64, signups:9, purchases:4, totalCommission:"Rp600.000", unpaidCommission:"Rp0" },
  { id:"HIRU-DIMAS", owner:"Dimas", user:"Pengguna •••7", invoice:"INV •••0998", status:"Dibatalkan", reward:"Rp. 0", verified:false, clicks:30, signups:4, purchases:0, totalCommission:"Rp0", unpaidCommission:"Rp0" },
];

export default function ReferralsPage() {
  const [items,setItems] = useState(fixtures);
  const [selectedId,setSelectedId] = useState("HIRU-HILMI25");
  const [query,setQuery] = useState("");
  const [filter,setFilter] = useState("Semua Status");
  const [state,setState] = useState<State>(null);
  const [reason,setReason] = useState("");
  const [error,setError] = useState("");
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  const visible = useMemo(() => items.filter((item) => (filter === "Semua Status" || item.status === filter) && `${item.id} ${item.owner} ${item.user} ${item.invoice}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  function activate() { if (!selected.verified || !["Tersedia","Digunakan"].includes(selected.status)) { setState("blocked"); return; } setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Tersedia",reward:"Reward dapat digunakan"}:item)); setState("activated"); }
  function openCancel() { setReason("");setError("");setState("cancel"); }
  function cancel() { if (!reason.trim()) {setError("Alasan wajib diisi sebelum reward dibatalkan.");return;} setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Dibatalkan",reward:"Reward dibatalkan"}:item));setState("cancelled"); }

  return <AdminShell current="transaction"><main className="admin-page admin-a5-page">
    <header className="admin-header"><div><p className="admin-kicker">TRANSAKSI • REFERRAL &amp; DISKON</p><h1>Pengelolaan Referral &amp; Diskon</h1><p>Kelola kode referral, diskon pendaftar baru, reward pemilik kode, dan laporan penggunaan.</p></div><div className="admin-header-actions"><button className="button button-primary" type="button" onClick={() => setState("rules")}>Simpan Aturan</button></div></header>
    <section className="admin-kpi-grid">{[["Semua affiliate","128","Affiliate terdaftar"],["Kode affiliate","128","Kode affiliate aktif"],["Jumlah klik","120","Klik pada link affiliate"],["Jumlah pendaftar","18","Pendaftar dari referral"],["Jumlah pembelian","5","Pembelian terverifikasi"],["Total komisi","Rp750.000","Akumulasi komisi"],["Komisi belum dibayar","Rp300.000","Menunggu pencairan"]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a5-filters referral-filter"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari kode, pemilik, pengguna, atau invoice" /></label><label className="admin-field"><span>Status</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>Semua Status</option><option>Klik</option><option>Daftar</option><option>Menunggu pembayaran</option><option>Sudah bayar</option><option>Komisi valid</option><option>Komisi dicairkan</option><option>Dibatalkan</option></select></label><button className="button button-secondary" type="button" onClick={() => setState("export")}>Ekspor Data</button></section>
    <div className="a5-referral-layout"><section className="a5-referral-list"><header><h2>Antrean referral</h2><p>Daftar klaim kode referral siswa dan status verifikasi invoice.</p></header>{visible.length ? visible.map((item) => <button className={selected.id === item.id ? "active":""} type="button" onClick={() => setSelectedId(item.id)} key={item.id}><strong>{item.id}</strong><span>{item.owner}</span><span>{item.user}</span><span>{item.invoice}</span><b>{item.status}</b><small>{item.reward}</small></button>) : <section className="a4-empty-table"><h2>Belum ada data untuk filter ini</h2><button className="button button-secondary" type="button" onClick={() => {setQuery("");setFilter("Semua Status");}}>Reset Filter</button></section>}</section>
      <aside className="a5-referral-detail"><header><p className="admin-kicker">DETAIL REFERRAL TERPILIH</p><h2>{selected.id}</h2><p>{selected.owner} → {selected.user}</p><span>{selected.verified ? "INVOICE TERVERIFIKASI":"INVOICE BELUM TERVERIFIKASI"}</span><strong>{selected.invoice}</strong><small>Membership mengikuti invoice • {selected.reward}</small></header><dl><div><dt>Jumlah klik</dt><dd>{selected.clicks}</dd></div><div><dt>Jumlah pendaftar</dt><dd>{selected.signups}</dd></div><div><dt>Jumlah pembelian</dt><dd>{selected.purchases}</dd></div><div><dt>Total komisi</dt><dd>{selected.totalCommission}</dd></div><div><dt>Komisi belum dibayar</dt><dd>{selected.unpaidCommission}</dd></div></dl><div className="a5-detail-actions" style={{ display: "flex", gap: "10px", flexWrap: "wrap", alignItems: "center" }}><button className="button button-secondary danger" type="button" onClick={openCancel}>Batalkan Reward</button><Link className="button button-dark" href="/admin/invoices">Lihat Invoice</Link><Link className="button button-primary" href="/admin/users" style={{ background: "var(--navy)", color: "#ffffff" }}>Lihat Pengguna</Link><button className="button button-primary" type="button" onClick={activate}>Tandai Sudah Dicairkan</button></div><aside className="a5-self-rule"><strong>Anti self-referral: Aktif</strong><p>Reward tidak dibuat untuk invoice gagal, refund, atau transaksi akun sendiri.</p></aside></aside></div>
    <section className="a5-rules"><header><h2>Aturan program affiliate</h2><p>Atur komisi, masa validasi, dan status affiliate.</p></header>{[["Persentase komisi","Dari konfigurasi"],["Nominal komisi","Dari konfigurasi"],["Masa validasi komisi","Dari konfigurasi"],["Status affiliate","Aktif / Nonaktif"]].map(([label,value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}<p>Perubahan aturan affiliate dapat disimpan melalui tombol Simpan Aturan.</p></section>
    {state && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setState(null)} aria-label="Tutup state referral"/><section className="a4-dialog a5-dialog" role="dialog" aria-modal="true" aria-labelledby="referral-state-title">
      {state === "rules" && <section className="a4-success"><p className="admin-kicker">REFERRAL &amp; DISKON • BERHASIL</p><h2 id="referral-state-title">Aturan referral berhasil disimpan</h2><span aria-hidden="true">✓</span><p>Kebijakan reward dan diskon referral telah diperbarui.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "activated" && <section className="a4-success"><p className="admin-kicker">REWARD • TERSEDIA</p><h2 id="referral-state-title">Reward diskon berhasil diaktifkan</h2><span aria-hidden="true">✓</span><p>Reward pemilik kode sekarang tersedia dan dapat digunakan untuk potongan renewal.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "blocked" && <><p className="admin-kicker">REWARD • BELUM DAPAT DIAKTIFKAN</p><h2 id="referral-state-title">Reward belum dapat diaktifkan</h2><p>Reward hanya tersedia setelah invoice siswa baru berhasil diverifikasi.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali</button></>}
      {state === "cancel" && <><p className="admin-kicker">KONFIRMASI • PEMBATALAN</p><h2 id="referral-state-title">Batalkan reward referral?</h2><p>Gunakan tindakan ini jika transaksi dibatalkan atau terindikasi pelanggaran aturan referral.</p><label className="admin-field"><span>Alasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation" role="alert">{error}</p>}<div><button className="button button-primary" type="button" onClick={cancel}>Batalkan Reward</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Kembali</button></div></>}
      {state === "cancelled" && <section className="a4-success"><p className="admin-kicker">REWARD • DIBATALKAN</p><h2 id="referral-state-title">Reward referral berhasil dibatalkan</h2><span aria-hidden="true">✓</span><p>Status reward berhasil dibatalkan dan dicatat pada sistem.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "export" && <section className="a4-success"><p className="admin-kicker">REFERRAL &amp; DISKON • EKSPOR</p><h2 id="referral-state-title">Ekspor data referral sedang diproses</h2><p>Data kode referral dan riwayat komisi sedang diekspor dalam format spreadsheet.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
    </section></div>}
  </main></AdminShell>;
}
