"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Referral = { id:string; owner:string; user:string; invoice:string; status:string; reward:string; verified:boolean };
type State = "rules" | "activated" | "blocked" | "cancel" | "cancelled" | "export" | null;
const fixtures:Referral[] = [
  { id:"HIRU-RINA", owner:"Pemilik •••1", user:"Pengguna •••8", invoice:"INV •••1024", status:"Menunggu", reward:"Reward belum aktif", verified:false },
  { id:"HIRU-DIMAS", owner:"Pemilik •••2", user:"Pengguna •••9", invoice:"INV •••1017", status:"Tersedia", reward:"Reward dapat digunakan", verified:true },
  { id:"HIRU-AYU", owner:"Pemilik •••3", user:"Pengguna •••4", invoice:"INV •••1008", status:"Digunakan", reward:"Dipakai pada renewal", verified:true },
  { id:"HIRU-HILMI", owner:"Pemilik •••4", user:"Pengguna •••7", invoice:"INV •••0998", status:"Dibatalkan", reward:"Invoice dibatalkan", verified:false },
];

export default function ReferralsPage() {
  const [items,setItems] = useState(fixtures);
  const [selectedId,setSelectedId] = useState("HIRU-DIMAS");
  const [query,setQuery] = useState("");
  const [filter,setFilter] = useState("Semua Status");
  const [state,setState] = useState<State>(null);
  const [reason,setReason] = useState("");
  const [error,setError] = useState("");
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  const visible = useMemo(() => items.filter((item) => (filter === "Semua Status" || item.status === filter) && `${item.id} ${item.owner} ${item.user} ${item.invoice}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  function activate() { if (!selected.verified || !["Tersedia","Digunakan"].includes(selected.status)) { setState("blocked"); return; } setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Tersedia",reward:"Reward dapat digunakan"}:item)); setState("activated"); }
  function openCancel() { setReason("");setError("");setState("cancel"); }
  function cancel() { if (!reason.trim()) {setError("Alasan wajib diisi sebelum reward dibatalkan.");return;} setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Dibatalkan",reward:"Reward dibatalkan"}:item));setState("cancelled"); }

  return <AdminShell current="transaction"><main className="admin-page admin-a5-page">
    <header className="admin-header"><div><p className="admin-kicker">TRANSAKSI • REFERRAL &amp; DISKON</p><h1>Pengelolaan Referral &amp; Diskon</h1><p>Kelola kode, diskon pengguna baru, reward pemilik kode, invoice, masa berlaku, dan audit dalam satu alur backend.</p></div><div className="admin-header-actions"><Link className="button button-secondary" href="/admin">Dashboard</Link><button className="button button-primary" type="button" onClick={() => setState("rules")}>Simpan Aturan</button></div></header>
    <section className="admin-kpi-grid">{[["Kode aktif","Dinamis","Kode yang dapat digunakan"],["Penggunaan valid","Dinamis","Invoice memenuhi aturan"],["Reward menunggu","Dinamis","Menunggu verifikasi invoice"],["Reward tersedia","Dinamis","Dapat dipakai pada transaksi"]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a5-filters referral-filter"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari kode, pemilik, pengguna, atau invoice" /></label><label className="admin-field"><span>Status</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>Semua Status</option><option>Menunggu</option><option>Tersedia</option><option>Digunakan</option><option>Kedaluwarsa</option><option>Dibatalkan</option></select></label><button className="button button-secondary" type="button" onClick={() => setState("export")}>Ekspor Data</button></section>
    <div className="a5-referral-layout"><section className="a5-referral-list"><header><h2>Antrean referral</h2><p>Data pengguna dimasking. Reward baru tersedia setelah invoice terverifikasi.</p></header>{visible.length ? visible.map((item) => <button className={selected.id === item.id ? "active":""} type="button" onClick={() => setSelectedId(item.id)} key={item.id}><strong>{item.id}</strong><span>{item.owner}</span><span>{item.user}</span><span>{item.invoice}</span><b>{item.status}</b><small>{item.reward}</small></button>) : <section className="a4-empty-table"><h2>Belum ada data untuk filter ini</h2><button className="button button-secondary" type="button" onClick={() => {setQuery("");setFilter("Semua Status");}}>Reset Filter</button></section>}</section>
      <aside className="a5-referral-detail"><header><p className="admin-kicker">DETAIL REFERRAL TERPILIH</p><h2>{selected.id}</h2><p>{selected.owner} → {selected.user}</p><span>{selected.verified ? "INVOICE TERVERIFIKASI":"INVOICE BELUM TERVERIFIKASI"}</span><strong>{selected.invoice}</strong><small>Membership mengikuti invoice • {selected.reward}</small></header><dl><div><dt>Diskon pengguna baru</dt><dd>Nilai dinamis</dd></div><div><dt>Reward pemilik kode</dt><dd>Nilai dinamis</dd></div><div><dt>Masa berlaku</dt><dd>Dari konfigurasi backend</dd></div></dl><div className="a5-detail-actions"><Link className="button button-secondary" href="/admin/invoices">Lihat Invoice</Link><Link className="button button-secondary" href="/admin/users">Lihat Pengguna</Link><button className="button button-primary" type="button" onClick={activate}>Aktifkan Reward</button><button className="button button-secondary danger" type="button" onClick={openCancel}>Batalkan Reward</button></div><aside className="a5-self-rule"><strong>Anti self-referral: Aktif</strong><p>Reward tidak dibuat untuk invoice gagal, refund, self-referral, atau transaction invalid.</p></aside></aside></div>
    <section className="a5-rules"><header><h2>Aturan program</h2><p>Semua nilai berasal dari backend dan perubahan wajib masuk audit log.</p></header>{[["Diskon pengguna baru","Dinamis per program"],["Reward pemilik kode","Dinamis per program"],["Aktivasi reward","Setelah invoice diverifikasi"],["Masa berlaku","Dari konfigurasi"],["Batas penggunaan","Per akun / per kode"],["Self-referral","Tidak diizinkan"]].map(([label,value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}<p>Audit log menyimpan perubahan aturan, aktivasi reward, penggunaan, pembatalan, dan alasan.</p></section>
    {state && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setState(null)} aria-label="Tutup state referral"/><section className="a4-dialog a5-dialog" role="dialog" aria-modal="true" aria-labelledby="referral-state-title">
      {state === "rules" && <section className="a4-success"><p className="admin-kicker">REFERRAL &amp; DISKON • BERHASIL</p><h2 id="referral-state-title">Aturan referral berhasil disimpan</h2><span aria-hidden="true">✓</span><p>Fixture lokal diperbarui; nilai, audit, dan backend policy tidak dipersistensikan.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "activated" && <section className="a4-success"><p className="admin-kicker">REWARD • TERSEDIA</p><h2 id="referral-state-title">Reward diskon berhasil diaktifkan</h2><span aria-hidden="true">✓</span><p>Reward pemilik kode sekarang tersedia karena invoice pengguna baru sudah diverifikasi. Nilai mengikuti backend; membership tidak dimutasi.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "blocked" && <><p className="admin-kicker">REWARD • BLOCKED</p><h2 id="referral-state-title">Reward belum dapat diaktifkan</h2><p>Reward hanya tersedia setelah qualifying invoice diverifikasi dan anti self-referral terpenuhi.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali</button></>}
      {state === "cancel" && <><p className="admin-kicker">KONFIRMASI • DESTRUKTIF</p><h2 id="referral-state-title">Batalkan reward referral?</h2><p>Gunakan tindakan ini hanya jika invoice dibatalkan, refund, self-referral, atau pelanggaran aturan terverifikasi.</p><label className="admin-field"><span>Alasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation" role="alert">{error}</p>}<div><button className="button button-primary" type="button" onClick={cancel}>Batalkan Reward</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Kembali</button></div></>}
      {state === "cancelled" && <section className="a4-success"><p className="admin-kicker">REWARD • DIBATALKAN</p><h2 id="referral-state-title">Reward referral berhasil dibatalkan</h2><span aria-hidden="true">✓</span><p>Status fixture dibatalkan. Membership pengguna tidak terpengaruh. Audit belum dipersistensikan.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
      {state === "export" && <section className="a4-success"><p className="admin-kicker">REFERRAL &amp; DISKON • EKSPOR</p><h2 id="referral-state-title">Ekspor data referral sedang diproses</h2><p>File akan memuat code, user terkait, invoice, discount, reward, status, dan audit sesuai filter aktif. Permission dan masking tetap backend-owned; tidak ada file dibuat.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Referral</button></section>}
    </section></div>}
  </main></AdminShell>;
}
