"use client";

import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Certificate = { id:string; member:string; program:string; eligibility:string; status:string };
type State = "template" | "issue" | "blocked" | "processed" | "download" | "reissue" | "revoke" | "revoked" | null;
const fixtures:Certificate[] = [
  { id:"c1", member:"Member •••1", program:"JLPT N5", eligibility:"Eligible", status:"Issued" },
  { id:"c2", member:"Member •••2", program:"JLPT N4", eligibility:"Eligible", status:"Pending" },
  { id:"c3", member:"Member •••3", program:"JLPT N4", eligibility:"Not Eligible", status:"Pending" },
  { id:"c4", member:"Member •••4", program:"JLPT N5", eligibility:"Eligible", status:"Revoked" },
  { id:"c5", member:"Member •••5", program:"JLPT N3", eligibility:"Not Eligible", status:"Pending" },
];

export default function CertificatesPage() {
  const [items,setItems] = useState(fixtures);
  const [selectedId,setSelectedId] = useState("c1");
  const [query,setQuery] = useState("");
  const [program,setProgram] = useState("Semua Program");
  const [status,setStatus] = useState("Semua Status");
  const [state,setState] = useState<State>(null);
  const [reason,setReason] = useState("");
  const [error,setError] = useState("");
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  const visible = useMemo(() => items.filter((item) => (program === "Semua Program" || item.program === program) && (status === "Semua Status" || item.status === status) && `${item.member} ${item.program} ${item.status}`.toLowerCase().includes(query.toLowerCase())),[items,program,status,query]);
  function open(next:State) { setReason("");setError("");setState(next); }
  function issueSelected() { if (selected.eligibility !== "Eligible" || selected.status !== "Pending") { setState("blocked"); return; } setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Issued"}:item));setState("processed"); }
  function issueEligible() { const target = items.find((item) => item.eligibility === "Eligible" && item.status === "Pending"); if (!target) {setState("blocked");return;} setSelectedId(target.id);setState("issue"); }
  function reissue() { if (!reason.trim()) {setError("Ringkasan wajib diisi untuk terbit ulang.");return;} setState("processed"); }
  function revoke() { if (!reason.trim()) {setError("Alasan pencabutan wajib diisi.");return;} setItems((list) => list.map((item) => item.id === selected.id ? {...item,status:"Revoked"}:item));setState("revoked"); }

  return <AdminShell current="users"><main className="admin-page admin-a6-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • DIGITAL CREDENTIALS</p><h1>Certificate Management</h1><p>Kelola eligibility, issuance, digital preview, download log, revocation, reissue, dan audit.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={() => open("template")}>Template</button><button className="button button-primary" type="button" onClick={issueEligible}>Terbitkan yang Memenuhi</button></div></header>
    <aside className="a6-digital-only"><strong>DIGITAL ONLY</strong><p>Scope MVP menggunakan sertifikat digital; tidak menggunakan sertifikat fisik lama.</p></aside>
    <section className="admin-kpi-grid">{[["Eligible","Dinamis","Memenuhi kriteria program."],["Issued","Dinamis","Sertifikat digital diterbitkan."],["Pending","Dinamis","Menunggu review atau issue."],["Revoked","Dinamis","Dicabut dengan alasan tercatat."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a6-filters"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari penerima termasking, program, atau status" /></label><label className="admin-field"><span>Program</span><select value={program} onChange={(event) => setProgram(event.target.value)}><option>Semua Program</option>{["JLPT N1","JLPT N2","JLPT N3","JLPT N4","JLPT N5"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="admin-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option>Semua Status</option><option>Issued</option><option>Pending</option><option>Revoked</option></select></label></section>
    <div className="a6-layout"><section className="a6-list"><header><span>Recipient</span><span>Program</span><span>Eligibility</span><span>Certificate Status</span><span>Action</span></header>{visible.length ? visible.map((item) => <button className={selected.id === item.id ? "active":""} type="button" onClick={() => setSelectedId(item.id)} key={item.id}><div><strong>{item.member}</strong><small>Data penerima dimasking</small></div><div><strong>{item.program}</strong><small>Kriteria dari backend</small></div><span>{item.eligibility}</span><b>{item.status}</b><em>Detail</em></button>) : <section className="a4-empty-table"><h2>Belum ada data untuk filter ini</h2><p>Ubah program, status, atau kata kunci.</p><button className="button button-secondary" type="button" onClick={() => {setQuery("");setProgram("Semua Program");setStatus("Semua Status");}}>Reset Filter</button></section>}<footer className="asset-pagination"><span>Pagination fixture lokal</span><div><button disabled type="button">‹</button><button className="active" type="button">1</button><button type="button">2</button><button type="button">›</button></div></footer></section>
      <aside className="a6-detail"><header><div><p className="admin-kicker">{selected.member.toUpperCase()}</p><h2>{selected.program} • Digital Certificate</h2></div><div><span>{selected.eligibility}</span><b>{selected.status}</b></div></header><section className="a6-preview"><p>SERTIFIKAT DIGITAL</p><strong>{selected.member}</strong><span>Telah menyelesaikan program {selected.program}</span><small>Digital preview fixture; bukan file atau printable certificate.</small></section><section className="a6-eligibility"><p className="admin-kicker">ELIGIBILITY</p>{["Program selesai","Assessment memenuhi rule","Membership valid saat completion","Tidak ada revocation aktif"].map((criterion,index) => { const complete = selected.eligibility === "Eligible" && (index !== 3 || selected.status !== "Revoked"); return <div className={complete ? "complete" : "incomplete"} key={criterion}><span aria-hidden="true">{complete ? "✓" : "!"}</span><strong>{criterion}</strong></div>; })}<p>Kriteria ditampilkan dari fixture; evaluasi tetap backend-owned.</p></section><section className="a6-audit"><p className="admin-kicker">DOWNLOAD &amp; AUDIT LOG</p><p>Issue time, downloads, reissue, revocation, actor, dan reason berasal dari backend.</p></section><div className="a6-actions"><button className="button button-secondary" type="button" disabled={selected.status !== "Issued"} onClick={() => open("download")}>Unduh</button><button className="button button-secondary" type="button" disabled={selected.status !== "Issued"} onClick={() => open("reissue")}>Terbitkan Ulang</button><button className="button button-secondary danger" type="button" disabled={selected.status !== "Issued"} onClick={() => open("revoke")}>Cabut</button>{selected.status === "Pending" && <button className="button button-primary" type="button" onClick={() => selected.eligibility === "Eligible" ? open("issue"):open("blocked")}>Terbitkan</button>}</div></aside></div>
    {state && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setState(null)} aria-label="Tutup state sertifikat"/><section className="a4-dialog a6-dialog" role="dialog" aria-modal="true" aria-labelledby="certificate-dialog-title">
      {state === "template" && <><p className="admin-kicker">SERTIFIKAT</p><h2 id="certificate-dialog-title">Template sertifikat siap diedit</h2><p>Logo, judul, penandatangan, nomor, dan metadata verifikasi dapat diperbarui.</p><label className="admin-field"><span>Logo</span><input value="Logo HIRU dari backend" readOnly /></label><label className="admin-field"><span>Judul</span><input defaultValue="Sertifikat Digital" /></label><label className="admin-field"><span>Penandatangan</span><input value="Dari konfigurasi backend" readOnly /></label><label className="admin-field"><span>Nomor &amp; metadata verifikasi</span><input value="Dikelola backend" readOnly /></label><p>Aksi mengikuti permission Admin dan dicatat pada audit log. Perubahan ini hanya fixture lokal.</p><div><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Sertifikat</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Batal</button></div></>}
      {state === "issue" && <><p className="admin-kicker">SERTIFIKAT • ISSUE</p><h2 id="certificate-dialog-title">Terbitkan sertifikat eligible?</h2><p>{selected.member} • {selected.program}. Eligibility dan issuance wajib diverifikasi backend.</p><div><button className="button button-primary" type="button" onClick={issueSelected}>Proses Fixture Lokal</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Batal</button></div></>}
      {state === "blocked" && <><p className="admin-kicker">SERTIFIKAT • BLOCKED</p><h2 id="certificate-dialog-title">Sertifikat belum dapat diterbitkan</h2><p>Not Eligible atau status tidak memenuhi syarat. Eligibility tetap backend-owned.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Sertifikat</button></>}
      {state === "processed" && <section className="a4-success"><p className="admin-kicker">SERTIFIKAT</p><h2 id="certificate-dialog-title">Aksi sertifikat berhasil diproses</h2><span aria-hidden="true">✓</span><p>Penerbitan, unduh, atau terbit ulang mengikuti eligibility dan versi template aktif. State ini simulasi frontend; backend dan audit belum terhubung.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Sertifikat</button></section>}
      {state === "download" && <><p className="admin-kicker">SERTIFIKAT</p><h2 id="certificate-dialog-title">Aksi sertifikat berhasil diproses</h2><p>Digital file berasal dari backend. Tidak ada PDF, Blob, URL, atau download yang dibuat.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Sertifikat</button></>}
      {state === "reissue" && <><p className="admin-kicker">SERTIFIKAT</p><h2 id="certificate-dialog-title">Terbitkan ulang sertifikat</h2><p>Credential identity tetap sama; version, issue time, dan audit berasal dari backend.</p><label className="admin-field"><span>Ringkasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation">{error}</p>}<div><button className="button button-primary" type="button" onClick={reissue}>Proses Terbit Ulang</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Batal</button></div></>}
      {state === "revoke" && <><p className="admin-kicker">SERTIFIKAT • DESTRUKTIF</p><h2 id="certificate-dialog-title">Cabut sertifikat ini?</h2><p>Sertifikat tidak lagi valid untuk verifikasi publik. Alasan pencabutan wajib dicatat.</p><label className="admin-field"><span>Alasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation" role="alert">{error}</p>}<div><button className="button button-primary" type="button" onClick={revoke}>Cabut Sertifikat</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Batal</button></div></>}
      {state === "revoked" && <section className="a4-success"><p className="admin-kicker">SERTIFIKAT</p><h2 id="certificate-dialog-title">Sertifikat berhasil dicabut</h2><span aria-hidden="true">✓</span><p>Status certificate fixture menjadi Revoked. Membership dan progress tidak berubah. Backend permission dan audit belum terhubung.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Sertifikat</button></section>}
    </section></div>}
  </main></AdminShell>;
}
