"use client";

import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Post = { id:string; author:string; title:string; category:string; reports:number; status:"Review"|"Visible"|"Hidden"; suspended:boolean; content:string; reasons:string[] };
type Dialog = "rules"|"attachment"|"bulk"|"processed"|"destructive"|"done"|null;
const fixtures:Post[] = [
  {id:"p1",author:"Author •••1",title:"Pertanyaan tentang partikel に",category:"Tanya Sensei",reports:2,status:"Review",suspended:false,content:"Mohon jelaskan perbedaan penggunaan partikel に dan で pada konteks tempat aktivitas.",reasons:["Spam / promosi","Kategori tidak sesuai"]},
  {id:"p2",author:"Author •••2",title:"Tips flashcard N4",category:"Diskusi Member",reports:0,status:"Visible",suspended:false,content:"Saya membagi flashcard berdasarkan tema untuk membantu sesi review.",reasons:[]},
  {id:"p3",author:"Author •••3",title:"Pengumuman materi baru",category:"Info Hiru",reports:0,status:"Visible",suspended:false,content:"Materi latihan terbaru sudah tersedia untuk ditinjau member.",reasons:[]},
  {id:"p4",author:"Author •••4",title:"Promosi tidak relevan",category:"Diskusi Member",reports:4,status:"Hidden",suspended:false,content:"Konten promosi dilaporkan karena tidak relevan dengan pembelajaran.",reasons:["Spam / promosi","Kategori tidak sesuai"]},
  {id:"p5",author:"Author •••5",title:"Informasi kerja ke Jepang",category:"Kerja ke Jepang",reports:1,status:"Review",suspended:false,content:"Bagaimana cara memeriksa sumber informasi kerja sebelum dibagikan?",reasons:["Kategori tidak sesuai"]},
];

export default function CommunityPage() {
  const [items,setItems] = useState(fixtures),[selectedId,setSelectedId] = useState("p1"),[query,setQuery] = useState(""),[filter,setFilter] = useState("Semua"),[dialog,setDialog] = useState<Dialog>(null),[summary,setSummary] = useState(""),[reason,setReason] = useState(""),[error,setError] = useState(""),[action,setAction] = useState<"Remove"|"Suspend">("Remove");
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  const visible = useMemo(() => items.filter((item) => `${item.title} ${item.category} ${item.reports ? `${item.reports} Report`:"No Report"} ${item.status}`.toLowerCase().includes(query.toLowerCase()) && (filter === "Semua" || filter === "Reported" && item.reports > 0 || filter === "Hidden" && item.status === "Hidden" || item.category === filter)),[items,query,filter]);
  function nonDestructive(kind:"Keep Visible"|"Warn Author") { if (!summary.trim()) {setError("Ringkasan keputusan wajib diisi.");return;} setItems((list) => list.map((item) => item.id === selected.id && kind === "Keep Visible" ? {...item,status:"Visible"}:item));setError("");setDialog("processed"); }
  function openDestructive(kind:"Remove"|"Suspend") { setAction(kind);setReason("");setError("");setDialog("destructive"); }
  function confirm() { if (!reason.trim()) {setError("Alasan tindakan wajib diisi.");return;} setItems((list) => list.map((item) => item.id === selected.id ? action === "Remove" ? {...item,status:"Hidden"}:{...item,suspended:true}:item));setDialog("done"); }
  return <AdminShell current="communication"><main className="admin-page admin-a8-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • COMMUNITY GOVERNANCE</p><h1>Community Moderation</h1><p>Tinjau post, report, kategori akses, media, warning, removal, suspension, dan audit trail.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={() => setDialog("rules")}>Aturan Komunitas</button><button className="button button-primary" type="button" onClick={() => setDialog("bulk")}>Bulk Review</button></div></header>
    <section className="admin-kpi-grid">{[["Posts visible",items.filter((item) => item.status === "Visible").length,"Postingan yang aktif."],["Reported",items.filter((item) => item.reports > 0).length,"Memerlukan review."],["Hidden",items.filter((item) => item.status === "Hidden").length,"Disembunyikan oleh moderator."],["Suspended users",items.filter((item) => item.suspended).length,"Status berdasarkan policy."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a8-toolbar"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input aria-label="Cari community" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari post, kategori, report, atau status" /></label><div className="admin-filters">{["Semua","Reported","Tanya Sensei","Diskusi Member","Info Hiru","Hidden"].map((option) => <button className={filter === option ? "active":""} type="button" onClick={() => setFilter(option)} key={option}>{option}</button>)}</div></section>
    <div className="a8-layout"><section className="a8-queue"><header><h2>Antrean community</h2><p>Author dan status ditampilkan secara terbatas.</p></header>{visible.length ? visible.map((item) => <button className={selected.id === item.id ? "active":""} aria-pressed={selected.id === item.id} type="button" onClick={() => setSelectedId(item.id)} key={item.id}><span><strong>{item.title}</strong><small>{item.category} • author dimasking</small></span><span><b>{item.reports ? `${item.reports} Report`:"No Report"}</b><small>{item.status}{item.suspended ? " • Suspended":""}</small></span><em>Review</em></button>) : <section className="a8-empty"><strong>Tidak ada post sesuai filter.</strong><button className="button button-secondary" type="button" onClick={() => {setQuery("");setFilter("Semua");}}>Reset</button></section>}</section>
      <section className="a8-review"><header><div><p className="admin-kicker">{selected.author.toUpperCase()}</p><h2>{selected.title}</h2></div><span>{selected.status}</span></header><div className="a8-badges"><b>{selected.category}</b><span>{selected.reports ? `${selected.reports} Report`:"No Report"}</span>{selected.suspended && <span>Author Suspended • lokal</span>}</div><article className="a8-feedback-text"><strong>POST CONTENT</strong><p>{selected.content}</p></article><section className="a9-attachment"><span aria-hidden="true">画</span><div><strong>Screenshot materi</strong><small>Metadata file dari backend</small></div><button className="button button-secondary" type="button" onClick={() => setDialog("attachment")}>Lihat</button></section><section className="a9-reports"><strong>REPORT REASONS</strong>{selected.reasons.length ? <ul>{selected.reasons.map((item) => <li key={item}>{item}</li>)}</ul>:<p>Tidak ada report pada fixture ini.</p>}</section><div className="a8-form-grid"><label className="admin-field"><span>Keputusan</span><select defaultValue="Pertahankan"><option>Pertahankan</option><option>Warning</option><option>Remove</option></select></label><label className="admin-field"><span>Ringkasan</span><textarea rows={3} value={summary} onChange={(event) => setSummary(event.target.value)} /></label></div>{error && dialog === null && <p className="a4-validation" role="alert">{error}</p>}<div className="a8-actions"><button className="button button-primary" type="button" onClick={() => nonDestructive("Keep Visible")}>Keep Visible</button><button className="button button-dark" type="button" onClick={() => nonDestructive("Warn Author")}>Warn Author</button><button className="button button-secondary danger" type="button" onClick={() => openDestructive("Remove")}>Remove</button><button className="button button-secondary danger" type="button" onClick={() => openDestructive("Suspend")}>Suspend</button></div><aside className="a8-privacy"><strong>AUDIT TRAIL</strong><p>Keputusan, reason, actor, target, warning, removal, dan suspension harus tercatat.</p><small>Requirement saja; audit dan permission belum dipersistensikan.</small></aside></section></div>
    {dialog && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setDialog(null)} aria-label="Tutup state Community"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="community-dialog-title">
      {dialog === "rules" && <State title="Aturan komunitas tersedia" text="Admin dapat meninjau panduan posting, lampiran, laporan, dan sanksi moderasi." close={() => setDialog(null)} />}
      {dialog === "attachment" && <><p className="admin-kicker">COMMUNITY</p><h2 id="community-dialog-title">Lampiran postingan dapat ditinjau</h2><p>Admin dapat memeriksa media sebelum mempertahankan atau menghapus postingan.</p><div className="a9-media-placeholder"><span aria-hidden="true">画</span><strong>Screenshot materi</strong><small>Placeholder aman; file dan object storage tidak diakses.</small></div><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p><button className="button button-primary" type="button" onClick={() => setDialog(null)}>Kembali ke Moderasi</button></>}
      {dialog === "bulk" && <><p className="admin-kicker">COMMUNITY</p><h2 id="community-dialog-title">Bulk Review</h2><p>{items.filter((item) => item.reports > 0).length} fixture Reported siap ditinjau satu per satu. Bulk Remove dan Suspend tidak tersedia tanpa konteks serta konfirmasi.</p><button className="button button-primary" type="button" onClick={() => setDialog("processed")}>Selesaikan Review Non-destruktif</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Batal</button></>}
      {dialog === "processed" && <State title="Keputusan moderasi berhasil disimpan" text="Postingan dipertahankan atau penulis diberi peringatan sesuai aksi Admin." close={() => setDialog(null)} note="Fixture lokal saja; warning tidak mengirim notifikasi." />}
      {dialog === "destructive" && <><p className="admin-kicker">COMMUNITY • DESTRUKTIF</p><h2 id="community-dialog-title">Lanjutkan tindakan moderasi?</h2><p>Penghapusan postingan atau penangguhan penulis harus memiliki alasan yang dapat diaudit.</p><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p><label className="admin-field"><span>Alasan {action}</span><textarea rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error && <p className="a4-validation" role="alert">{error}</p>}<div><button className="button button-primary" type="button" onClick={confirm}>Konfirmasi Tindakan</button><button className="button button-secondary" type="button" onClick={() => setDialog(null)}>Batal</button></div></>}
      {dialog === "done" && <State title="Tindakan moderasi selesai" text="Konten atau akses penulis diperbarui dan notifikasi dikirim sesuai kebijakan." close={() => setDialog(null)} note="Interpretasi frontend: status fixture saja; konten, akun, notifikasi, dan audit nyata tidak berubah." />}
    </section></div>}
  </main></AdminShell>;
}
function State({title,text,close,note}:{title:string;text:string;close:()=>void;note?:string}) { return <><p className="admin-kicker">COMMUNITY</p><h2 id="community-dialog-title">{title}</h2><p>{text}</p><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p>{note && <p className="admin-local-feedback" role="status">{note}</p>}<button className="button button-primary" type="button" onClick={close}>Kembali ke Moderasi</button><button className="button button-secondary" type="button" disabled>Lihat Audit • OPEN</button></>; }
