"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

const questions = [
  { id: "q1", title: "Arti kosakata 毎朝", type: "Multiple Choice", status: "Ready", prompt: "Pilih arti yang tepat:", professional: "毎朝", beginner: "まいあさ", options: ["Setiap pagi","Setiap malam","Minggu depan","Kemarin"], correct: 0 },
  { id: "q2", title: "Pola kalimat rutinitas", type: "Multiple Choice", status: "Ready", prompt: "Pilih pola kalimat yang tepat.", professional: "毎日、日本語を＿＿。", beginner: "まいにち、にほんごを", options: ["勉強します","大きいです","静かです","先生です"], correct: 0 },
  { id: "q3", title: "Audio aktivitas pagi", type: "Audio", status: "Draft", prompt: "Dengarkan audio dan pilih jawaban.", professional: "朝の活動", beginner: "あさのかつどう", options: ["Pilihan A","Pilihan B","Pilihan C","Pilihan D"], correct: 1 },
  { id: "q4", title: "Reading pendek", type: "Reading", status: "Ready", prompt: "Baca teks lalu pilih jawaban.", professional: "少しずつ勉強を続けます。", beginner: "すこしずつ べんきょうを つづけます", options: ["Berhenti","Melanjutkan","Mengganti","Menunda"], correct: 1 },
  { id: "q5", title: "Kanji waktu", type: "Image", status: "Draft", prompt: "Pilih makna kanji.", professional: "時間", beginner: "じかん", options: ["Waktu","Tempat","Orang","Benda"], correct: 0 },
];

export default function MiniCheckpointBuilderPage() {
  const [level, setLevel] = useState("N4");
  const [session, setSession] = useState("2");
  const [part, setPart] = useState("1");
  const [selectedId, setSelectedId] = useState("q1");
  const [correct, setCorrect] = useState(0);
  const [saved, setSaved] = useState(false);
  const [media, setMedia] = useState(false);
  const editorRef = useRef<HTMLElement>(null);
  const selected = questions.find((question) => question.id === selectedId) ?? questions[0];

  function selectQuestion(id: string) { const question = questions.find((item) => item.id === id) ?? questions[0]; setSelectedId(id); setCorrect(question.correct); setSaved(false); }

  return <AdminShell current="content"><main className="admin-page admin-a3-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • MINI CHECKPOINT BUILDER</p><h1>Mini Checkpoint Builder</h1><p>Kelola Mini Checkpoint khusus LMS Plus: level N5–N2, sesi, part, timer, passing score, soal, gambar, review, dan publish.</p></div><div className="admin-header-actions"><Link className="button button-secondary" href="/admin/program/n4/chapters">Chapter Builder</Link><button className="button button-primary" type="button" onClick={() => setSaved(true)}>Simpan Mini Checkpoint</button></div></header>
    <section className="mini-context-bar"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input placeholder="Cari pertanyaan atau topik" /></label><label className="admin-field"><span>Level</span><select value={level} onChange={(event) => setLevel(event.target.value)}><option>N5</option><option>N4</option><option>N3</option><option>N2</option></select></label><label className="admin-field"><span>Sesi</span><select value={session} onChange={(event) => setSession(event.target.value)}><option>1</option><option>2</option><option>3</option></select></label><label className="admin-field"><span>Part</span><select value={part} onChange={(event) => setPart(event.target.value)}><option>1</option><option>2</option></select></label><button className="button button-dark" type="button" onClick={() => editorRef.current?.scrollIntoView({ behavior: "smooth" })}>Tambah Pertanyaan</button>{saved && <span className="admin-local-feedback" role="status">Mini Checkpoint tersimpan pada fixture lokal.</span>}</section>
    <section className="mini-context-summary"><p className="admin-kicker">LEVEL / SESI / PART</p>{[["Level",level],["Sesi",session],["Part",part],["Timer","Config"],["Passing","Config"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <div className="mini-builder-layout"><aside className="mini-question-bank"><header><h2>Bank pertanyaan</h2><p>Jumlah dan urutan dari konfigurasi.</p></header>{questions.map((question,index) => <button className={selected.id === question.id ? "active" : ""} type="button" onClick={() => selectQuestion(question.id)} key={question.id}><span>{String(index + 1).padStart(2,"0")}</span><div><strong>{question.title}</strong><small>{question.type}</small></div><b>{question.status}</b></button>)}<button className="a2-add-row" type="button" onClick={() => setSaved(false)}>Import Pertanyaan</button></aside>
      <section className="mini-editor" ref={editorRef}><header><div><p className="admin-kicker">PERTANYAAN {String(questions.findIndex((item) => item.id === selected.id) + 1).padStart(2,"0")} • {selected.type.toUpperCase()}</p><h2>Editor pertanyaan</h2></div><span className={`admin-status status-${selected.status === "Ready" ? "active" : "pending"}`}>{selected.status}</span></header><div className="a2-field-row"><label className="admin-field"><span>Tipe Soal</span><select defaultValue={selected.type} key={`${selected.id}-type`}><option>Multiple Choice</option><option>Audio</option><option>Reading</option><option>Image</option></select></label><label className="admin-field"><span>Kesulitan</span><select><option>Medium</option></select></label></div><label className="admin-field"><span>Ringkasan</span><textarea defaultValue={selected.prompt} key={`${selected.id}-prompt`} rows={3}/></label><div className="japanese-modes"><div className="jp-mode"><h4>Jepang Profesional</h4><label className="admin-field"><span>Teks Jepang</span><input defaultValue={selected.professional} key={`${selected.id}-professional`}/></label></div><div className="jp-mode"><h4>Jepang Pemula</h4><label className="admin-field"><span>State Pemula</span><input defaultValue={selected.beginner} key={`${selected.id}-beginner`}/></label></div></div><section className="mini-media"><span aria-hidden="true">画</span><div><h3>Media opsional</h3><p>Upload gambar opsional untuk soal Mini Checkpoint.</p></div><button className="button button-secondary" type="button" onClick={() => setMedia((value) => !value)}>{media ? "Hapus Gambar Lokal" : "Upload Gambar"}</button></section><section className="quiz-options-builder"><h4>Pilihan jawaban</h4>{selected.options.map((option,index) => <div className={`quiz-option-row ${correct === index ? "correct" : ""}`} key={`${selected.id}-${option}`}><label className="radio-label"><input type="radio" name={`mini-correct-${selected.id}`} checked={correct === index} onChange={() => { setCorrect(index); setSaved(false); }}/><span className="sr-only">Jawaban Benar</span></label><input defaultValue={option} /><span>{correct === index ? "Jawaban Benar" : "Opsi"}</span></div>)}</section><label className="admin-field"><span>Penjelasan</span><textarea defaultValue="Penjelasan fixture dapat diedit dan tidak tersimpan ke backend." rows={3}/></label></section></div>
    <div className="mini-lower-layout"><section className="a2-panel"><h2>Mini Checkpoint settings</h2>{[["Randomisasi soal","Urutan dapat diacak per attempt.","Config"],["Randomisasi opsi","Pilihan jawaban dapat diacak.","Config"],["Timer","Durasi mengikuti assessment.","Dinamis"],["Passing logic","Nilai minimum dari admin.","Dinamis"],["Attempt rules","Jumlah percobaan dan cooldown.","Dinamis"],["Review availability","Tersedia mengikuti konfigurasi.","Config"],["Publication state","Draft / Terjadwal / Aktif.","Config"]].map(([title,detail,state]) => <div className="a2-setting-row" key={title}><div><strong>{title}</strong><small>{detail}</small></div><span>{state}</span></div>)}</section><section className="mini-student-preview"><p className="admin-kicker">Preview siswa</p><h2>{selected.prompt}</h2><strong>{selected.professional}</strong><span>A. {selected.options[0]}</span><button className="button button-secondary" type="button">Buka Preview</button></section></div>
    <footer className="builder-footer"><span className="button button-secondary disabled" aria-disabled="true">Cohort &amp; Kelas</span><p>Perubahan assessment aktif setelah disimpan dan dipublikasikan.</p></footer>
  </main></AdminShell>;
}
