"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Invoice = { id:string; user:string; program:string; status:string; source:string };
type State = "verify" | "proof" | "verified" | "reject" | "rejected" | "export" | null;
const fixtures: Invoice[] = [
  { id:"INV•••001", user:"Member •••1", program:"N4 • Belajar Mandiri", status:"Menunggu", source:"WhatsApp / admin flow" },
  { id:"INV•••002", user:"Member •••2", program:"N4 • Belajar dengan Sensei", status:"Terverifikasi", source:"WhatsApp / admin flow" },
  { id:"INV•••003", user:"Member •••3", program:"N5 • Belajar Mandiri", status:"Ditolak", source:"WhatsApp / admin flow" },
  { id:"INV•••004", user:"Member •••4", program:"Renewal • LMS", status:"Menunggu", source:"WhatsApp / admin flow" },
];

export default function InvoicesPage() {
  const [invoices,setInvoices] = useState(fixtures);
  const [query,setQuery] = useState("");
  const [filter,setFilter] = useState("Semua");
  const [selectedId,setSelectedId] = useState("INV•••001");
  const [state,setState] = useState<State>(null);
  const [reason,setReason] = useState("");
  const [error,setError] = useState("");
  const selected = invoices.find((invoice) => invoice.id === selectedId) ?? invoices[0];
  const visible = useMemo(() => invoices.filter((invoice) => (filter === "Semua" || filter === "Periode" || invoice.status === filter) && `${invoice.id} ${invoice.user} ${invoice.program}`.toLowerCase().includes(query.toLowerCase())),[invoices,filter,query]);
  function open(invoice:Invoice) { setSelectedId(invoice.id); setReason(""); setError(""); setState("verify"); }
  function requireReason(next:"verified"|"reject") { if (!reason.trim()) { setError("Ringkasan wajib diisi sebelum tindakan sensitif."); return; } setError(""); if (next === "verified") { setInvoices((items) => items.map((invoice) => invoice.id === selected.id ? {...invoice,status:"Terverifikasi"}:invoice)); } setState(next); }
  function reject() { setInvoices((items) => items.map((invoice) => invoice.id === selected.id ? {...invoice,status:"Ditolak"}:invoice)); setState("rejected"); }

  return <AdminShell current="transaction"><main className="admin-page admin-a5-page">
    <header className="admin-header"><div><p className="admin-kicker">ADMIN • TRANSACTIONS &amp; ACTIVATION</p><h1>Invoice Management</h1><p>Kelola invoice, bukti pembayaran, verifikasi, aktivasi membership, dan audit trail.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={() => setState("export")}>Export Data</button><Link className="button button-secondary" href="/admin">Dashboard</Link></div></header>
    <aside className="a5-critical"><strong>Pengumuman</strong><p>Aktivasi membership hanya dilakukan setelah transaksi diverifikasi.</p></aside>
    <section className="admin-kpi-grid">{[["Menunggu verifikasi","Dinamis","Antrean transaksi dari backend."],["Terverifikasi","Dinamis","Membership telah diaktifkan."],["Ditolak / batal","Dinamis","Memerlukan alasan dan catatan."],["Nilai transaksi","Dinamis","Mengikuti data terverifikasi."]].map(([label,value,meta]) => <article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>{value}</strong><small>{meta}</small></article>)}</section>
    <section className="a5-filters"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari invoice, pengguna, atau program" /></label><div className="admin-filters">{["Semua","Menunggu","Terverifikasi","Ditolak","Periode"].map((item) => <button className={filter === item ? "active":""} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></section>
    <section className="admin-table-container a5-table">{visible.length ? <table className="admin-table"><thead><tr><th>Invoice</th><th>Pengguna</th><th>Program</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{visible.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.id}</strong><small>Dibuat sistem</small></td><td><strong>{invoice.user}</strong><small>Data dimasking</small></td><td><strong>{invoice.program}</strong><small>Level dan plan</small></td><td><strong>Dinamis</strong><small>Dari backend</small></td><td><span className={`admin-status status-${invoice.status === "Terverifikasi" ? "active":"pending"}`}>{invoice.status}</span></td><td><button type="button" onClick={() => open(invoice)}>Lihat Detail</button></td></tr>)}</tbody></table> : <section className="a4-empty-table"><h2>Belum ada data untuk filter ini</h2><p>Ubah filter atau kata kunci.</p><button className="button button-secondary" type="button" onClick={() => {setQuery("");setFilter("Semua");}}>Reset Filter</button></section>}</section>
    {state && <div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={() => setState(null)} aria-label="Tutup state invoice"/><section className="a4-dialog a5-dialog" role="dialog" aria-modal="true" aria-labelledby="invoice-dialog-title">
      {state === "verify" && <><p className="admin-kicker">INVOICE VERIFICATION</p><h2 id="invoice-dialog-title">{selected.id} • {selected.status}</h2><aside><strong>Pengumuman</strong><p>Verifikasi mengaktifkan membership dan reward referral yang memenuhi aturan; semua perubahan dicatat pada audit log.</p></aside><dl>{[["Pengguna",selected.user],["Program",selected.program],["Nominal","Mengikuti data transaksi"],["Status",selected.status],["Sumber",selected.source]].map(([term,value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl><section className="a5-proof"><strong>Bukti pembayaran</strong><p>File, waktu unggah, dan metadata berasal dari backend.</p><button className="button button-secondary" type="button" onClick={() => setState("proof")}>Lihat Bukti</button></section><h3>Aktivasi membership &amp; referral</h3><label className="admin-field"><span>Plan</span><input value={selected.program} readOnly /></label><label className="admin-field"><span>Periode Akses</span><input value="Dari konfigurasi produk" readOnly /></label><p className="a5-rule">Reward hanya aktif jika kode valid, bukan self-referral, dan invoice tidak dibatalkan.</p><label className="admin-field"><span>Ringkasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation" role="alert">{error}</p>}<div><button className="button button-primary" type="button" onClick={() => requireReason("verified")}>Verifikasi &amp; Aktifkan</button><button className="button button-secondary danger" type="button" onClick={() => requireReason("reject")}>Tolak Invoice</button><button className="button button-secondary" type="button" onClick={() => setState(null)}>Kembali</button></div></>}
      {state === "proof" && <><p className="admin-kicker">INVOICE</p><h2 id="invoice-dialog-title">Bukti pembayaran dapat ditinjau</h2><div className="a5-proof-preview"><strong>Evidence placeholder</strong><p>Admin memeriksa identitas, nominal, waktu transaksi, dan kecocokan invoice. Tidak ada bukti bank yang difabrikasi.</p></div><p>Pratinjau bukti tidak mengaktifkan membership.</p><div><button className="button button-secondary" type="button" onClick={() => setState("verify")}>Kembali ke Invoice</button><button className="button button-primary" type="button" onClick={() => setState("verify")}>Lanjut Verifikasi</button></div></>}
      {state === "verified" && <section className="a4-success"><p className="admin-kicker">ADMIN • VERIFIKASI INVOICE</p><h2 id="invoice-dialog-title">Invoice berhasil diverifikasi</h2><span aria-hidden="true">✓</span><p>Membership aktif dan reward referral yang valid diproses sesuai aturan backend. Demo hanya mengubah fixture sesi; Student tidak berubah.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Invoice Management</button></section>}
      {state === "reject" && <><p className="admin-kicker">ADMIN • KONFIRMASI INVOICE</p><h2 id="invoice-dialog-title">Tolak invoice ini?</h2><p>Invoice akan ditandai ditolak. Alasan verifikasi dan tindakan admin tetap dicatat.</p><label className="admin-field"><span>Alasan</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3}/></label>{error && <p className="a4-validation">{error}</p>}<div><button className="button button-primary" type="button" onClick={() => reason.trim() ? reject() : setError("Alasan wajib diisi.")}>Konfirmasi Tolak</button><button className="button button-secondary" type="button" onClick={() => setState("verify")}>Batal</button></div></>}
      {state === "rejected" && <section className="a4-success"><p className="admin-kicker">ADMIN • INVOICE DITOLAK</p><h2 id="invoice-dialog-title">Invoice ditandai ditolak</h2><p>Perubahan hanya fixture lokal; audit belum dipersistensikan.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali ke Invoice Management</button></section>}
      {state === "export" && <section className="a4-success"><p className="admin-kicker">ADMIN • EXPORT</p><h2 id="invoice-dialog-title">Export sedang diproses</h2><p>Permission, masking, filter aktif, dan audit wajib diperiksa backend. Tidak ada file dibuat.</p><button className="button button-primary" type="button" onClick={() => setState(null)}>Kembali</button></section>}
    </section></div>}
  </main></AdminShell>;
}
