"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Event={id:string;glyph:string;event:string;category:string;actor:string;target:string;outcome:"Success"|"Denied"|"Pending";reason:string;description:string;before?:string;after?:string};
const fixtures:Event[]=[{id:"EVT•••001",glyph:"鍵",event:"User Access Updated",category:"Access",actor:"Admin •••1",target:"Member •••1",outcome:"Success",reason:"Upgrade membership terverifikasi",description:"Perubahan entitlement pengguna",before:"Plan: Free Member • Level: N4 • Access: Chapter 1",after:"Plan: Belajar Mandiri • Level: N4 • Access: Full Journey"},{id:"EVT•••002",glyph:"請",event:"Invoice Verified",category:"Transaction",actor:"Admin •••2",target:"INV•••001",outcome:"Success",reason:"Verifikasi pembayaran dari backend",description:"Status invoice terverifikasi"},{id:"EVT•••003",glyph:"公",event:"Chapter Published",category:"Content",actor:"Admin •••1",target:"N4 • Chapter 4",outcome:"Success",reason:"Konten memenuhi validasi publikasi",description:"Chapter dipublikasikan"},{id:"EVT•••004",glyph:"録",event:"Sensitive Export",category:"Export",actor:"Admin •••3",target:"User Dataset",outcome:"Denied",reason:"Permission backend tidak terpenuhi",description:"Export sensitif ditolak"},{id:"EVT•••005",glyph:"公",event:"Replay Published",category:"Replay",actor:"Admin •••2",target:"Replay •••4",outcome:"Success",reason:"Replay memenuhi validasi akses",description:"Replay dipublikasikan"},{id:"EVT•••006",glyph:"録",event:"Permission Change",category:"Permission",actor:"Admin •••1",target:"Role Policy",outcome:"Pending",reason:"Menunggu backend validation",description:"Perubahan permission diproses"}];
type Dialog="action"|"export"|null;
export default function AuditLogsPage(){
 const [selectedId,setSelectedId]=useState("EVT•••001"),[query,setQuery]=useState(""),[category,setCategory]=useState("Semua Event"),[outcome,setOutcome]=useState("Semua Outcome"),[period,setPeriod]=useState("Periode Backend"),[dialog,setDialog]=useState<Dialog>(null),selected=fixtures.find((item)=>item.id===selectedId)??fixtures[0];
 const visible=useMemo(()=>fixtures.filter((item)=>`${item.event} ${item.actor} ${item.target} ${item.reason}`.toLowerCase().includes(query.toLowerCase())&&(category==="Semua Event"||item.category===category)&&(outcome==="Semua Outcome"||item.outcome===outcome)),[query,category,outcome]);
 function reset(){setQuery("");setCategory("Semua Event");setOutcome("Semua Outcome");setPeriod("Periode Backend");}
 return <AdminShell current="settings"><main className="admin-page admin-a8-page"><header className="admin-header"><div><p className="admin-kicker">ADMIN • SECURITY &amp; TRACEABILITY</p><h1>Audit Logs</h1><p>Tinjau actor, target, event, timestamp, reason, outcome, permission, dan perubahan sensitif.</p></div><button className="button button-primary" type="button" onClick={()=>setDialog("export")}>Ekspor Audit</button></header>
 <section className="admin-kpi-grid">{[["Events","Jumlah event pada periode."],["Sensitive changes","Akses, transaksi, permission."],["Denied actions","Aksi yang ditolak backend."],["Export events","Export yang tercatat."]].map(([label,meta])=><article className="admin-kpi-card" key={label}><h2>{label}</h2><strong>Dinamis</strong><small>{meta}</small></article>)}</section>
 <section className="a13-audit-filters"><label className="admin-search-box"><span aria-hidden="true">⌕</span><input type="search" aria-label="Cari Audit" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Cari event, actor termasking, target, atau reason" /></label><label className="admin-field"><span>Category</span><select value={category} onChange={(event)=>setCategory(event.target.value)}><option>Semua Event</option>{[...new Set(fixtures.map((item)=>item.category))].map((item)=><option key={item}>{item}</option>)}</select></label><label className="admin-field"><span>Outcome</span><select value={outcome} onChange={(event)=>setOutcome(event.target.value)}><option>Semua Outcome</option><option>Success</option><option>Denied</option><option>Pending</option></select></label><label className="admin-field"><span>Periode</span><select value={period} onChange={(event)=>setPeriod(event.target.value)}><option>Periode Backend</option></select></label></section>
 <div className="a8-layout"><section className="a8-queue"><header><h2>Recorded events</h2><p>Fixture evidence read-only; actor dan target dimasking.</p></header>{visible.length?visible.map((item)=><button aria-pressed={selected.id===item.id} className={selected.id===item.id?"active":""} type="button" onClick={()=>setSelectedId(item.id)} key={item.id}><span><strong><i className="a9-glyph">{item.glyph}</i>{item.event}</strong><small>{item.actor} • Actor dimasking</small></span><span><b>{item.outcome}</b><small>{item.target}</small></span><em>Detail</em></button>):<section className="a8-empty"><strong>Tidak ada audit event sesuai filter.</strong><button className="button button-secondary" type="button" onClick={reset}>Reset</button></section>}</section>
 <section className="a8-review"><header><div><p className="admin-kicker">{selected.event.toUpperCase()}</p><h2>{selected.description}</h2></div><span>{selected.outcome}</span></header><dl className="a13-audit-meta">{[["Actor",selected.actor],["Target",selected.target],["Timestamp","Dari backend"],["IP / Device","Dimasking sesuai policy"],["Reason",selected.reason],["Outcome",selected.outcome]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><section className="a13-diff"><strong>CHANGE DIFF</strong><div><article><small>BEFORE</small><p>{selected.before??"Evidence sebelum perubahan mengikuti metadata backend."}</p></article><article><small>AFTER</small><p>{selected.after??"Evidence setelah perubahan mengikuti metadata backend."}</p></article></div></section><section className="a11-block"><strong>REASON &amp; EVIDENCE</strong><p>Reason, related invoice, actor permission, dan backend checks tersimpan sebagai metadata event.</p></section><div className="a8-actions"><button className="button button-primary" type="button" onClick={()=>setDialog("action")}>Salin ID Event</button><button className="button button-secondary" type="button" onClick={()=>setDialog("action")}>Data Terkait</button><button className="button button-dark" type="button" onClick={()=>setDialog("export")}>Ekspor Event</button></div><aside className="a8-privacy"><strong>RETENTION &amp; ACCESS</strong><p>Retention, export, dan visibility audit log mengikuti policy, permission, serta backend source of truth.</p><small>Periode retention belum ditetapkan; Audit tidak dapat diedit atau dihapus.</small></aside></section></div>
 {dialog&&<div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={()=>setDialog(null)} aria-label="Tutup state Audit"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="audit-state-title">{dialog==="action"?<><p className="admin-kicker">AUDIT</p><h2 id="audit-state-title">Aksi audit berhasil diproses</h2><p>ID event disalin, record terkait dibuka, atau data ekspor disiapkan sesuai permission.</p><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p><p className="admin-local-feedback" role="status">Fixture {selected.id}; tidak ada production ID, record transport, atau audit persistence.</p><div><button className="button button-primary" type="button" onClick={()=>setDialog(null)}>Kembali ke Audit</button><Link className="button button-secondary" href="/admin">Dashboard</Link></div></>:<><p className="admin-kicker">ADMIN • EXPORT</p><h2 id="audit-state-title">Export sedang diproses</h2><p>Dataset, masking, permission, dan ukuran file diperiksa sebelum tautan download tersedia.</p><ul className="a8-steps"><li>Permission check</li><li>Backend validation</li><li>Audit event</li></ul><p className="admin-local-feedback" role="status">Tidak ada file, Blob, dataset, atau download URL dibuat.</p><button className="button button-primary" type="button" onClick={()=>setDialog(null)}>Kembali ke Audit</button></>}</section></div>}
 </main></AdminShell>;
}
