import type { Membership } from "@/lib/dashboard-mock";
export type SupportingKind = "library" | "practice" | "progress" | "leaderboard" | "certificate" | "community" | "notifications" | "profile" | "renewal" | "createPost";
type Card = { icon: string; status: string; title: string; description: string; action?: string; href?: string };
type SupportingData = { eyebrow: string; title: string; description: string; locked?: boolean; cards: Card[]; notice?: { title: string; description: string } };
const card = (icon: string, status: string, title: string, description: string, action?: string, href?: string): Card => ({ icon, status, title, description, action, href });
export const supportingData: Record<SupportingKind, SupportingData> = {
  library: { eyebrow: "PERPUSTAKAAN MATERI", title: "Temukan kembali materi dari seluruh journey", description: "Akses material mengikuti level dan entitlement membership.", locked: true, cards: [card("-", "Tersimpan", "Tata Bahasa", "Pola Kalimat Sehari-hari. Modul Chapter 4 yang terakhir dibuka.", "Buka", "/learn/n4/chapter-1"), card("", "Tersedia", "Kanji", "Keadaan, Waktu & Aktivitas. Kanji chapter dengan bookmark dan catatan."), card("AUDIO", "Terkunci", "Audio", "Simulasi Choukai N4. Akses audio lengkap mengikuti membership.", "Lihat Membership", "/renewal")], notice: { title: "LIBRARY EMPTY", description: "Belum ada materi pada filter ini. Ubah level, kategori, atau kata kunci untuk menemukan materi yang tersedia." } },
  practice: { eyebrow: "LATIHAN HARIAN FREE MEMBER", title: "Latihan singkat berdasarkan progresmu", description: "Aktivitas harian terpisah dari simulasi Try Out dan tidak mengurangi attempt Try Out.", locked: true, cards: [card("o-", "REKOMENDASI", "Flashcard Review", "Ulangi kosakata dan pola dengan confidence state.", "Mulai Rekomendasi", "/journey"), card("AUDIO", "TERSEDIA", "Audio Drill", "Latihan listening dari Chapter aktif."), card("-", "TERSEDIA", "Reading Drill", "Bacaan pendek dengan penjelasan jawaban."), card("c", "TERSEDIA", "Checkpoint Retry", "Ulangi checkpoint sesuai attempt rule Chapter.")] },
  progress: { eyebrow: "PROGRES & ACHIEVEMENT", title: "Rayakan progres tanpa kehilangan fokus", description: "Progress, streak, mastery, dan achievement dihitung dari journey serta aktivitas backend.", cards: [card("+-", "65%", "Journey N4", "Perjalanan belajar terus bertumbuh."), card("", "450", "Kanji mastered", "Kanji yang dikuasai dari aktivitas belajar."), card("?", "Terbuka", "Streak 7 Hari", "Belajar konsisten selama tujuh hari."), card("c", "Belum terbuka", "Try Out Finisher", "Menyelesaikan Try Out pertama."), card("CERT", "Terkunci", "Certificate Ready", "Memenuhi eligibility sertifikat.")], notice: { title: "Achievement", description: "Leaderboard tersedia untuk melihat konsistensi belajar." } },
  leaderboard: { eyebrow: "LEADERBOARD", title: "Bandingkan konsistensi, bukan tekanan", description: "Poin, periode, cohort, rank, dan movement berasal dari backend serta dapat menggunakan nama samaran.", cards: [1,2,3,4,5,6,7,8].map((rank) => card(rank === 7 ? "Kamu" : `0${rank}`, rank === 7 ? "Posisimu saat ini" : "Member community", rank === 7 ? "Kamu" : `Member ${rank}`, "Poin", rank === 7 ? "+ 3" : "")) },
  certificate: { eyebrow: "CERTIFICATE CENTER", title: "Sertifikat digital dari milestone yang tervalidasi", description: "Eligibility, issuance, download, dan status sertifikat berasal dari backend. Scope menggunakan sertifikat digital saja.", cards: [] },
  community: { eyebrow: "FORUM KOMUNITAS", title: "Berdiskusi, bertanya, dan berbagi perjalanan belajar", description: "Free Member dapat membaca. Post, komentar, dan Tanya Sensei tetap terkunci sesuai entitlement.", cards: [card("c", "READ ONLY", "Perbedaan penggunaan untuk tempat?", "Pertanyaan grammar untuk memahami konteks aktivitas dan lokasi.", "Baca", "/community/post"), card("Y", "Semua Akses", "Pengingat jadwal dan materi minggu ini", "Info dari Hiru untuk pembelajar."), card("c", "Diskusi Member", "Tips menjaga konsistensi flashcard N4", "Forum diskusi dengan sesama pembelajar.")] },
  createPost: { eyebrow: "BUAT POSTINGAN", title: "Bagikan pertanyaan atau pengalaman belajar", description: "Postingan mengikuti aturan komunitas dan dapat melalui moderasi.", cards: [] },
  notifications: { eyebrow: "NOTIFICATION CENTER", title: "Informasi penting tanpa mengganggu fokus", description: "Notifikasi, status baca, trigger, waktu, dan delivery berasal dari backend serta preference akun.", cards: [card("", "Belajar", "Materi Chapter 4 tersedia", "Lanjutkan video, modul, dan latihan pada journey aktif.", "Buka Chapter", "/learn/n4/chapter-1"), card("T,", "Class", "Pengingat sesi Zoom", "Jadwal, Sensei, dan link mengikuti konfigurasi admin."), card("+?", "Class", "Progress chapter diperbarui", "Perubahan progress mengikuti aktivitas dan data backend.", "Buka Progress", "/progress"), card("?", "Achievement", "Achievement baru terbuka", "Streak belajar berhasil mencapai milestone baru.", "Lihat Achievement", "/progress"), card("CERT", "Achievement", "Sertifikat digital tersedia", "Sertifikat dapat dilihat dan diunduh dari Certificate Center.")] },
  profile: { eyebrow: "AKUN & MEMBERSHIP", title: "Profil dan status belajarmu", description: "Kelola informasi akun, membership, sertifikat, dan preferensi.", cards: [card("", "Hilmi", "Level N4", "hilmi.student@example.com"), card("-%", "Free Member", "STATUS MEMBERSHIP", "Periode akses dan tanggal akhir berasal dari backend.", "Perpanjang Membership", "/renewal"), card("CERT", "Terkunci", "Sertifikat", "Sertifikat mengikuti eligibility dan tetap terkunci untuk Free Member."), card("Y", "Tersedia", "Notifikasi", "Atur pengingat belajar dan informasi kelas.", "Buka", "/notifications")] },
  renewal: { eyebrow: "MEMBERSHIP RENEWAL", title: "Lanjutkan akses tanpa kehilangan progres", description: "Harga dan periode baru tampil setelah plan dipilih; data berasal dari konfigurasi admin.", cards: [card("-%", "Membership Aktif", "Free Member", "Progres tetap tersimpan setelah renewal."), card("o", "Pilih plan lanjutan", "Belajar Mandiri", "Harga dan periode mengikuti konfigurasi admin."), card(".^", "Pilih plan lanjutan", "Belajar dengan Sensei", "Semua fitur mengikuti entitlement yang diverifikasi.")] }
};
export function getSupportingData(kind: SupportingKind, membership: Membership) { return { ...supportingData[kind], membership }; }
