"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { AdminShell } from "@/components/admin-shell";

type Dialog="review"|"saved"|"security"|null;
const nav=["Branding","Locale & Defaults","Support","Privacy & Security","Integrations","Admin Profile"];
export default function SettingsPage(){
 const [product,setProduct]=useState("Hiru Academy"),[shortName,setShortName]=useState("Hiru"),[summary,setSummary]=useState(""),[language,setLanguage]=useState("Indonesia"),[timezone,setTimezone]=useState("Asia/Jakarta"),[currency,setCurrency]=useState("IDR"),[supportEmail,setSupportEmail]=useState("Belum diberikan client"),[supportWa,setSupportWa]=useState("Belum diberikan client"),[supportHours,setSupportHours]=useState("Belum diberikan client"),[dialog,setDialog]=useState<Dialog>(null),[dirty,setDirty]=useState(false),[logo,setLogo]=useState("Asset branding dari konfigurasi");
 const refs=useRef<Record<string,HTMLElement|null>>({});function change(){setDirty(true)}function go(id:string){refs.current[id]?.scrollIntoView({behavior:"smooth",block:"start"});refs.current[id]?.focus();}
 return <AdminShell current="settings"><main className="admin-page admin-a13-settings"><header className="admin-header"><div><p className="admin-kicker">ADMIN • SYSTEM CONFIGURATION</p><h1>General Settings</h1><p>Kelola branding, support placeholders, locale, defaults, privacy, security, integrations, dan feature settings.</p></div><div className="admin-header-actions"><button className="button button-secondary" type="button" onClick={()=>setDialog("review")}>Review Changes</button><button className="button button-primary" type="button" onClick={()=>{setDirty(false);setDialog("saved");}}>Simpan Pengaturan</button></div></header>
 <aside className="a13-security-announcement"><strong>Pengumuman</strong><p>Jangan menyimpan secret, token, atau credential sensitif langsung pada UI atau file desain.</p></aside><nav className="a13-settings-nav" aria-label="Bagian General Settings">{nav.map((item)=><button type="button" onClick={()=>go(item)} key={item}>{item}</button>)}</nav>
 <div className="a13-settings-grid"><Section id="Branding" innerRef={(n)=>refs.current["Branding"]=n} title="Branding" text="Logo, nama produk, warna, favicon, dan asset publik mengikuti brand system."><section className="a10-media"><div><strong>Hiru Academy</strong><small>{logo}</small></div><button type="button" onClick={()=>{setLogo(logo?"":"Asset logo fixture");change();}}>Ganti Logo</button></section><div className="a8-form-grid"><Field label="Nama Produk" value={product} set={(value)=>{setProduct(value);change();}}/><Field label="Nama Pendek" value={shortName} set={(value)=>{setShortName(value);change();}}/></div><Field label="Ringkasan" value={summary} set={(value)=>{setSummary(value);change();}}/></Section>
 <Section id="Locale & Defaults" innerRef={(n)=>refs.current["Locale & Defaults"]=n} title="Locale & System Defaults"><div className="a13-three-fields"><Select label="Bahasa" value={language} set={(v)=>{setLanguage(v);change();}}/><Select label="Timezone" value={timezone} set={(v)=>{setTimezone(v);change();}}/><Select label="Mata Uang" value={currency} set={(v)=>{setCurrency(v);change();}}/></div><div className="a11-block">{[["章","Default Program","Tidak dipilih otomatis tanpa data."],["役","Default Role","Student untuk akun baru."],["知","Notification","Mengikuti preference user."]].map(([glyph,title,text])=><div className="a13-setting-row" key={title}><span>{glyph}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></Section>
 <Section id="Support" innerRef={(n)=>refs.current["Support"]=n} title="Support & Public Contact" text="Kontak support, WhatsApp, email, dan jam layanan harus diisi dari data client."><div className="a13-three-fields"><Field label="Email Support" value={supportEmail} set={(v)=>{setSupportEmail(v);change();}}/><Field label="WhatsApp Support" value={supportWa} set={(v)=>{setSupportWa(v);change();}}/><Field label="Jam Layanan" value={supportHours} set={(v)=>{setSupportHours(v);change();}}/></div><aside className="a10-testimonial"><strong>Pengumuman</strong><p>Kontak publik tidak boleh dipublikasikan sebelum data resmi client tersedia.</p></aside></Section>
 <Section id="Privacy & Security" innerRef={(n)=>refs.current["Privacy & Security"]=n} title="Privacy & Security" text="Aturan data, masking, session, permission, dan audit."><StatusGrid items={[["隠","Data masking","Masking PII pada list, export, dan desain.","Configured"],["鍵","Backend authorization","Semua akses sensitif diperiksa server.","Configured"],["時","Session policy","Durasi dan logout mengikuti security config.","Pending"],["録","Audit logging","Actor, target, reason, dan outcome dicatat.","Configured"],["保","Data retention","Periode retention perlu policy resmi.","Missing"]]} /></Section>
 <Section id="Integrations" innerRef={(n)=>refs.current["Integrations"]=n} title="Integrations" text="Status koneksi tanpa menampilkan secret atau credential."><StatusGrid items={[["会","Zoom integration","Connection status dan account reference.","Pending"],["郵","Email provider","Provider dan delivery status.","Pending"],["払","Payment / verification","Flow transaksi dan webhook status.","Pending"],["像","Media storage","Storage status untuk file dan replay.","Configured"],["分","Analytics","Event collection dan privacy state.","Pending"]]} /></Section>
 <Section id="Admin Profile" innerRef={(n)=>refs.current["Admin Profile"]=n} title="ADMIN •••1" text="Profile dan role dari backend"><div className="a8-badges"><b>MFA Required</b></div><dl className="a13-audit-meta">{[["Email","Dimasking"],["Role","Permission-driven"],["Password","Last changed dinamis"],["Active sessions","Backend data"],["Recovery","Policy-controlled"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="a8-actions"><button className="button button-primary" type="button" onClick={()=>setDialog("security")}>Kelola MFA</button><button className="button button-secondary" type="button" onClick={()=>setDialog("security")}>Ubah Password</button></div><aside className="a8-privacy"><strong>SECURITY NOTE</strong><p>Jangan tampilkan credential, recovery secret, atau session token pada UI.</p></aside></Section>
 <Section id="Feature Defaults" innerRef={(n)=>refs.current["Feature Defaults"]=n} title="Feature Defaults" text="Default state produk; entitlement tetap berasal dari backend."><StatusGrid items={[["","Placement Test","Public tanpa akun, lead wajib.","On"],["","Digital Certificate","Digital only.","On"],["","Community","Read/write sesuai plan.","On"],["","Jepang Pemula","Bukan screen terpisah.","Editor State"],["","Zoom & Replay","Hanya Belajar dengan Sensei dan publish admin.","Conditional"]]} /><aside className="a10-controlled"><strong>SAVE &amp; REVIEW</strong><p>Perubahan branding, privacy, integration, atau default sensitif perlu review, backend validation, dan audit log.</p><p>{dirty?"Perubahan fixture lokal belum disimpan.":"Tidak ada perubahan fixture lokal."}</p></aside></Section></div>
 {dialog&&<div className="admin-dialog-layer"><button className="admin-dialog-backdrop" type="button" onClick={()=>setDialog(null)} aria-label="Tutup state Pengaturan"/><section className="a4-dialog a8-dialog" role="dialog" aria-modal="true" aria-labelledby="settings-state-title">{dialog==="review"?<><p className="admin-kicker">ADMIN • PERMISSION</p><h2 id="settings-state-title">Kamu tidak memiliki permission</h2><p>Role saat ini tidak diizinkan menjalankan tindakan sensitif ini. Backend menolak request.</p><ul className="a8-steps"><li>Permission check</li><li>Backend validation</li><li>Audit event</li></ul><p className="admin-local-feedback">Representasi visual saja; browser bukan authorization authority.</p><button className="button button-primary" type="button" onClick={()=>setDialog(null)}>Tutup</button></>:dialog==="security"?<><p className="admin-kicker">KEAMANAN</p><h2 id="settings-state-title">Pengaturan keamanan siap dikelola</h2><p>MFA dan perubahan kata sandi membutuhkan autentikasi ulang serta audit.</p><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p><p className="admin-local-feedback">Tidak ada password form, MFA secret, QR, recovery code, atau session token.</p><div><button className="button button-primary" type="button" onClick={()=>setDialog(null)}>Kembali ke Pengaturan</button><Link className="button button-secondary" href="/admin/audit-logs">Lihat Audit</Link></div></>:<><p className="admin-kicker">PENGATURAN</p><h2 id="settings-state-title">Pengaturan berhasil disimpan</h2><p>Konfigurasi umum atau aset brand telah diperbarui dan dicatat pada audit log.</p><p>Aksi mengikuti permission Admin dan dicatat pada audit log.</p><p className="admin-local-feedback">Fixture lokal saja; backend, Public, Student, integrasi, security, dan audit nyata tidak berubah.</p><div><button className="button button-primary" type="button" onClick={()=>setDialog(null)}>Kembali ke Pengaturan</button><Link className="button button-secondary" href="/admin/audit-logs">Lihat Audit</Link></div></>}</section></div>}
 </main></AdminShell>;
}
function Section({id,title,text,children,innerRef}:{id:string;title:string;text?:string;children:React.ReactNode;innerRef:(node:HTMLElement|null)=>void}){return <section className="a10-panel a13-section" tabIndex={-1} ref={innerRef}><header><h2>{title}</h2>{text&&<p>{text}</p>}</header><div>{children}</div></section>}
function Field({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <label className="admin-field"><span>{label}</span><input value={value} onChange={(event)=>set(event.target.value)} /></label>}
function Select({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <label className="admin-field"><span>{label}</span><select value={value} onChange={(event)=>set(event.target.value)}><option>{value}</option></select></label>}
function StatusGrid({items}:{items:string[][]}){return <div className="a13-status-grid">{items.map(([glyph,title,text,status])=><article key={title}>{glyph&&<span>{glyph}</span>}<div><strong>{title}</strong><p>{text}</p></div><b>{status}</b></article>)}</div>}
